### ISSUE TITLE
mobile safari needs to respond with proper capabilities

### ISSUE THREAD

**Issue by lukeis** [ios-driver/ios-driver#1]
the capability response should include:

browserName: Safari
platform: iOS
javascriptEnabled: true

maybe more... @jarib :)

**Comment by nicegraham** [comment]
I've added a fix:
https://github.com/nicegraham/ios-driver/commit/5bdba9556678918fdc08344682b6fbd0c7fac165

the response https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#L216 now looks like:
https://gist.github.com/nicegraham/5262806

**Comment by lukeis** [comment]
Thanks :)

You should have push access... Everything I see says you should.

**Comment by nicegraham** [comment]
Franois sorted it - code has been pushed to this repo. You can do what you want with it now :)
