### ISSUE TITLE
ios-server 0.6.2 depends on libimobiledevice-java 

### ISSUE THREAD

**Issue by krmahadevan** [ios-driver/ios-driver#101]
When adding a dependency to ios-server 0.6.2 I am failing in dependency resolve because this artifact is depending upon 

&lt;groupId&gt;libimobiledevice-java&lt;/groupId&gt;
&lt;artifactId&gt;libimobiledevice-java&lt;/artifactId&gt;
&lt;version&gt;1.0-SNAPSHOT&lt;/version&gt;

and I cant find this artifact anywhere.

http://repo1.maven.org/maven2/org/uiautomation/ios-server/0.6.2/ios-server-0.6.2.pom

**Comment by nicegraham** [comment]
It's not public right now, it will be in the next week or so

**Comment by freynaud** [comment]
fixed.
