### ISSUE TITLE
Setting up iOSDriver

### ISSUE THREAD

**Issue by PavithraNavaneeth** [ios-driver/ios-driver#104]
I am new to iOSDriver.
I want to setup this for web application automation in simulator and ios device. In setup page - its mentioned to get the test application. Is this mandatory step for safari - web automation? I downloaded xcode 4.6.3 and ios-server.jar and ran the command to update the mobilesafari info.plist. What is the next step i should do?

Thanks in Advance!!

**Comment by nicegraham** [comment]
no, to use MobileSafari you don't need to get an application. The process is documented on our wiki: 
http://ios-driver.github.io/ios-driver/safari.html

We don't currently support MobileSafari on real devices though we're working on it [I can't give you a timeline].

**Comment by PavithraNavaneeth** [comment]
Thanks for your reply Graham !!

**Comment by PavithraNavaneeth** [comment]
Graham,
Any update on the support for mobileSafari on real devices? Thanks!!

**Comment by nicegraham** [comment]
No, it's still being worked on - if it's very important to you, please feel free to help the effort. :)
