### ISSUE TITLE
Unsupported major.minor Version 51.0

### ISSUE THREAD

**Issue by PavithraNavaneeth** [ios-driver/ios-driver#108]
When I try to run my script, it is giving below run time error:
java.lang.UnsupportedClassVersionError: org/uiautomation/ios/IOSCapabilities : Unsupported major.minor version 51.0

My Java Version: 1.6
ios-grid version in pom.xml dependency -- 0.6.2

How can I resolve this issue?

**Comment by nicegraham** [comment]
upgrade to Java 1.7
