### ISSUE TITLE
third party files missing from inspector

### ISSUE THREAD

**Issue by darraghgrace** [ios-driver/ios-driver#110]
Third party files missing from - https://github.com/ios-driver/ios-driver/tree/dev/server/src/main/resources/inspector/thrid_party

When trying to inspect getting exceptions like these

54:57:119 WARNING IDEServlet.doGet  error getting resource /resources/inspector/thrid_party/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.jsnull
54:57:121 WARNING IDEServlet.doGet  error getting resource /resources/inspector/thrid_party/jquery-ui-1.10.3.custom/css/smoothness/jquery-ui-1.10.3.custom.min.cssnull

Looks like 'jquery-ui-1.10.3.custom' folder and files are missing

p.s. thrid_party is spelled incorrectly :)

**Comment by freynaud** [comment]
2beea17e8906f2449df623074693f7af5c31d275 should fix it.
