### ISSUE TITLE
WARNING IOSSimulatorManager.restoreExiledSDKs

### ISSUE THREAD

**Issue by jayanthvijayakumar** [ios-driver/ios-driver#114]
The below warning is displaying for every run of the sample ios driver scripts on InternationalMountains app through eclipse

WARNING IOSSimulatorManager.restoreExiledSDKs  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/exiledSDKs doesn't exist.Cannot move folders from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/exiledSDKs Make sure the rights are correct (chmod -R +rw ... )

Note:
Scripts are running only when the iphone simulator is closed, the script will launch the simulator 
Otherwise,  When the simulator is active with the InternationalMountains app installed the below error message displayed in the eclipse console

Eclipse Console
Exception in thread "main" org.openqa.selenium.WebDriverException: execution failed. Exit code =1 , command was : [killall, iPhone Simulator]
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.7.0_25'
Driver info: driver.version: unknown
Command duration or timeout: 62.71 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.7.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver...

Terminal - iOS Server
cannot delete /Users/lion3/Library/Application Support/iPhone Simulator/6.1/Library
cannot delete content and settings folder /Users/lion3/Library/Application Support/iPhone Simulator/6.1
couldn't re-create/Users/lion3/Library/Application Support/iPhone Simulator/6.1

Please advice me on this,
1. How to remove the warning
2. Can we run the scripts only by closing the simulator by default

Thanks,
Jayanth Vijayakumar

**Comment by nicegraham** [comment]
The error tells you what to do:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/exiledSDKs doesn't exist.Cannot move folders from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/exiledSDKs Make sure the rights are correct (chmod -R +rw ... )

i.e. create the exiledSDKs folder in that location and make sure is has read write for all.

**Comment by jayanthvijayakumar** [comment]
Graham,

mkdir: exiledSDKs: Permission denied

while creating the directory.

**Comment by nicegraham** [comment]
Ok, use sudo mkdir

**Comment by jayanthvijayakumar** [comment]
Thanks graham., its working now :)
