### ISSUE TITLE
Error starting instrument for session ####, Instruments crashed

### ISSUE THREAD

**Issue by jayanthvijayakumar** [ios-driver/ios-driver#118]
For my native application, the ios driver has been started and while running the test, it launches the ipad simulator but failed to run the scripts and closed automatically. Instead the error message is displayed in the eclipse console

Eclipse console:
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: error starting instrument for session 1c4e6e85-c446-4c6f-8e2c-cd5a57bfa9ea, Instruments crashed.

Terminal:
05:44:214 INFO APPIOSApplication.canRun  The application doesn't have any content files.The localization related features won't be availabled.

**Comment by nicegraham** [comment]
was the application compiled using the same version of xcode that you're running instruments from?

**Comment by jayanthvijayakumar** [comment]
Instruments version 4.6
Xcode version 4.6.2

I am not running the instruments,
Just started the iOS driver by the below command

java -jar ios-server-0.6.0.jar -aut /Users/lion3/Library/Developer/Xcode/DerivedData/Myapp/Build/Products/Debug-iphonesimulator/myapp.app -port 4444

Then launching my app through iOS driver

**Comment by sachin185** [comment]
i am also having this same trouble while automating an ios application. Anyone can help?? please.
Is there anything we have to do in the ipa folder to succesfully automate app file

**Comment by lunasummer** [comment]
Any Solve?

**Comment by mach6** [comment]
This issue needs additional details and is related to an older/early version (0.6.0) of ios-driver. 

Closing it. Please re-open if it applies to a more recent revision of ios-driver and you can also provide the additional details including ios-driver version, xcode version, stack trace, etc.
