### ISSUE TITLE
Enhancement: Do we able to run the scripts on Safari Browser first and then in Native/Hybrid app on a test suite

### ISSUE THREAD

**Issue by jayanthvijayakumar** [ios-driver/ios-driver#120]
Do we able to run the scripts on Safari Browser first and then in Native/Hybrid app on a single test.

I am having an app in which scripts has to be executed on a browser - first test , then continue the scripts on the app - second test

Is this possible in iOS driver.

Please advice me on this.

**Comment by freynaud** [comment]
yes, but that's 2 different drivers.A single driver cannot switch from one ap to the other.
