### ISSUE TITLE
Impact of the move to Xcode 5

### ISSUE THREAD

**Issue by xuyuansi** [ios-driver/ios-driver#121]
Folks, 

Hope this is the right place to ask this: 

"Will iOS-driver be impacted by the move to Xcode 5 in the coming months?  Xcode 5 is still a developer preview, but it will go GM before iOS 7 is released."

Thanks, 

Xuyuan

**Comment by freynaud** [comment]
Hello,
yes, it will be impacted as we're using instruments, and that is updated together with xcode.

current status of the work :
- ios7 works for native apps. Switching back to older SDK ( ios5.1 -> IOS 6.1) after switching to the new xcode is still flaky.
- mobile safari doesn't work yet.
  thanks,
  françois

**Comment by julianhaslinger** [comment]
Is there an estimated timeframe for the release of the ios7 mobile safari compatible version of the ios driver?

**Comment by freynaud** [comment]
safari is working fine on the dev branch. We're working on fixing the last broken tests but it should already be useable.
François

**Comment by freynaud** [comment]
you can try https://dl.dropboxusercontent.com/u/24687868/ios-beta/ios-server-0.6.6-SNAPSHOT-jar-with-dependencies.jar
