### ISSUE TITLE
How to execute Web-app Test scripts on iPhone real device? 

### ISSUE THREAD

**Issue by giteshgarg** [ios-driver/ios-driver#130]
we are able to execute script in simulators but failed in real device.....
can you please provide us some info on real devices..  

Thanks in Advance 
Gitesh Garg

**Comment by nicegraham** [comment]
There are details on the wiki here: http://ios-driver.github.io/ios-driver/setup.html#real

What version of ios-driver are you using, real device support is broken in the current builds. So you should be using 0.6.0 if possible.

**Comment by freynaud** [comment]
there is a technical solution, but we're still waiting to sort out the license implication.

**Comment by giteshgarg** [comment]
@nicegraham I am using 0.6.0 ..still not working

**Comment by LimeDang** [comment]
@freynaud, I am really need real device support to execute test for safari, as I know currently ios driver can not take control safari on real device, may you help me on this?

**Comment by rgustavsson** [comment]
@freynaud @nicegraham 

Can you confirm if mobile safari is available from a real device? 
Since there is no way to "archive" it, and my "/wd/hub/capabilities/all" page says "com.apple.mobilesafari on iphone(Simulator)" only, I guess it isn't supported?

**Comment by nicegraham** [comment]
@rgustavsson no - only on simulators
