### ISSUE TITLE
ios-server exception

### ISSUE THREAD

**Issue by rgustavsson** [ios-driver/ios-driver#136]
Hi!

I want to run my test within the safari browser only, i.e. not in a native application.

Please note that I dont have any issues to run tests in safari if I start the simulator through xcode (xcode --> Product --> Profile --> Instruments --> Automation). 
The "InternationalMountains" app will be launched and if I run my test from a remote machine, pointing at http://IP:5555/wd/hub/, all goes well. Safari browser opens and the test runs perfectly.

But when I start the ios server through the command below (xcode & instruments are not running) I get an error:

java -jar ios-server-0.6.0.jar -port 5555
20:43:092 INFO ApplicationStore.<init>  App archive folder:/Users/richard/Downloads/applications
20:45:078 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Inspector: http://0.0.0.0:5555/inspector/
tests can access the server at http://0.0.0.0:5555/wd/hub
server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/richard/Downloads/applications' for new applications
using xcode install : /Applications/Xcode.app
using IOS version 6.1
Archived apps /Users/richard/Downloads/applications
ios >= 6.0. Safari and hybrid apps are supported.
## Applications:

```
CFBundleName=Safari,CFBundleVersion=8536.25
```

2013-09-02 16:20:45.079:INFO::jetty-7.x.y-SNAPSHOT
2013-09-02 16:20:45.273:INFO::Started SelectChannelConnector@0.0.0.0:5555

---

23:43:330 WARNING DefaultCommandListener.stderr  2013-09-02 16:23:43.327 ScriptAgent[824:2b07] +[UIAXElement initialize]: UIAutomation never received kAXAccessibilityLoaded.  Waited 20.05 seconds.
23:43:609 WARNING DefaultCommandListener.stderr  2013-09-02 16:23:43.606 ScriptAgent[824:2b07] Unexpected error in -[UIAXElement_0xad943c initialize], /SourceCache/UIAutomation_Sim/UIAutomation-271/Framework/UIAXElement.m line 165, kAXErrorServerNotFound
23:43:610 WARNING DefaultCommandListener.stderr  2013-09-02 16:23:43.608 ScriptAgent[824:2b07] **\* Terminating app due to uncaught exception 'kUIAExeceptionAccessibilityError', reason: 'Unexpected error in -[UIAXElement_0xad943c initialize], /SourceCache/UIAutomation_Sim/UIAutomation-271/Framework/UIAXElement.m line 165, kAXErrorServerNotFound'
23:43:610 WARNING DefaultCommandListener.stderr  **\* First throw call stack:
23:43:611 WARNING DefaultCommandListener.stderr  (0x497012 0x1b80e7e 0x496deb 0xa9055b 0x1b817cf 0x1b88a0d 0x1b7faeb 0x1b7fe22 0x1b920e1 0xaa8605 0xa847 0x5d8d 0x866d 0x2925)
23:43:617 WARNING DefaultCommandListener.stderr  libc++abi.dylib: terminate called throwing an exception
23:44:616 WARNING DefaultCommandListener.stderr  2013-09-02 16:23:44.613 instruments[792:5307] Automation Instrument ran into an exception while trying to run the script.  UIAScriptAgentSignaledException

---

Are you able to see what I'm doing wrong? Am I missing something?

Thanks for your patience.

**Comment by freynaud** [comment]
Are you talking about safari or mobile safari ?
Can you post the code of the test you're trying to execute ?

When using ios-driver, Xcode, the simulator and instruments should not be started already.

**Comment by rgustavsson** [comment]
Hi freynaud and thanks for your reply.

I was talking about the mobile safari.

This is parts of my code. There's a big chain of methods involved and I'd need to send you the entire project for you to get the whole picture. But I'm basically doing this:

capabillities = DesiredCapabilities.iphone();
            capabillities.setCapability("device", "iphone");
            capabillities.setCapability("language", "en");
            capabillities.setCapability("locale", "en_GB");
            capabillities.setCapability("CFBundleName", "Safari");
            capabillities.setCapability("CFBundleVersion", "8536.25");
            capabillities.setCapability("variation", "Regular");
            capabillities.setCapability("simulator", true);

driver = new RemoteWebDriver(gethubUrl(), capabillities);
driver.get(site);

---

I don't get two the "driver.get(site)", the error mentioned in my previous comment is thrown before that.

All of it work when I start the simulator and instruments manually and run the test (the server would listen to port 5555 by default)

I recorded a session for when I run a test, please check it out @ http://screencast.com/t/EjIKskD2qG
Please note that xcode, the simulator and instruments where not launched when starting the test.

Thanks.

**Comment by rgustavsson** [comment]
I tested it some more and the scenario that works is if I start the simulator through xcode - profile - automation.
I'll then start the ios-server through the command line and run the test. Test passed.
Is there someting in particular that I could of missed when it comes to UIAutomation?

**Comment by rgustavsson** [comment]
I have tried this some more and it seems that the test actually runs through the first time I run it, but after that I start to get the following message:

18:18:267 WARNING DefaultCommandListener.stderr  2013-09-13 12:18:18.262 ScriptAgent[749:2c07] +[UIAXElement initialize]: UIAutomation never received kAXAccessibilityLoaded.  Waited 20.04 seconds.
18:18:283 WARNING DefaultCommandListener.stderr  2013-09-13 12:18:18.279 ScriptAgent[749:2c07] Unexpected error in -[UIAXElement_0xad943c initialize], /SourceCache/UIAutomation_Sim/UIAutomation-271/Framework/UIAXElement.m line 165, kAXErrorServerNotFound
18:18:285 WARNING DefaultCommandListener.stderr  2013-09-13 12:18:18.283 ScriptAgent[749:2c07] **\* Terminating app due to uncaught exception 'kUIAExeceptionAccessibilityError', reason: 'Unexpected error in -[UIAXElement_0xad943c initialize], /SourceCache/UIAutomation_Sim/UIAutomation-271/Framework/UIAXElement.m line 165, kAXErrorServerNotFound'
18:18:286 WARNING DefaultCommandListener.stderr  **\* First throw call stack:
18:18:286 WARNING DefaultCommandListener.stderr  (0x497012 0x1b80e7e 0x496deb 0xa9055b 0x1b817cf 0x1b88a0d 0x1b7faeb 0x1b7fe22 0x1b920e1 0xaa8605 0xa847 0x5d8d 0x866d 0x2925)
18:18:287 WARNING DefaultCommandListener.stderr  libc++abi.dylib: terminate called throwing an exception
18:21:233 WARNING DefaultCommandListener.stderr  2013-09-13 12:18:21.228 instruments[719:5407] Automation Instrument ran into an exception while trying to run the script.  UIAScriptAgentSignaledException

**Comment by rgustavsson** [comment]
Im getting the same execption as this guy:
http://stackoverflow.com/questions/15031758/error-running-ui-automation-from-command-line

Even though I'm doing something else, I wish that I also could test with xcode 4.5.2, but I can't find the application for download.

**Comment by rgustavsson** [comment]
@freynaud xcode 4.6.3 should work fine, right?

The issue seems to be in instruments, any known issue in this area?

**Comment by rgustavsson** [comment]
Got it working now :)
I did the same as this guy, https://github.com/ios-driver/ios-driver/issues/67.
