### ISSUE TITLE
Receiving Exception in thread "main" java.lang.UnsupportedClassVersionError: org/uiautomation/ios/IOSCapabilities : Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by mlmathisumes** [ios-driver/ios-driver#144]
Receiving this exception message. I ran the driver using "java -jar ios-server-0.6.3.jar -port 4444". And excuted the following code:

public class SimulatorTest {
      public static void main(String[] args) throws Exception {
            DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
            RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), safari);

```
        driver.get("http://www.ebay.co.uk/");

        System.out.println(driver.getTitle());
        driver.quit();
    }
```

}

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/uiautomation/ios/IOSCapabilities : Unsupported major.minor version 51.0

 "build": {
      "revision": "7867b6d426bf20b51d7dabad8328bee3fa3bc6e3",
      "time": "20130828-1934",
      "version": "0.6.3"
    },
    "ios": {"simulatorVersion": "6.1"},
    "java": {"version": "1.7.0_25"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.8.4"

![screen shot 2013-09-10 at 10 41 16 pm](https://f.cloud.github.com/assets/5432094/1119958/b5c78fea-1a8b-11e3-9864-f3388ae26d5c.png)

**Comment by nicegraham** [comment]
The only time I've seen that error is if you're running the wrong version of Java - it needs to be 1.7. Your json message is saying that it's 1.7 but can you confirm that's what's actually running ios-driver?

**Comment by mlmathisumes** [comment]
thanks. I updated the execution environment to java 1.7 in the properties

**Comment by drkibitz** [comment]
Seems a little weird that this is Mac specific functionality which requires a java version that doesn't come by default on Mac? Also couldn't find this noted anywhere until I found this issue.
