### ISSUE TITLE
How to Scroll on Safari on simulator

### ISSUE THREAD

**Issue by saikrishna321** [ios-driver/ios-driver#145]
I have a web page which needs to be scrolled down to a particular element and capture a screenshot . 

How do i scroll to that respective element  ??

I tried giving the xpath of the element understanding that it would move the screen , but it doesnt 

How to work with this ?

**Comment by federicoviscomi** [comment]
```
 public static void scrollToAnElement(WebDriver webDriver, By xpath) {
    WebElement webElement = webDriver.findElement(xpath);
    JavascriptExecutor javascriptExecutor = (JavascriptExecutor) webDriver;
    javascriptExecutor.executeScript("window.scrollTo" + webElement.getLocation());
  }
```

**Comment by QuantumGeordie** [comment]
really? window.scrollTo(0,document.body.scrollHeight) does not seem to work for me. works fine in chrome and firefox, but not mobile safari on iOS 7.1. am i doing something wrong?
