### ISSUE TITLE
How to solve “[xslt] Can not find matching 1-argument function ” exception?

### ISSUE THREAD

**Issue by swamic** [ios-driver/ios-driver#151]
When i am including ios-server-0.6.0.jar in build path (selenium-server-standalone is also present in the build path) my webdriver script is not working.Build is Failing.
But when i remove ios-server-0.6.0.jar , build is successful.

**Comment by bijoyv** [comment]
can you please post entire build failing console output

**Comment by mach6** [comment]
please re-open this when you post you console output
