### ISSUE TITLE
Possible to run test on real device using safari browser?

### ISSUE THREAD

**Issue by rgustavsson** [ios-driver/ios-driver#155]
Hi!

It would be really great if you could answer the following question and perhaps add that peice of information to your website.

Is it possible to run tests on a real device using the safari browser? 
Or is it only possible to test hybrid apps on a real device?

Thanks in advance.

**Comment by nicegraham** [comment]
no, it's not possible. You can only test safari on simulators right now.

**Comment by rgustavsson** [comment]
Thanks for the rapid feedback @nicegraham
