### ISSUE TITLE
ios-driver not able to start ios7 Simulator

### ISSUE THREAD

**Issue by SurenMohanathas** [ios-driver/ios-driver#158]
Environment:
Xcode5,java1.7,MacOS10.8.5,ios-driver0.6.4

I have Xcode5 installed with iOS6 and iOS7 Simulators.  I am trying to open a page on the mobileSafari.  Below is the output from the ios-driver console.

java -jar ios-server-0.6.4-jar-with-dependencies.jar -simulators -port 4444
58:56:996 INFO ApplicationStore.<init>  App archive folder:/Users/smohanat/selenium-node-iOS/applications
58:57:483 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
58:57:761 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
58:57:784 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
58:58:261 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
58:58:532 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
58:58:545 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
58:58:562 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:4444/inspector/
tests can access the server at http://0.0.0.0:4444/wd/hub
server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/smohanat/selenium-node-iOS/applications' for new applications
Archived apps /Users/smohanat/selenium-node-iOS/applications
using xcode install : /Applications/Xcode.app
using IOS version 7.0
ios >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=Safari,CFBundleVersion=8536.25
CFBundleName=Safari,CFBundleVersion=9537.53
```

2013-09-25 16:58:58.562:INFO::jetty-7.x.y-SNAPSHOT
2013-09-25 16:58:58.654:INFO::Started SelectChannelConnector@0.0.0.0:4444
59:12:588 WARNING DefaultCommandListener.stderr  2013-09-25 16:59:12.586 instruments[10637:707] -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff74ff8500
59:12:590 WARNING DefaultCommandListener.stderr  2013-09-25 16:59:12.589 instruments[10637:707] Exception during preparation: -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff74ff8500
59:12:618 WARNING DefaultCommandListener.stderr  2013-09-25 16:59:12.618 instruments[10637:707] **\* Assertion failure in -[UIAInstrument _startAgentForApp:withPID:], /SourceCache/AutomationInstrument/AutomationInstrument-185/Classes/UIAInstrument-Simulator.m:116
59:12:618 WARNING DefaultCommandListener.stderr  2013-09-25 16:59:12.618 instruments[10637:707] Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException

My Java code:
public class iPhoneTester {

```
public static void main(String[] args) throws Exception {
    DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
    safari.setCapability(IOSCapabilities.SIMULATOR, true);
    RemoteWebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444/wd/hub"), safari);

    Thread.sleep(10000);        
    driver.get("http://www.google.com");

    System.out.println(driver.getTitle());
    driver.quit();
}
```

}

**Comment by SurenMohanathas** [comment]
Can someone please help. Thx.

**Comment by jasone** [comment]
The instruments crash is due to ios-driver corrupting Info.plist (converting it to JSON format).  This is fixed in https://github.com/ios-driver/ios-driver/commit/144e1fa0d3a7154d3c738ef37c82cfc5ee9d3821 .  In my tests, ios-driver still isn't quite working with XCode 5, but it's a lot closer.

**Comment by nicegraham** [comment]
@jasone have you looked at the refactor branch? that's where @freynaud has been doing the ios7 integration work

**Comment by jasone** [comment]
I hadn't noticed that branch, @nicegraham.  Thanks for the heads up.

**Comment by rsalvador** [comment]
Is ios-driver able to use iOS 7 already?. I tried both the "dev" and "refactor" branches and I still get the same instruments crash that was reported in this issue.

**Comment by rsalvador** [comment]
The reason I was still getting the instruments crash with the latest source is that there was corrupted Info.plist in ~/.ios-driver/safariCopies from previous runs. Deleting the old safariCopies gets pass the instruments crash.
