### ISSUE TITLE
Issue in ios-driver for iOS 7 simulator

### ISSUE THREAD

**Issue by praveshkumar09** [ios-driver/ios-driver#163]
Hi,

Have anybody used iWebdriver for iOS 7 simulator(iPhone retina 3.5 inch)?
We are facing issues in using the same.

after doing this......we are getting below logs on terminal:
java -jar ios-server-xxx.jar -aut ~/Documents/build/myapp.app -port
    4444
Pravesh_Kumar$ java -jar ~/Desktop/ACM/ios-server-0.6.5-jar-with-dependencies.jar -aut ~/Desktop/ACM/ACMInternalTest1.app -port 4444
55:32:818 INFO ApplicationStore.<init>  App archive folder:/Users/pravesh_kumar/Desktop/ACM/applications
55:32:868 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): false
Inspector: http://0.0.0.0:4444/inspector/
tests can access the server at http://0.0.0.0:4444/wd/hub
server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/pravesh_kumar/Desktop/ACM/applications' for new applications
Archived apps /Users/pravesh_kumar/Desktop/ACM/applications
## Applications :

```
CFBundleName=ACMInternalTest1,CFBundleVersion=2.3.2.0.4
```

2013-10-08 16:55:32.869:INFO::jetty-7.x.y-SNAPSHOT
2013-10-08 16:55:32.969:INFO::Started SelectChannelConnector@0.0.0.0:4444

When we open http://0.0.0.0:4444/wd/hub/status, it says error.....

{
  "class": "org.openqa.selenium.remote.Response",
  "hCode": 1306765021,
  "sessionId": "",
  "state": null,
  "status": 13,
  "value": {
    "class": "org.openqa.selenium.WebDriverException",
    "message": "there was an error.stderr is not empty\nBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'\nSystem info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_40'\nDriver info: driver.version: unknown",
    "screen": null,
    "stackTrace": [
      {
        "className": "org.uiautomation.ios.utils.ShowSDKsPasrer",
        "fileName": "ClassicCommands.java",
        "lineNumber": 154,
        "methodName": "getSDKs"
      },
      {
        "className": "org.uiautomation.ios.utils.ClassicCommands",
        "fileName": "ClassicCommands.java",
        "lineNumber": 115,
        "methodName": "getInstalledSDKs"
      },
      {
        "className": "org.uiautomation.ios.utils.ClassicCommands",
        "fileName": "ClassicCommands.java",
        "lineNumber": 120,
        "methodName": "getDefaultSDK"
      },
      {
        "className": "org.uiautomation.ios.server.command.uiautomation.ServerStatusNHandler",
        "fileName": "ServerStatusNHandler.java",
        "lineNumber": 58,
        "methodName": "handle"
      },
      {
        "className": "org.uiautomation.ios.server.command.BaseCommandHandler",
        "fileName": "BaseCommandHandler.java",
        "lineNumber": 86,
        "methodName": "handleAndRunDecorators"
      },
      {
        "className": "org.uiautomation.ios.server.servlet.IOSServlet",
        "fileName": "IOSServlet.java",
        "lineNumber": 144,
        "methodName": "getResponse"
      },
      {
        "className": "org.uiautomation.ios.server.servlet.IOSServlet",
        "fileName": "IOSServlet.java",
        "lineNumber": 85,
        "methodName": "process"
      },
      {
        "className": "org.uiautomation.ios.server.servlet.IOSServlet",
        "fileName": "IOSServlet.java",
        "lineNumber": 46,
        "methodName": "doGet"
      },
      {
        "className": "javax.servlet.http.HttpServlet",
        "fileName": "HttpServlet.java",
        "lineNumber": 707,
        "methodName": "service"
      },
      {
        "className": "javax.servlet.http.HttpServlet",
        "fileName": "HttpServlet.java",
        "lineNumber": 820,
        "methodName": "service"
      },
      {
        "className": "org.eclipse.jetty.servlet.ServletHolder",
        "fileName": "ServletHolder.java",
        "lineNumber": 533,
        "methodName": "handle"
      },
      {
        "className": "org.eclipse.jetty.servlet.ServletHandler",
        "fileName": "ServletHandler.java",
        "lineNumber": 475,
        "methodName": "doHandle"
      },
      {
        "className": "org.eclipse.jetty.server.session.SessionHandler",
        "fileName": "SessionHandler.java",
        "lineNumber": 224,
        "methodName": "doHandle"
      },
      {
        "className": "org.eclipse.jetty.server.handler.ContextHandler",
        "fileName": "ContextHandler.java",
        "lineNumber": 920,
        "methodName": "doHandle"
      },
      {
        "className": "org.eclipse.jetty.servlet.ServletHandler",
        "fileName": "ServletHandler.java",
        "lineNumber": 403,
        "methodName": "doScope"
      },
      {
        "className": "org.eclipse.jetty.server.session.SessionHandler",
        "fileName": "SessionHandler.java",
        "lineNumber": 184,
        "methodName": "doScope"
      },
      {
        "className": "org.eclipse.jetty.server.handler.ContextHandler",
        "fileName": "ContextHandler.java",
        "lineNumber": 856,
        "methodName": "doScope"
      },
      {
        "className": "org.eclipse.jetty.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 117,
        "methodName": "handle"
      },
      {
        "className": "org.eclipse.jetty.server.handler.HandlerList",
        "fileName": "HandlerList.java",
        "lineNumber": 47,
        "methodName": "handle"
      },
      {
        "className": "org.eclipse.jetty.server.handler.HandlerWrapper",
        "fileName": "HandlerWrapper.java",
        "lineNumber": 114,
        "methodName": "handle"
      },
      {
        "className": "org.eclipse.jetty.server.Server",
        "fileName": "Server.java",
        "lineNumber": 352,
        "methodName": "handle"
      },
      {
        "className": "org.eclipse.jetty.server.HttpConnection",
        "fileName": "HttpConnection.java",
        "lineNumber": 596,
        "methodName": "handleRequest"
      },
      {
        "className": "org.eclipse.jetty.server.HttpConnection$RequestHandler",
        "fileName": "HttpConnection.java",
        "lineNumber": 1049,
        "methodName": "headerComplete"
      },
      {
        "className": "org.eclipse.jetty.http.HttpParser",
        "fileName": "HttpParser.java",
        "lineNumber": 590,
        "methodName": "parseNext"
      },
      {
        "className": "org.eclipse.jetty.http.HttpParser",
        "fileName": "HttpParser.java",
        "lineNumber": 212,
        "methodName": "parseAvailable"
      },
      {
        "className": "org.eclipse.jetty.server.HttpConnection",
        "fileName": "HttpConnection.java",
        "lineNumber": 426,
        "methodName": "handle"
      },
      {
        "className": "org.eclipse.jetty.io.nio.SelectChannelEndPoint",
        "fileName": "SelectChannelEndPoint.java",
        "lineNumber": 510,
        "methodName": "handle"
      },
      {
        "className": "org.eclipse.jetty.io.nio.SelectChannelEndPoint",
        "fileName": "SelectChannelEndPoint.java",
        "lineNumber": 34,
        "methodName": "access$000"
      },
      {
        "className": "org.eclipse.jetty.io.nio.SelectChannelEndPoint$1",
        "fileName": "SelectChannelEndPoint.java",
        "lineNumber": 40,
        "methodName": "run"
      },
      {
        "className": "org.eclipse.jetty.util.thread.QueuedThreadPool$2",
        "fileName": "QueuedThreadPool.java",
        "lineNumber": 450,
        "methodName": "run"
      },
      {
        "className": "java.lang.Thread",
        "fileName": "Thread.java",
        "lineNumber": 724,
        "methodName": "run"
      }
    ]
  }
}

Help is needed to run the test.....

We have performed all the steps mentioned on http://ios-driver.github.io/ios-driver/setup.html

still running with many issues.

Thanks in advance.

**Comment by duncandee** [comment]
I am having the same issue with xcode5 and ios7. Great product btw

**Comment by nicegraham** [comment]
folks can you try running the code from the refactor branch, it's still a work in progress but it's working well enough for us

**Comment by SurenMohanathas** [comment]
Hi Graham,
Running code from refactor branch, does it mean i need to pull down the src from refactor branch and build it my self?  
thanks
Suren

**Comment by nicegraham** [comment]
yep, just download and run mvn package. The with dependencies jar should be
in ./ios-driver/server/target

**Comment by SurenMohanathas** [comment]
Thanks Graham for the quick response.
Did build the refactor branch and still no luck instrument crashes. Opened a Issue.

**Comment by jasone** [comment]
@surenAKA, were you using Xcode 5.0.1 by chance?  If so, please try again with Xcode 5.0.2; there was a critical regression in Xcode 5.0.1.

**Comment by SurenMohanathas** [comment]
I was using Version 5.0 (5A1413), Will try again with 5.0.2.  Thanks for the help.

**Comment by SurenMohanathas** [comment]
I am having issue wiht 5.0.2 as well,  the issue is "org.openqa.selenium.WebDriverException: iPhone incompatible with SDK 7.0"  can anyone point me to how to set in capabilities to use the retina display.  Thanks.

**Comment by SurenMohanathas** [comment]
Thanks all.  I updated to Xcode 5.0.2 and with some support from the ios-driver foks, i got all working.  below is summary of commands you will need.

sudo chmod 666 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator*.sdk/Applications/MobileSafari.app/Info.plist
java -jar selenium-server-standalone-2.37.0.jar -host 127.0.0.1 -role hub -timeout 30

rm -rf ~/.ios-driver/
sudo chmod -R a+rw /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app
sudo chmod a+rw /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications
java -jar ios-server-0.6.5-jar-with-dependencies.jar -hub http://127.0.0.1:4444/grid/register -host 127.0.0.1 -simulators

DesiredCapabilities safariIphone = IOSCapabilities.iphone("Safari");
safariIphone.setCapability(IOSCapabilities.SIMULATOR, true);
safariIphone.setCapability("variation", "Retina4");
safariIphone.setCapability(IOSCapabilities.LANGUAGE, "en");
safariIphone.setCapability(IOSCapabilities.LOCALE, "en_US");

**Comment by SurenMohanathas** [comment]
what killed me was no documents mentioning that i needed to do "safariIphone.setCapability("variation", "Retina4")" to get ios7 simulator working.

**Comment by rsalvador** [comment]
The latest refactor branch will tell you so in the "org.openqa.selenium.WebDriverException: iPhone incompatible with SDK 7.0" error message.

**Comment by winderdancer** [comment]
Do we still need the refactor branch to allow this to work with ios7 on Mavericks? Is the public 0.6.5 enough?

**Comment by nicegraham** [comment]
@winderdancer the refactor or dev branches work.

**Comment by greg-dennis** [comment]
what's the log on the ios driver side?
