### ISSUE TITLE
Not able to connect with selenium grid with the new version

### ISSUE THREAD

**Issue by sazanow** [ios-driver/ios-driver#167]
The connection success with the version 0.6.1 but not with 0.6.4 and 0.6.5.

logFile:

31:45:642 INFO ApplicationStore.<init>  App archive folder:/Users/xxxx/Desktop/iosDriver/applications
31:46:499 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:46:957 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:46:978 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:47:008 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:5555/inspector/
tests can access the server at http://0.0.0.0:5555/wd/hub
server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/risingtob/Desktop/iosDriver/applications' for new applications
Archived apps /Users/risingtob/Desktop/iosDriver/applications
using xcode install : /Applications/Xcode.app
using IOS version 6.0
ios >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=Safari,CFBundleVersion=8536.25
```

31:53:641 WARNING IOSServlet.getResponse  965ms.    GET  /status
31:59:558 WARNING IOSServlet.getResponse  879ms.    GET  /status

buildPart: 

"build": {
      "revision": "c5a477fb76d549b7559d9adaaa6fbf957060eefa",
      "time": "20130726-1752",
      "version": "0.6.1"
    },
    "ios": {"simulatorVersion": "6.0"},
    "java": {"version": "1.7.0_40"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.7.5"
    },

**Comment by nicegraham** [comment]
what version of grid are you using?

**Comment by sazanow** [comment]
version: 2.35.0
/var/lib/jenkins/.jenkins/plugins/selenium/WEB-INF/lib/selenium-server-standalone-2.35.0.jar

**Comment by nicegraham** [comment]
well that combination is working for us [2.35.0-2.37.1 & 0.6.5] - what error are you seeing?

**Comment by sazanow** [comment]
output in Terminal: 

java -jar ios-server-0.6.5-jar-with-dependencies.jar -hub http://dcp-ciplayer:4444/grid/register -proxy org.openqa.grid.selenium.proxy.DefaultRemoteProxy -host 172.23.104.253 -port 5555 -simulators
36:23:780 INFO ApplicationStore.<init>  App archive folder:/Users/risingtob/Desktop/iosDriver/applications
36:24:610 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
36:25:087 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
36:25:108 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
36:25:138 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:5555/inspector/
tests can access the server at http://0.0.0.0:5555/wd/hub
server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/risingtob/Desktop/iosDriver/applications' for new applications
Archived apps /Users/risingtob/Desktop/iosDriver/applications
using xcode install : /Applications/Xcode.app
using IOS version 6.0
ios >= 6.0. Safari and hybrid apps are supported.

## Applications :

```
CFBundleName=Safari,CFBundleVersion=8536.25
```

2013-10-25 11:36:25.577:INFO::jetty-7.x.y-SNAPSHOT
2013-10-25 11:36:25.786:INFO::Started SelectChannelConnector@0.0.0.0:5555
36:32:183 WARNING IOSServlet.getResponse  1021ms.   GET  /status
36:38:107 WARNING IOSServlet.getResponse  866ms.    GET  /status

output in grid:

Okt 25, 2013 11:36:25 AM org.openqa.grid.internal.Registry removeIfPresent
WARNING: Proxy 'host :http://172.23.104.253:5555 time out : 300000' was previously registered.  Cleaning up any stale test sessions.
Okt 25, 2013 11:36:38 AM org.openqa.grid.selenium.proxy.DefaultRemoteProxy onEvent
WARNING: Marking the node as down. Cannot reach the node for 2 tries.
Okt 25, 2013 11:37:18 AM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request: The target server failed to respond
Okt 25, 2013 11:37:18 AM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: Retrying request
Okt 25, 2013 11:37:18 AM org.openqa.grid.selenium.proxy.DefaultRemoteProxy isAlive
WARNING: Failed to check status of node: Connection to http://172.23.104.253:5555 refused

**Comment by nicegraham** [comment]
has your networks environment changed? new firewall or something? that looks like a connectivity issue.

**Comment by sazanow** [comment]
it works with the new version selenium-server-standalone-2.37.0.jar
think can be closed

**Comment by nicegraham** [comment]
cool :)
