### ISSUE TITLE
Real Device Support

### ISSUE THREAD

**Issue by operatiay** [ios-driver/ios-driver#168]
Hello,

as far as I know real devices are not supported any more since there are licensing problems with the libimobile library.

So here are the questions:
1. Is the support for real devices going to be established again in the next future?
2. What needs to be done in order to license the library in order to use real devices for tests for a single solution (we're considering acquiring the license)?

**Comment by LimeDang** [comment]
Can we consider remove those commercial licence libraries? to continue to support ios real device.

**Comment by operatiay** [comment]
My only concern is real device support. Should the project decide to use something different, I'd want to know when it's going to happen. We really need real device support (there are apps which can't be executed on simulator).

**Comment by basavaraj1985** [comment]
I am trying to run my web-automation (browser) on real device - iPhone 5. To enable automation run, i have to start the server with -beta option, as it says on setup page. But when I start the server with -beta I get an exception and server exits.

Here is the error I get:

basavar$ java -jar ios-server-0.6.5-jar-with-dependencies.jar -port 4444 -beta
Cannot load libimobiledevice-sdk.dylib
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.uiautomation.ios.server.IOSServerManager.<init>(IOSServerManager.java:57)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:112)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:83)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:62)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:66)
Caused by: java.lang.NullPointerException
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
    at org.libimobiledevice.ios.driver.binding.IMobileDeviceFactory.unpack(IMobileDeviceFactory.java:73)
    at org.libimobiledevice.ios.driver.binding.IMobileDeviceFactory.<clinit>(IMobileDeviceFactory.java:42)
    ... 5 more

My environment details:
Mac OS X, 10.7.5

Does this mean that there is nil support for real device automation run as of now? Or am I missing any configuration/settings?

**Comment by operatiay** [comment]
Could please one of developers reply to this?

**Comment by tlytvyn** [comment]
I have the same problem, how to resolve it ????

**Comment by nicegraham** [comment]
@freynaud can comment further but right now we won't be able to package the libimobile libraries with the project. You may be able to licence that seperately and ios-driver should work with it.

**Comment by lindachennice** [comment]
@nicegraham ,how can I do the licence libimobile libraries seperately and maknkse ios-driver work? Please advise. thanks

**Comment by nicegraham** [comment]
You should contact the owners of the project http://www.libimobiledevice.org/

**Comment by operatiay** [comment]
Is there a way we could get some hints from the owner in here? Unfortunately there was no answer to my emails sent about 2 weeks ago... But it also might be due to the holidays.

**Comment by nicegraham** [comment]
maybe @funkym can comment

**Comment by gitnava** [comment]
Any update on this subject?

Thank you :)

**Comment by freynaud** [comment]
real device are nearly working now for native and safari. 
A couple of cleanup and it will be released. I'll update that ticket when it happens.

**Comment by KaustavSaikia** [comment]
any update on the real device support @freynaud ?

Thanks 
:+1:

**Comment by freynaud** [comment]
I am working on it this week. I'll give an update next week

**Comment by operatiay** [comment]
@freynaud: Sorry to bother you again, Francois. Can you share with us an update on the roadmap?

**Comment by freynaud** [comment]
Hi,

most of the real device stuff is working now, the missing bit are the documentation and throwing correct exceptions when something goes wrong, especially in the setup phase.
The good error messages + starting safari automatically where mostly finished last week. There is no tech. block any more. I'm now working on integrating that new code ( that comes from libimobiledevice.org ) .

François

**Comment by operatiay** [comment]
@freynaud: Thank you for the update. Does it mean that if I take the 'real' branch it should already work? (or you suggest I'd rather not use it until it's been merged into the main? )

**Comment by freynaud** [comment]
dev should work, but there are some assumption regarding the setup that are
hard to guess. It really needs doc before being usable.

**Comment by operatiay** [comment]
I've actually managed to do the initial setup.

For anyone who wants to do the same here's what I've done:
- Native support seems to rely on .ipa archive rather than on architecture ( @freynaud: would it make sense from your point of view to extract the supported chip architecture from the app and split between simulator and real device based on that?)

here's what I've done to build the ipa:
1. create folder 'Payload'
2. copy the app build for real device into the created folder
   1. find the place where Xcode is storing compiled apps (start Xcode, in menu: Xcode --> Preferences... --> Locations --> Derived Data). In my case it was `/Users/my.name/Library/Developer/Xcode/DerivedData`
   2. build the app for a real device. As a result you should find a folder like `[XcodeProjectName]-somegeneratedhash` within the previously identified DerivedData folder
   3. find your real device version under (I'm using the debug version): `[path_to_the_folder_from_1.1.2.2]/Build/Products/Debug-iphoneos/[appName].app`
3. zip the folder from 1.1.1 (Payload) and store the result under .ipa:`tar -zcvf [yourName].ipa ./Payload`
- Now about the way to start the server. Here's my code to start the server from the test:

``` java
String[] args = { "-port", "4444", "-host", "localhost", "-aut", "/Users/my.name/apps/my.ipa", "-beta", "-sessionTimeout", "600", };
IOSServerConfiguration config = IOSServerConfiguration.create(args);
IOSServer server = new IOSServer(config);
server.start();
```

The code to obtain the driver looks like this:

``` java
String yourBundleName = "something";
IOSCapabilities cap = new IOSCapabilities();
cap.setCapability(IOSCapabilities.DEVICE, DeviceType.iphone);
cap.setCapability(IOSCapabilities.SIMULATOR, false);
cap.setCapability(IOSCapabilities.INSTRUMENTS, false);
cap.setCapability(IOSCapabilities.BUNDLE_NAME, yourBundleName);

driver = new RemoteIOSDriver(getRemoteURL(), cap);
```

Of course, this would only work if there is actually a real device connected to the machine.

**Comment by operatiay** [comment]
my current problem is though that I can't use the keyboard.
I am able to find an item on the screen via `driver.findElement(By.className("UIATextField"))` and can even `.click()` on it.
Then the keyboard is being displayed. After that I am not able to use the console to inspect the elements or send keystroke events for the selected element (using `.sendKeys()`).

@freynaud: is this a known issue/work in progress? Am I missing something in the configuration/setup?

**Comment by operatiay** [comment]
Managed to automate on real device with the prerelease version 0.6.6 from branch newSDK
