### ISSUE TITLE
libimobile-java module seems missing

### ISSUE THREAD

**Issue by xuyuansi** [ios-driver/ios-driver#17]
@freynaud 

In the highest level of pom.xml in the iOS driver 0.6.0 source code, there are six modules: 

```
<modules>
    <module>common</module>
    <module>client</module>
    <module>libimobile-java</module>   <!--Seems missing-->
    <module>server</module> 
    <module>ios-selenium-tests</module>
    <module>grid</module>
</modules>
```

But I cannot find libimobile-java. Just curious that where to find this module please? Currently I added ios-server-0.6.0.jar as a library of the project as a work around. 

Thanks, 

Xuyuan

**Comment by lukeis** [comment]
it's a git submodule

after cloning the main repo:
cd ios-driver
git submodule init
git submodule update

**Comment by rugh** [comment]
It would be great to have this information in the FAQ at least.

Thanks in advance.

**Comment by xuyuansi** [comment]
Currently in .gitmodules the url is like: git@github.com:ios-driver/libimobile-java.git 
I tried to follow the instruction above but it requires the public key, which I think is for the developers. 
I also tred to replace the current url to https://github.com/ios-driver/libimobile-java.git, which works.
