### ISSUE TITLE
Not able to select "Go" key

### ISSUE THREAD

**Issue by sankarharidasmenon29** [ios-driver/ios-driver#170]
Hi,

No option to click "Go" key in iOS simulator's keyboard.

os.name: Mac OS X
os.arch: 'x86_64'
os.version: '10.7.5'
java.version: '1.7.0_45'
Xcode: 4.6

Thanks,
Sankar

**Comment by pshakya** [comment]
element = driver.findElement(By.xpath("//*[@name='Go']"));
element.click();
