### ISSUE TITLE
IOS-driver crashes while taking screenshot in landscape mode

### ISSUE THREAD

**Issue by mdiwakar** [ios-driver/ios-driver#171]
ios-driver version: 0.6.5
IOS 6.1 simulator
Java 1.7

//create DesiredCapability

 if ("ipad".equals(browserName)) {
                  desiredCapabilities = IOSCapabilities.ipad("Safari");
        } else ("iphone".equals(browserName)) {
                  desiredCapabilities = IOSCapabilities.iphone("Safari");
}

//Instantiate driver
WebDriver webDriver = new RemoteWebDriver(httpCommandExecutor, desiredCapabilities);

//rotate device landscape
    public void rotateDeviceLandscape() {
        ((Rotatable) webDriver).rotate(ScreenOrientation.LANDSCAPE);
    }

// take screen shot

TakesScreenshot takesScreenshot = ((TakesScreenshot)(webDriver));
byte[] png = takesScreenshot.getScreenshotAs(OutputType.BYTES);

**Comment by mdiwakar** [comment]
following exception is thrown

WebDriverException: Session [ef289748-2e84-40f2-8d42-c48e2cde276f] was terminated due to FORWARDING_TO_NODE_FAILED Command duration or timeout: 19 milliseconds Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_45' Session ID: ef289748-2e84-40f2-8d42-c48e2cde276f Driver info: org.openqa.selenium.remote.RemoteWebDriver Capabilities [{javascriptEnabled=true, browserVersion=8536.25, browserName=Safari, variation=Regular, locale=en_GB, systemName=iPhone OS, supportedLocales=[hr, ro, ca, vi, tr, fr, unknown, hu, unknown, th, id, pt-PT, en-GB, fi, unknown, sv, it, sk, ja, uk, es, da, ms, ko, ar, he, en, nl, cs, el, pl, pt, ru, de], takesElementScreenshot=false, version=6.0, sdkVersion=6.1, aut=/Users/hudson/.ios-driver/safariCopies/safari-6.0.app, platformVersion=6.1, elementTree=true, platformName=IOS, name=iPad Simulator, iosSearchContext=true, CFBundleVersion=8536.25, takesScreenshot=true, platform=UNIX, CFBundleIdentifier=com.apple.mobilesafari, simulator=true, rotatable=true, rect={origin={y=0, x=0}, size={height=1024, width=768}}, locationContextEnabled=true, cssSelectors=true, configurable=true, device=ipad, language=en, iosTouchScreen=true}]

**Comment by nicegraham** [comment]
are you running on a VM? if so can you make sure you've installed the latest update from Oracle - 7u45.

**Comment by mdiwakar** [comment]
thanks Graham, yes I was running a on VM and upgrading to 7u45 did help
resolve this issue.
