### ISSUE TITLE
Inspector not showing up the objects when i use ios server 6.5 dependencie. jar

### ISSUE THREAD

**Issue by vishwanath-vodeyar** [ios-driver/ios-driver#173]
I have downloaded the latest ios-server-0.6.5-dependencies.jar file. I'm able to start the server and launch the application from eclipse on MAC. 

I'm unable to inspect the elements of the application. The safari browser is only showing up the ios screen. But when i mouse over the elements its not showing the properties or the locators etc .....

**Comment by freynaud** [comment]
safari inspector is not supported. You can use Safari > Developer  menu to inspect mobile web directly.
