### ISSUE TITLE
Even with "refactor" branch unable to use ios-driver with xcode5

### ISSUE THREAD

**Issue by SurenMohanathas** [ios-driver/ios-driver#174]
51:03:469 INFO ApplicationStore.<init>  App archive folder:/Users/smohanat/selenium-node-iOS/applications
51:04:241 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag ): false
Simulator enabled (enabled by -simulators flag): true
Inspector: http://0.0.0.0:5555/inspector/
Tests can access the server at http://0.0.0.0:5555/wd/hub
Server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/smohanat/selenium-node-iOS/applications' for new applications
Archived apps: /Users/smohanat/selenium-node-iOS/applications
Using Xcode install : /Applications/Xcode.app
Using IOS version 6.0
iOS >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=Safari,CFBundleVersion=8536.25
```

2013-11-13 15:51:04.304:INFO::jetty-7.x.y-SNAPSHOT
2013-11-13 15:51:04.365:INFO::Started SelectChannelConnector@0.0.0.0:5555
51:41:790 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/5.0/51166/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate /var/root/.ios-driver/safariCopies/safari-6.0.app -e UIASCRIPT /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/uiamasterscript2644169104231998344.js -e UIARESULTSPATH /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/a7f93d6d-8fd7-4def-806f-92917285f8922400683972501396481.tmp  2013-11-13 15:51:41.789 instruments[16661:707] -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff72aac4e0
51:41:791 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/5.0/51166/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate /var/root/.ios-driver/safariCopies/safari-6.0.app -e UIASCRIPT /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/uiamasterscript2644169104231998344.js -e UIARESULTSPATH /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/a7f93d6d-8fd7-4def-806f-92917285f8922400683972501396481.tmp  2013-11-13 15:51:41.791 instruments[16661:707] Exception during preparation: -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff72aac4e0
51:41:816 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/5.0/51166/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate /var/root/.ios-driver/safariCopies/safari-6.0.app -e UIASCRIPT /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/uiamasterscript2644169104231998344.js -e UIARESULTSPATH /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/a7f93d6d-8fd7-4def-806f-92917285f8922400683972501396481.tmp  2013-11-13 15:51:41.815 instruments[16661:707] **\* Assertion failure in -[UIAInstrument _startAgentForApp:withPID:], /SourceCache/AutomationInstrument/AutomationInstrument-185/Classes/UIAInstrument-Simulator.m:116
51:41:817 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/5.0/51166/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate /var/root/.ios-driver/safariCopies/safari-6.0.app -e UIASCRIPT /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/uiamasterscript2644169104231998344.js -e UIARESULTSPATH /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/a7f93d6d-8fd7-4def-806f-92917285f8922400683972501396481.tmp  2013-11-13 15:51:41.816 instruments[16661:707] Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException

also tried with xcode 5

05:38:737 INFO ApplicationStore.<init>  App archive folder:/Users/smohanat/selenium-node-iOS/applications
05:40:139 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag ): false
Simulator enabled (enabled by -simulators flag): true
Inspector: http://0.0.0.0:5555/inspector/
Tests can access the server at http://0.0.0.0:5555/wd/hub
Server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/smohanat/selenium-node-iOS/applications' for new applications
Archived apps: /Users/smohanat/selenium-node-iOS/applications
Using Xcode install : /Applications/Xcode.app
Using IOS version 7.0
iOS >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=Safari,CFBundleVersion=8536.25
CFBundleName=Safari,CFBundleVersion=9537.53
```

2013-11-13 16:05:40.195:INFO::jetty-7.x.y-SNAPSHOT
2013-11-13 16:05:40.253:INFO::Started SelectChannelConnector@0.0.0.0:5555
05:42:652 WARNING SimulatorSettings.getSimulateDeviceValue  Non-retina iPhone not supported starting with SDK 7.0; substituting 3.5-inch retina iPhone
05:43:996 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/5.0/51166/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate /var/root/.ios-driver/safariCopies/safari-7.0.app -e UIASCRIPT /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/uiamasterscript7056482864626834144.js -e UIARESULTSPATH /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/447b9c78-5078-4043-ab81-cd7c11a2a3519105683265314665100.tmp  2013-11-13 16:05:43.995 instruments[17961:707] -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff72aac4e0
05:43:997 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/5.0/51166/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate /var/root/.ios-driver/safariCopies/safari-7.0.app -e UIASCRIPT /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/uiamasterscript7056482864626834144.js -e UIARESULTSPATH /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/447b9c78-5078-4043-ab81-cd7c11a2a3519105683265314665100.tmp  2013-11-13 16:05:43.996 instruments[17961:707] Exception during preparation: -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff72aac4e0
05:44:021 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/5.0/51166/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate /var/root/.ios-driver/safariCopies/safari-7.0.app -e UIASCRIPT /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/uiamasterscript7056482864626834144.js -e UIARESULTSPATH /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/447b9c78-5078-4043-ab81-cd7c11a2a3519105683265314665100.tmp  2013-11-13 16:05:44.020 instruments[17961:707] **\* Assertion failure in -[UIAInstrument _startAgentForApp:withPID:], /SourceCache/AutomationInstrument/AutomationInstrument-185/Classes/UIAInstrument-Simulator.m:116
05:44:022 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/5.0/51166/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate /var/root/.ios-driver/safariCopies/safari-7.0.app -e UIASCRIPT /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/uiamasterscript7056482864626834144.js -e UIARESULTSPATH /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/447b9c78-5078-4043-ab81-cd7c11a2a3519105683265314665100.tmp  2013-11-13 16:05:44.021 instruments[17961:707] Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException

same problem.

can anyone please let me know if you were successfully able to get iphone simulator and safariMobile working with the new code base on refactor branch.

**Comment by SurenMohanathas** [comment]
I sued the 'refactor' branch to do the above testing.

**Comment by jasone** [comment]
You have a corrupted Info.plist in your app bundle (text format, but should be binary or XML).  There was a bug in ios-driver that caused this corruption, but if you ran an older version of ios-driver, the corruption may persist until you completely rebuild the app from scratch.  Delete the relevant directory in ~/Library/Developer/Xcode/DerivedData , rebuild, then try again.
