### ISSUE TITLE
Multiple tests error

### ISSUE THREAD

**Issue by CavalornIV** [ios-driver/ios-driver#175]
Hey guys!

I want to run my C# (MBUnit) tests on 2 virtual osx (running on a mac mini) parallel but everytime I start more than one test from my Visual Studio (same problem with jenkins job) the ios simulator opens but after starting safari it stops without typing a url. When I try to run a single test it works perfect.

My environment:
-) Selenium Hub - selenium-server-standalone 2.37 (running on a windows 2012 server) (also tried 2.35 => same problem)
-) C# test (MBUnit) (on my Win7)
-) 2 x Virtual osx 10.8.5
-) ios-server-0.6.5-jar-with-dependencies.jar (also tried 0.6.3 and 0.6.4 with the same problem)

IPhone Driver:
            DesiredCapabilities capabilities = DesiredCapabilities.IPhone();
            capabilities.SetCapability("AcceptSslCertificates", "true");
            capabilities.SetCapability("language", "en");
            IWebDriver driver = new RemoteWebDriver(new Uri(TestSuiteConfiguration.SeleniumHubURL), capabilities);
            ((IJavaScriptExecutor) driver).ExecuteScript("window.location=arguments[0]", TestSuiteConfiguration.SiteUrl);
            driver.SwitchTo().Alert().Accept();

I use the javascript to handle the unknown ssl certificate :)

iOS-server:
java -jar ios-server-0.6.5-jar-with-dependencies.jar -simulators -port 4444 -hub http://Hub:4444/grid/register -host iOS1

Any ideas?

Thanks
Regards
cava

**Comment by CavalornIV** [comment]
Anyone?

**Comment by nicegraham** [comment]
you're test runss are connecting via your grid? can you see the 2 nodes connected to the grid?

**Comment by CavalornIV** [comment]
yep, they are connected. i can see them and if i run only one test it works fine

**Comment by nicegraham** [comment]
does each node have a seperate ip / port? it sounds like it's a hub config issue to be honest and the only thing I can think of is that hub is sending a new session request to ios driver on node a, followed by another new session request on the same node - killing the previous session. Is there anything in the console logs?

**Comment by CavalornIV** [comment]
hmm yeah both have different ips but the same port. But i thought that shouldn't be a problem when they run on 2 different machines?.

As I said: 2 mac osx VM's running on one Mac Mini

Config node 1:
port:4444
servlets:[]
host:null
cleanUpCycle:5000
browserTimeout:0
hubHost:QASeleniumHub
capabilityMatcher:org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout:-1
log:../SeleniumHubDebug2.37.0.log
remoteHost:http://QAWebRegiOS:4444
prioritizer:null
throwOnCapabilityNotPresent:true
nodePolling:5000
proxy:org.openqa.grid.selenium.proxy.DefaultRemoteProxy
maxSession:1
role:hub
hubPort:4444
timeout:300000

Config node 2:
port:4444
servlets:[]
host:null
cleanUpCycle:5000
browserTimeout:0
hubHost:QASeleniumHub
capabilityMatcher:org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout:-1
log:../SeleniumHubDebug2.37.0.log
remoteHost:http://QAWebRegiOS2:4444
prioritizer:null
throwOnCapabilityNotPresent:true
nodePolling:5000
proxy:org.openqa.grid.selenium.proxy.DefaultRemoteProxy
maxSession:1
role:hub
hubPort:4444
timeout:300000

**Comment by nicegraham** [comment]
Can you ping QAWebRegiOS and QAWebRegiOS2 from the jenkins machine to ensure they're resolving to different IPs?

**Comment by CavalornIV** [comment]
yep it works. i can ping both machines

**Comment by CavalornIV** [comment]
i can execute one test without any problems. the problem only occurs if i try to execute more than one test

**Comment by nicegraham** [comment]
but did you make sure when you ping them, they resolve to differnt IP addresses? for a test can you change the port on one?

**Comment by CavalornIV** [comment]
yep they resolve to different ip's.
QAWebRegiOS 192._._.82
QAWebRegiOS2 192._._.100

**Comment by CavalornIV** [comment]
i changed the port of QAWebRegiOS2 to 5555 and it worked for 3 tests!

but after the 3 test the simulator stays open with a blank page and all the other test fail...

**Comment by nicegraham** [comment]
is there anything in the ios-driver console output?

**Comment by CavalornIV** [comment]
WARNING IOSServlet.getResponse 93ms. POST /session/:sessionId/element
WARNING IOSServlet.getResponse 13ms. GET /session/:sessionId/url
WARNING IOSServlet.getResponse 185ms. DELETE /session/:sessionId
WARNING IOSServlet.getResponse 6066ms. GET /status
WARNING IOSServlet.getResponse 91ms. POST /session/:sessionId/element
WARNING IOSServlet.getResponse 10973ms. POST /session
WARNING IOSServlet.getResponse 1189ms. GET /status
WARNING IOSServlet.getResponse 1230ms. GET /status
WARNING IOSServlet.getResponse 1215ms. GET /status
and so on... (always GET /status)

then i tried to kill the emulator:
WARNING IOSServlet.getResponse 1185ms. GET /status
WARNING IOSServlet.getResponse 1149ms. GET /status
WARNING ClassicCommands.psgrep Error waiting for the process and the listener threads to finish.
WARNING Command$2.run Error reading the output of the process :Stream closed
WARNING IOSServlet.getResponse 1423ms. GET /status
WARNING IOSServlet.getResponse 1145ms. GET /status
WARNING IOSServlet.getResponse 1185ms. GET /status
WARNING IOSServlet.getResponse 1179ms. GET /status

it starts the ios simulator again after a while with the following output:
http://i39.tinypic.com/1z4xug6.jpg

**Comment by CavalornIV** [comment]
couldn't copy the text from the ios vm to my windows machine :) so i made a screenshot

**Comment by CavalornIV** [comment]
I think i fixed the problem

In my AssemblyInfo.cs I set the value of DegreeOfParallelism exactly to the number of simulators running

But there's anther problem now:
Does the ios-driver support xpaths?
Cause it can't click my element with this xpath: 
//li[not(@style)]//a[(@data-id='btnSport1') and @data-id!='btnSportTopBets' and @data-id!='btnSport']

**Comment by nicegraham** [comment]
It does support xpath - http://ios-driver.github.io/ios-driver/hybrid.html

If you continue to have problems with this, it's a seperate issue so please raise a new ticket. Closing this one as it's resolved.

**Comment by CavalornIV** [comment]
Sorry i posted the wrong xpath...
edited it

**Comment by nicegraham** [comment]
open a new issue for this please
