### ISSUE TITLE
Using this as library to install ipa onto device

### ISSUE THREAD

**Issue by alexhulbert** [ios-driver/ios-driver#177]
Hi. I was looking for a JNI wrapper for libimobiledevice when I came accross your wrapper (libimobiledevice-wrapper). I'm creating [a project](https://github.com/Triforce1/Icew1nd) that needs to restore ipa files onto unjailbroken devices and I heard that libimobiledevice was the only way to do thisonly way to go. Unfortunately, it seems you have commented out some of the classes/methods I need for my project (mainly org.libimobiledevice.ios.driver.binding.installer). I'm guessing the "IMobileDeviceService" class it references isn't done. I opened [an issue](https://github.com/ios-driver/libimobiledevice-wrapper/issues/10), but it seems like that project has been abandoned and the repo is dead. I thought I was completely screwed until I saw _this_ repo. To be honest, I really have no clue what this does, but some of it looks to be of possible use to me.

 `org.uiautomation.ios.server` and `org.uiautomation.ios.server.application` seem to have all that I need to connect to a device and install a codesigned ipa on it. That being said, here's my question: Can I import part (or all if necessary) of your project into mine as a library/API and use it like that? If so, how would I go about installing ipas onto a device? I know there's a class that represents an ipa file in application package, but how would I use that with a physical device? Thanks in advance for any support you have to offer.

EDIT: I heard that @freynaud would know about this. Could he help me with this?

**Comment by alexhulbert** [comment]
Its been over two weeks. What should I do about this? Is there any way I could get support for this?

**Comment by nicegraham** [comment]
you'll need to talk to the owner of the libimobiledevice library to licence its use for this I believe.

**Comment by alexhulbert** [comment]
I don't have to, libimobiledevice is licensed under LGPL. My program is free and open source, so I dont need to specifically need to contact him.

EDIT: I should probably specify that the problem I''m having is that I need to be able to use _ideviceinstaller_ in java.

**Comment by nirvdrum** [comment]
Our license is ASLv2, which is rather permissive. You should be able to import it into your own project without concern.

**Comment by alexhulbert** [comment]
Yes, but when that is done, how would I use it? I don't know how I would go about using it to install an ipa file onto an iDevice.

**Comment by FunkyM** [comment]
@Triforce1 The ios-driver project is not providing what you are looking for. You can use the [libimobiledevice-wrapper](https://github.com/ios-driver/libimobiledevice-wrapper) for your "app install" requirements and the related native shared library as per LGPL license. Just mind that the wrapper is currently in a "refactoring and WIP" state. As I told you once back already in a different issue tracker, I am wondering why your "Icew1nd" project doesn't use the library directly or as an alternative simply executes the [ideviceinstaller](https://github.com/libimobiledevice/ideviceinstaller) binary with your IPA of choice instead (using exec() from Java).

Asides, as usual in open-source projects, people try to help and response to your inquires as their time permits.

**Comment by lukeis** [comment]
github issues are not intended to be help forums, but you know, actual issues with the product (for its intended use).

Feel free to email the ios-driver forum: https://groups.google.com/forum/#!forum/ios-driver

And as previously noted, this is 'volunteer' open source. No one is obligated to help :)
