### ISSUE TITLE
[MAC OS X] Can't get the driver to start my simulator (SAFARI) (iOS 6.1)(XCODE 5.0.2)

### ISSUE THREAD

**Issue by Skarlso** [ios-driver/ios-driver#178]
Hello guys.

I saw a bunch of problems with the driver not being able to start the simulator for iOS 7.0. 

I'm trying iOS 6.1 right now with latest xCode as of today. I have 666 on plist. I freshly built the stuff with maven although the tests didn't work obviously. But I skipped those. 

And this is the log I'm getting:
## Log:

2013-12-03 08:57:43.689:INFO::jetty-7.x.y-SNAPSHOT
2013-12-03 08:57:44.116:INFO::Started SelectChannelConnector@0.0.0.0:5555
58:18:679 WARNING DefaultCommandListener.stderr  2013-12-03 08:58:18.678 instruments[4227:507] -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff795badb0
58:18:681 WARNING DefaultCommandListener.stderr  2013-12-03 08:58:18.679 instruments[4227:507] Exception during preparation: -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff795badb0
58:18:682 WARNING DefaultCommandListener.stderr  2013-12-03 08:58:18.682 instruments[4227:507] **\* Assertion failure in -[UIAInstrument _startAgentForApp:withPID:], /SourceCache/AutomationInstrument/AutomationInstrument-1000/Classes/UIAInstrument-Simulator.m:116
58:18:683 WARNING DefaultCommandListener.stderr  2013-12-03 08:58:18.682 instruments[4227:507] Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException

---

Now, I saw that it mights be that the plist file is corrupted so I got a new one and tried again, didn't work. I want to try automating the browser. Safari. 

This is the simple test I'm trying:
## Code:

public class TestSafari {
    public static void main(String[] args) throws Exception {
        DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
        safari.setCapability("version", "6.1");
        safari.setCapability("CFBundleName", "Safari");
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://0.0.0.0:5555/wd/hub"), safari);

```
    driver.get("htt://google.co.uk");

    System.out.println(driver.getTitle());
    driver.quit();
}
```

}

---

And this is how I'm running the server:
## Server:

java -jar ios-server-0.6.5-jar-with-dependencies.jar -simulators
57:42:170 INFO ApplicationStore.<init>  App archive folder:/Users/MyUser/Tools/ios-driver/fromgit/ios-driver/server/target/applications
57:43:061 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
57:43:357 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
57:43:370 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
57:43:450 INFO IOSServer.initDriver  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:5555/inspector/
Tests can access the server at http://0.0.0.0:5555/wd/hub
Server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/MyUser/Tools/ios-driver/fromgit/ios-driver/server/target/applications' for new applications
Archived apps: /Users/MyUser/Tools/ios-driver/fromgit/ios-driver/server/target/applications
using xcode install : /Applications/Xcode.app
using IOS version 6.1
ios >= 6.0. Safari and hybrid apps are supported.

Applications :
    CFBundleName=Safari,CFBundleVersion=8536.25

2013-12-03 08:57:43.689:INFO::jetty-7.x.y-SNAPSHOT
2013-12-03 08:57:44.116:INFO::Started SelectChannelConnector@0.0.0.0:5555

---

Any ideas tips suggestions would be VERY well come. I ran out of ideas and I really really need this to work. :)

Cheers,
Gergely.

**Comment by nicegraham** [comment]
you need to compile and run from the refactor branch, it has xcode >5 and ios7 support. You should make sure xcode is 5.0.2 - there were bugs in previous versions. You also may need to recompile and build your application as there was a problem with ios-driver corrupting the plist for ios7.

**Comment by Skarlso** [comment]
Thanks Graham!!

I'll check it out asap!

Cheers,
Gergely.

**Comment by Skarlso** [comment]
Hi Graham!

I'm terribly sorry for getting back to you this late. I was in hospital for a while.... 

So I tried the refactor branch and I've got this as error:

org.openqa.selenium.WebDriverException: iPhone incompatible with SDK 7.0
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.7.0_45'
Driver info: driver.version: IOSDualDriver

No I know there are some issues with 7.0 and I'm trying to get it to run under 6.1 but it doesn't seem to do that. I'm setting it via the code with capabilities and I also tried to just delete the whole iOS 7.0 simulator but then the simulator can't start. Also I tried to set it from the simulator menu in xcode to use 6.1 it seems to work then but I still get this error when I try the ios-driver.

I created the exiledSDKs folder but nothing seems to happen there. Do I need to specify which sdk to exile? 

EDIT:

This is what I'm getting when I'm trying to run the ios-driver with the deleted ios7.0 simulator.

18:59:747 INFO ApplicationStore.<init>  App archive folder:/Users/Camelot/Tools/ios-driver/fromgit_refactor/ios-driver/server/target/applications
19:01:539 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled (enabled by -simulators flag): true
Inspector: http://0.0.0.0:5555/inspector/
Tests can access the server at http://0.0.0.0:5555/wd/hub
Server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/Camelot/Tools/ios-driver/fromgit_refactor/ios-driver/server/target/applications' for new applications
Archived apps: /Users/Camelot/Tools/ios-driver/fromgit_refactor/ios-driver/server/target/applications
Build info: ios-driver 0.6.5 (built:20131217-1015,sha:f556e767821a21284da03c31ea07bba1dafd409d)
Running on: Mac OS X 10.9 (x86_64)
Using java: 1.7.0_45
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.0.1, build: 51168
Using iOS version 6.1
iOS >= 6.0. Safari and hybrid apps are supported.

Applications :
    CFBundleName=Safari,CFBundleVersion=8536.25,/var/root/.ios-driver/safariCopies/safari-6.1.app

2013-12-17 11:19:01.747:INFO::jetty-7.x.y-SNAPSHOT
2013-12-17 11:19:02.096:INFO::Started SelectChannelConnector@0.0.0.0:5555
19:25:891 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /var/root/.ios-driver/safariCopies/MobileSafari-6.1.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/Applications/MobileSafari.app
19:29:145 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000   2013-12-17 11:19:29.143 instruments[19290:507] -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff795bad90
19:29:148 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000   2013-12-17 11:19:29.147 instruments[19290:507] Exception during preparation: -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff795bad90
19:29:182 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000   2013-12-17 11:19:29.182 instruments[19290:507] **\* Assertion failure in -[UIAInstrument _startAgentForApp:withPID:], /SourceCache/AutomationInstrument/AutomationInstrument-1000/Classes/UIAInstrument-Simulator.m:116
19:29:195 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000   2013-12-17 11:19:29.194 instruments[19290:507] Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException

And then I wait and wait and this happens:

xception while trying to run the script.  NSInternalInconsistencyException
java.lang.NullPointerException

Cheers,
Gergely.

**Comment by nicegraham** [comment]
I think one problem here is the device you're specifying - it will need to be a retina type since ios7 doesn't support anything else.

**Comment by Skarlso** [comment]
And how do I do that? 

when I'm trying to select retina ios 6.1 only a blank black simulator appears without anything around it. 

Also now MobileSafari.app is missing even if I'm copying it back from where it copied it to ( why? ) it won't load into the simulator anymore. 

UPDATE:
Ohhh and BTW. I don't have my own application. I'm trying to automate the Safari browser. So I cannot specify which IOS simulator the application should use.

UPDATE2:

This happens when I do get status:

30:11:874 SEVERE IOSServlet.getResponse  GET:/session/null/tree
    body:{"translation":true,"native":true,"attachScreenshot":true}  in 8ms
30:11:881 WARNING IOSServlet.doGet  org.openqa.selenium.WebDriverException: Error processing response.bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.7.0_45'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.7.0_45'
Driver info: driver.version: unknown
java.lang.NullPointerException
    at org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver.logElementTree(RemoteIOSDriver.java:291)
    at org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver.logElementTree(RemoteIOSDriver.java:107)
    at org.uiautomation.ios.inspector.model.IDESessionModelImpl.refresh(IDESessionModelImpl.java:75)
    at org.uiautomation.ios.inspector.controllers.IDEController.handle(IDEController.java:42)
    at org.uiautomation.ios.inspector.IDEServlet.doGet(IDEServlet.java:91)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:744)
30:11:906 WARNING IDEServlet.doGet  null

**Comment by Skarlso** [comment]
Finally after LOTS of digging I've got to the next step.. 

I was able to run the old SDK with specifying it programatically like this:

```
    safari.setCapability("version", "6.1");
    safari.setCapability("sdkVersion", "6.1");
    safari.setCapability("CFBundleName", "Safari");
```

Now my next issue ( because there are always issues ) is that it can't start safari yet for some reason. But at least it finally opens up the simulator.

I _think_ I know why. Because for some reason it copies the Safari.app from the directory ( why the hell is it doing that?? ) and then copies it back but it will have the wrong credentials and accessibility rights.

How I can stop it from doing this?

cheers!

**Comment by jigtest** [comment]
@Skarlso I know its very late but wanted some help as I am stuck at this problem where I am running my code and iPhone simulator opens but the safari browser does not open. So were you able to solve your problem of opening the Safari browser? Could you help me with my problem.

Thanks.
