### ISSUE TITLE
Got an error "Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException"

### ISSUE THREAD

**Issue by tlytvyn** [ios-driver/ios-driver#179]
I am using ios-driver 0.6.5, latest Xcode version and my Mac OS version is 10.8.5
Tried to change the app sdk and tried different Emulators, but after running the 
java -jar ios-server-0.6.5-jar-with-dependencies.jar -app TicketMonster.app -port 4444 -simulators

(TicketMonster.app is my application name) I have this trace:

31:54:585 INFO ApplicationStore.<init>  App archive folder:/Users/administrator/git/new-development/applications
31:54:683 WARNING AppleLanguage.create  se isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:55:602 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:56:096 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:56:118 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:56:882 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:57:285 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:57:305 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:57:950 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:58:364 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:58:384 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
31:58:412 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:4444/inspector/
tests can access the server at http://0.0.0.0:4444/wd/hub
server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/administrator/git/new-development/applications' for new applications
Archived apps /Users/administrator/git/new-development/applications
using xcode install : /Applications/Xcode.app
using IOS version 7.0
ios >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=TicketMonster,CFBundleVersion=1.0
CFBundleName=Safari,CFBundleVersion=8536.25
CFBundleName=Safari,CFBundleVersion=8536.25
CFBundleName=Safari,CFBundleVersion=9537.53
```

2013-12-03 19:31:58.413:INFO::jetty-7.x.y-SNAPSHOT
2013-12-03 19:31:58.542:INFO::Started SelectChannelConnector@0.0.0.0:4444

And when I start running tests:

WebDriver webDriver = null;
        DesiredCapabilities capa = null;
        URL remoteUrl = new URL("http://localhost:" + port + "/wd/hub");

```
       capa = IOSCapabilities.iphone("TicketMonster");
       webDriver = new RemoteWebDriver(remoteUrl, capa);
       webDriver.switchTo().window("Web");
```

I am getting the error in terminal:

33:53:257 WARNING DefaultCommandListener.stderr  2013-12-03 19:33:53.256 instruments[52927:707] -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff7e972500
33:53:284 WARNING DefaultCommandListener.stderr  2013-12-03 19:33:53.283 instruments[52927:707] Exception during preparation: -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff7e972500
33:53:287 WARNING DefaultCommandListener.stderr  2013-12-03 19:33:53.286 instruments[52927:707] **\* Assertion failure in -[UIAInstrument _startAgentForApp:withPID:], /SourceCache/AutomationInstrument/AutomationInstrument-1000/Classes/UIAInstrument-Simulator.m:116
33:53:287 WARNING DefaultCommandListener.stderr  2013-12-03 19:33:53.287 instruments[52927:707] Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException

PLEASE HELP !!!!!

**Comment by pvaling** [comment]
Same issue on both Mavericks and Mountain Lion with Xcode 5.0.2 and Java 1.7.

**Comment by nicegraham** [comment]
you need to compile and run the code from the refactor branch. Can you also recompile your application as there was a problem in ios-driver corrupting the plist for ios7.

**Comment by tlytvyn** [comment]
I was trying to recompile it several times. 
You mean the ios-driver from refactor branch ?

**Comment by nicegraham** [comment]
yeah, ios-driver from the refactor branch and the application under test
before trying to run again.

**Comment by tlytvyn** [comment]
Tried to build the ios-driver from refactor branch, - now it's working with emulator, but I have different emulators and my app is always running on Iphone Retina 4 - how can I change the emulator to that one I need ?

And the second question is - what about running on real devices ? When I put -beta flag during running the script I receive the Cannot load libimobiledevice-sdk.dylib error:

Cannot load libimobiledevice-sdk.dylib
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.uiautomation.ios.server.IOSServerManager.<init>(IOSServerManager.java:69)
    at org.uiautomation.ios.server.IOSServer.initDriver(IOSServer.java:96)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:91)
    at org.uiautomation.ios.server.IOSServer.start(IOSServer.java:203)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:82)
Caused by: java.lang.NullPointerException
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
    at org.libimobiledevice.ios.driver.binding.IMobileDeviceFactory.unpack(IMobileDeviceFactory.java:73)
    at org.libimobiledevice.ios.driver.binding.IMobileDeviceFactory.<clinit>(IMobileDeviceFactory.java:42)
    ... 5 more

What should I do to fix this ?

**Comment by nicegraham** [comment]
Great. 

You can use the capabilities to set which device type and variation you want to use. 
e.g. capabilities.put("variation", variation required)
variations are: Regular, Retina35, Retina4, Retina, iPad25
type: iphone, ipad

Real device support is currently broken I'm afraid.

**Comment by tlytvyn** [comment]
When i set capability like this capa.setCapability("variation", "Regular");
I get the next error, but for Retina's working ok.

org.openqa.selenium.WebDriverException: iPhone incompatible with SDK 7.0

Is this because I have sdk 7 for Xcode ?

**Comment by nicegraham** [comment]
ios7 doesn't support non retina devices.

**Comment by pvaling** [comment]
I can't build refactor branch cause of test errors on 5.0.2 Xcode with iOS 7 default simulator and fresh oracle JDK 1.7. Is it possible to build ios-driver on that environment? Test are starting multiple times with iOS7 emulators but compilation hangs after 3-4 mins. I will provide logs if you confirm that it's normal to build project with IOS7.

**Comment by nicegraham** [comment]
yes you can build on that platform - it's what I have here. You can skip the tests mvn package -DskipTests=true
