### ISSUE TITLE
Create new ios-server.jar file from the refactor branch

### ISSUE THREAD

**Issue by gitnava** [ios-driver/ios-driver#187]
Based on what I have read among all the issues, ios-driver corrupting the plist for ios7. I need to compile the refactor branch and create a new ios-server.jar file. 

What would be the steps to create new ios-server.jar file from the refactor branch??

Thank you very much...

> > OS X 10.8.5 and Xcode 5.0.2

Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:4444/inspector/
tests can access the server at http://0.0.0.0:4444/wd/hub
server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/xxxxx/Downloads/applications' for new applications
Archived apps /Users/xxxxx/Downloads/applications
using xcode install : /Applications/Xcode.app
using IOS version 7.0
ios >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=Fandango,CFBundleVersion=5.9.1
CFBundleName=Safari,CFBundleVersion=8536.25
CFBundleName=Safari,CFBundleVersion=9537.53
```

2013-12-16 16:34:21.112:INFO::jetty-7.x.y-SNAPSHOT
2013-12-16 16:34:21.327:INFO::Started SelectChannelConnector@0.0.0.0:4444
38:30:758 WARNING IOSServlet.getResponse  4010ms.   GET  /status
45:21:098 INFO APPIOSApplication.canRun  The application doesn't have any content files. Localization related features won't be available.
45:34:578 WARNING DefaultCommandListener.stderr  2013-12-16 16:45:34.577 instruments[56738:707] -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff743ef500
45:34:579 WARNING DefaultCommandListener.stderr  2013-12-16 16:45:34.579 instruments[56738:707] Exception during preparation: -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff743ef500
45:34:629 WARNING DefaultCommandListener.stderr  2013-12-16 16:45:34.629 instruments[56738:707] **\* Assertion failure in -[UIAInstrument _startAgentForApp:withPID:], /SourceCache/AutomationInstrument/AutomationInstrument-1000/Classes/UIAInstrument-Simulator.m:116
45:34:630 WARNING DefaultCommandListener.stderr  2013-12-16 16:45:34.629 instruments[56738:707] Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException

ERROR: Instruments > IOS Simulator failed to install the application

**Comment by nicegraham** [comment]
The details are listed here:
http://ios-driver.github.io/ios-driver/building-source.html

**Comment by gitnava** [comment]
Great!!! I missed that page.
It works now.

Thank you

**Comment by gitnava** [comment]
Download the branch, run 'mvn clean install -DskipTests'  on it. Find the new jar file in the ios-driver-dev/server/target folder.
