### ISSUE TITLE
[MAC OS X] Driver is copying MobileSafari.app to a tmp folder and then copies it back with wrong credentials (Safari)(Refactor Branch)

### ISSUE THREAD

**Issue by Skarlso** [ios-driver/ios-driver#192]
Hello!

I'm having a weird issue here although I'm sure it's intentional but in my situation it messes up the whole run of the test. 
## Abstract

So what happens is that the runner for some reason (I'm sure there is an explanation for it) copies the MobileSafari.app away from the Application folder into some temp folder. I'm guessing this is how it works with it? But since it does that the simulator when it starts up will miss the application MobileSafari.app!!!! So it can't start it anymore. 
## Logs

Here is an output of that happening:

08:09:715 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
## Question

So after this happens I'm no longer able to use the MobileSafari.app because once it copies it back it will have the wrong credentials and it took me a whole reinstall or something like that to get the simulator to see the app again. 

I'm not quite sure why this is happening and what this install folder is and why the safari app gets copied out of it. 

Can somebody point me into the right direction please? 

Cheers,
Gergely

**Comment by rsalvador** [comment]
The reason the MobileSafari.app is temporarily moved out is because otherwise instruments in Xcode 5.0.\* no longer can start safari to run the test. After the test runs the runner should put it back and you should be able to see MobileSafari when you start the simulator manually. If for some reason the runner cannot put it back (i.e. because it gets killed before it puts it back), you can put it back yourself using the command shown in "if you need to restore it yourself use:". 

What do you mean by it will have the wrong credentials?. What error message do you get?

If you can't run mobile safari tests, could you attach the full log output for your run?

**Comment by Skarlso** [comment]
Hello Salvador!

So what happens is the following: 
- Test starts up and copies the MobileSafari out of Applications
- Test starts the simulator and the simulator no longer has safari there
- Test failes to start safari ( there is no error message about that happening )
- Test times out since there is nothing happening on the simulator ( that's the only error message )
- After test finishes I look into the folder and see that the MobileSafari was copied into the folder with root priviliges but the rest of the files in there has the credentials of my user. So I need to amend that file in order for the simulator to pick it up again. Which is very very weird. And I need to like restart the whole simulator / machine sometimes for the simulator to be able to pick up safari again.

But even so I get that it should not do that I don't get why the simulator no longer has safari in it. 

I know I could do it manually but obviously I can't do that during a test run. :)

**Comment by rsalvador** [comment]
Oh, maybe that is happening because you run ios-driver using sudo?.
What command do you use to start ios-driver?

**Comment by Skarlso** [comment]
Irrelevant now. Thanks for all the help though!
