### ISSUE TITLE
Cannot select date on Native Date Picker

### ISSUE THREAD

**Issue by pshakya** [ios-driver/ios-driver#193]
On the native view, need the way to select date on date picker and then dismiss date picker popup.

**Comment by federicoviscomi** [comment]
hi could you please use give more informations
for example these http://ios-driver.github.io/ios-driver/bug.html

**Comment by federicoviscomi** [comment]
check the requirements here
http://ios-driver.github.io/ios-driver/setup.html

**Comment by pshakya** [comment]
My problem is same as described in Issue #198. 

Here is system info I am using.

```
"build": {
  "revision": "120cf4311807e2e137e519f4c4877cf6340d0cbc",
  "time": "20130927-1435",
  "version": "0.6.5"
},
"ios": {"simulatorVersion": "6.1"},
"java": {"version": "1.7.0_45"},
"os": {
  "arch": "x86_64",
  "name": "Mac OS X",
  "version": "10.8.5"
},
```

**Comment by pshakya** [comment]
Thanks @federicoviscomi for your solution !!!
Anyone having this issue refer to Bug #198.
