### ISSUE TITLE
Run IOS web automation from my C# code

### ISSUE THREAD

**Issue by michaazran** [ios-driver/ios-driver#195]
Hi all
I managed to run automation on web browser on android device and now I need to do it on my 3.5G Iphone
I need to run it on real device browser from C# code
I downloaded the server 0.6.5 and I ran the java command to launch it with PORT 444
from my C# code I tried to open the browser but it failed
IWebDriver driver = new RemoteWebDriver(new Uri("http://127.0.0.1:4444/wd/hub"), DesiredCapabilities.IPhone());
but the command failed
"No response from server for url http://127.0.0.1:4444/wd/hub/session"

can anyone help me out here? am I missing something? is there something to install on the device? I am not using any XCode 

thank you

**Comment by freynaud** [comment]
real device is not supported yet.
