### ISSUE TITLE
C# and iOS7 fail to run in the simulator

### ISSUE THREAD

**Issue by winderdancer** [ios-driver/ios-driver#196]
I am new to this and trying to make it work with the C# selenium code 

My environment:
Mavericks + xcode 5.0.2. I am using iPhone Retina iOS 7 simulator as the test

I download the public jar file and use the following command to start it
$ java -jar /applications/ios-server-0.6.5.jar -aut ~/internationalmountains.app -port 4444 -simulators
59:51:457 INFO ApplicationStore.<init>  App archive folder:/Users/user/applications
59:52:262 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
59:52:765 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
59:52:798 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
59:53:519 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
59:53:915 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
59:53:937 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
59:54:522 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
59:54:946 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
59:54:966 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
59:54:993 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:4444/inspector/
tests can access the server at http://0.0.0.0:4444/wd/hub
server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/user/applications' for new applications
Archived apps /Users/user/applications
using xcode install : /user/Xcode.app
using IOS version 7.0
ios >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=InternationalMountains,CFBundleVersion=1.1
CFBundleName=Safari,CFBundleVersion=8536.25
CFBundleName=Safari,CFBundleVersion=8536.25
CFBundleName=Safari,CFBundleVersion=9537.53
```

2013-12-31 14:59:54.994:INFO::jetty-7.x.y-SNAPSHOT
2013-12-31 14:59:55.103:INFO::Started SelectChannelConnector@0.0.0.0:4444

﻿http://localhost:4444/wd/hub/status shows
﻿???????????{
  "class": "org.openqa.selenium.remote.Response",
  "hCode": 468821580,
  "sessionId": null,
  "state": null,
  "status": 0,
  "value": {
    "build": {
      "revision": "120cf4311807e2e137e519f4c4877cf6340d0cbc",
      "time": "20130927-1435",
      "version": "0.6.5"
    },
    "ios": {"simulatorVersion": "7.0"},
    "java": {"version": "1.7.0_40"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.9.1"
    },
    "state": "success",
    "supportedApps": [
      {
        "CFBundleDevelopmentRegion": "en",
        "CFBundleExecutable": "InternationalMountains",
        "CFBundleIconFile": "Icon.png",
        "CFBundleIdentifier": "com.yourcompany.InternationalMountains",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleName": "InternationalMountains",
        "CFBundlePackageType": "APPL",
        "CFBundleSignature": "????",
        "CFBundleSupportedPlatforms": ["iPhoneSimulator"],
        "CFBundleVersion": "1.1",
        "DTPlatformName": "iphonesimulator",
        "DTSDKName": "iphonesimulator7.0",
        "LSRequiresIPhoneOS": true,
        "NSMainNibFile": "MainWindow",
        "UIDeviceFamily": [1],
        "applicationPath": "/Users/user/internationalmountains.app",
        "device": "iphone",
        "deviceAlt": [
          "iphone",
          "ipod"
        ],
        "device_Alt": [
          "iphone",
          "ipad"
        ],
        "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=-674408620"},
        "sdkVersion": "7.0",
        "sdkVersion_Alt": [
          "5.0",
          "5.1",
          "6.0",
          "6.1"
        ],
        "simulator": true,
        "supportedLanguages": [
          "zh-Hant",
          "fr",
          "en"
        ],
        "timeHack": false,
        "variation": "Regular"
      },
      {
        "CFBundleDevelopmentRegion": "English",
        "CFBundleDisplayName": "Safari",
        "CFBundleExecutable": "MobileSafari",
        "CFBundleIcons": {"CFBundlePrimaryIcon": {
          "CFBundleIconFiles": [
            "icon~iphone.png",
            "icon~ipad.png",
            "icon@2x~iphone.png",
            "icon@2x~ipad.png",
            "icon-table.png",
            "icon-table@2x.png",
            "icon-spotlight~ipad.png",
            "icon-spotlight@2x~ipad.png"
          ],
          "UIPrenderedIcon": true
        }},
        "CFBundleIdentifier": "com.apple.mobilesafari",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "6.0",
        "CFBundleSignature": "????",
        "CFBundleSupportedPlatforms": ["iPhoneSimulator"],
        "CFBundleURLTypes~ipad": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          }
        ],
        "CFBundleURLTypes~iphone": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "Radar URL",
            "CFBundleURLSchemes": [
              "rdar",
              "radar"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          }
        ],
        "CFBundleURLTypes~ipod": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "Radar URL",
            "CFBundleURLSchemes": [
              "rdar",
              "radar"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          }
        ],
        "CFBundleVersion": "8536.25",
        "DTPlatformName": "iphonesimulator",
        "DTSDKName": "iphonesimulator6.0",
        "LSRequiresIPhoneOS": true,
        "SBMatchingApplicationGenres": [
          "Productivity",
          "Utilities"
        ],
        "SBUsesNetwork": 3,
        "SafariProductVersion": "6.0",
        "UIApplicationDisableLegacyAutorotationKey": true,
        "UIBackgroundModes": [
          "audio",
          "continuousFallback"
        ],
        "UIDeviceFamily": [
          2,
          1
        ],
        "UIHasPrefs": true,
        "UISupportedInterfaceOrientations": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight"
        ],
        "UISupportedInterfaceOrientations~ipad": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight",
          "UIInterfaceOrientationPortraitUpsideDown"
        ],
        "applicationPath": "/Users/user/.ios-driver/safariCopies/safari-6.0.app",
        "device": "iphone",
        "deviceAlt": [
          "ipad",
          "iphone",
          "ipod"
        ],
        "device_Alt": [
          "iphone",
          "ipad"
        ],
        "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=707870789"},
        "sdkVersion": "7.0",
        "sdkVersion_Alt": [
          "5.0",
          "5.1",
          "6.0",
          "6.1"
        ],
        "simulator": true,
        "supportedLanguages": [
          "hr",
          "ro",
          "ca",
          "vi",
          "tr",
          "fr",
          "unknown",
          "hu",
          "unknown",
          "th",
          "id",
          "pt-PT",
          "en-GB",
          "fi",
          "unknown",
          "sv",
          "it",
          "sk",
          "ja",
          "uk",
          "es",
          "da",
          "ms",
          "ko",
          "ar",
          "he",
          "en",
          "nl",
          "cs",
          "el",
          "pl",
          "pt",
          "ru",
          "de"
        ],
        "timeHack": false,
        "variation": "Regular"
      },
      {
        "CFBundleDevelopmentRegion": "English",
        "CFBundleDisplayName": "Safari",
        "CFBundleExecutable": "MobileSafari",
        "CFBundleIcons": {"CFBundlePrimaryIcon": {
          "CFBundleIconFiles": [
            "icon~iphone.png",
            "icon~ipad.png",
            "icon@2x~iphone.png",
            "icon@2x~ipad.png",
            "icon-table.png",
            "icon-table@2x.png",
            "icon-spotlight~ipad.png",
            "icon-spotlight@2x~ipad.png"
          ],
          "UIPrenderedIcon": true
        }},
        "CFBundleIdentifier": "com.apple.mobilesafari",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "6.0",
        "CFBundleSignature": "????",
        "CFBundleSupportedPlatforms": ["iPhoneSimulator"],
        "CFBundleURLTypes~ipad": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          }
        ],
        "CFBundleURLTypes~iphone": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "Radar URL",
            "CFBundleURLSchemes": [
              "rdar",
              "radar"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          }
        ],
        "CFBundleURLTypes~ipod": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "Radar URL",
            "CFBundleURLSchemes": [
              "rdar",
              "radar"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          }
        ],
        "CFBundleVersion": "8536.25",
        "DTPlatformName": "iphonesimulator",
        "DTSDKName": "iphonesimulator6.1",
        "LSRequiresIPhoneOS": true,
        "SBMatchingApplicationGenres": [
          "Productivity",
          "Utilities"
        ],
        "SBUsesNetwork": 3,
        "SafariProductVersion": "6.0",
        "UIApplicationDisableLegacyAutorotationKey": true,
        "UIBackgroundModes": [
          "audio",
          "continuousFallback"
        ],
        "UIDeviceFamily": [
          1,
          2
        ],
        "UIHasPrefs": true,
        "UISupportedInterfaceOrientations": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight"
        ],
        "UISupportedInterfaceOrientations~ipad": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight",
          "UIInterfaceOrientationPortraitUpsideDown"
        ],
        "applicationPath": "/Users/user/.ios-driver/safariCopies/safari-6.1.app",
        "device": "iphone",
        "deviceAlt": [
          "iphone",
          "ipod",
          "ipad"
        ],
        "device_Alt": [
          "iphone",
          "ipad"
        ],
        "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=707870789"},
        "sdkVersion": "7.0",
        "sdkVersion_Alt": [
          "5.0",
          "5.1",
          "6.0",
          "6.1"
        ],
        "simulator": true,
        "supportedLanguages": [
          "hr",
          "ro",
          "ca",
          "vi",
          "tr",
          "fr",
          "unknown",
          "hu",
          "unknown",
          "th",
          "id",
          "pt-PT",
          "en-GB",
          "fi",
          "unknown",
          "sv",
          "it",
          "sk",
          "ja",
          "uk",
          "es",
          "da",
          "ms",
          "ko",
          "ar",
          "he",
          "en",
          "nl",
          "cs",
          "el",
          "pl",
          "pt",
          "ru",
          "de"
        ],
        "timeHack": false,
        "variation": "Regular"
      },
      {
        "CFBundleDevelopmentRegion": "English",
        "CFBundleDisplayName": "Safari",
        "CFBundleExecutable": "MobileSafari",
        "CFBundleIcons": {"CFBundlePrimaryIcon": {
          "CFBundleIconFiles": [
            "icon-spotlight~ipad.png",
            "icon-table~ipad.png",
            "icon-about~ipad.png",
            "icon-table~ipad.png",
            "icon-spotlight@2x.png",
            "icon-table@2x.png",
            "icon~ipad.png",
            "icon-about@2x.png",
            "icon@2x~iphone.png",
            "icon@2x~ipad.png"
          ],
          "UIPrenderedIcon": true
        }},
        "CFBundleIdentifier": "com.apple.mobilesafari",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "7.0",
        "CFBundleSignature": "????",
        "CFBundleSupportedPlatforms": ["iPhoneSimulator"],
        "CFBundleURLTypes~ipad": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          },
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "MobileSafari Tab URL",
            "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
          }
        ],
        "CFBundleURLTypes~iphone": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "Radar URL",
            "CFBundleURLSchemes": [
              "rdar",
              "radar"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          },
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "MobileSafari Tab URL",
            "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
          }
        ],
        "CFBundleURLTypes~ipod": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "Radar URL",
            "CFBundleURLSchemes": [
              "rdar",
              "radar"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          },
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "MobileSafari Tab URL",
            "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
          }
        ],
        "CFBundleVersion": "9537.53",
        "DTPlatformName": "iphonesimulator",
        "DTSDKName": "iphonesimulator7.0",
        "LSRequiresIPhoneOS": true,
        "MallocBehavior": {"NanoAllocator": false},
        "SBMatchingApplicationGenres": [
          "Productivity",
          "Utilities"
        ],
        "SBUsesNetwork": 3,
        "SafariProductVersion": "7.0",
        "UIApplicationDisableLegacyAutorotationKey": true,
        "UIBackgroundModes": [
          "audio",
          "continuousFallback"
        ],
        "UIBackgroundStyle": "UIBackgroundStyleDarkBlur",
        "UIDeviceFamily": [
          1,
          2
        ],
        "UIHasPrefs": true,
        "UIStatusBarTintParameters": {"UINavigationBar": {"Style": "UIBarStyleDefault"}},
        "UISupportedInterfaceOrientations": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight"
        ],
        "UISupportedInterfaceOrientations~ipad": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight",
          "UIInterfaceOrientationPortraitUpsideDown"
        ],
        "UIViewControllerBasedStatusBarAppearance": true,
        "applicationPath": "/Users/user/.ios-driver/safariCopies/safari-7.0.app",
        "device": "iphone",
        "deviceAlt": [
          "iphone",
          "ipod",
          "ipad"
        ],
        "device_Alt": [
          "iphone",
          "ipad"
        ],
        "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=2134756163"},
        "sdkVersion": "7.0",
        "sdkVersion_Alt": [
          "5.0",
          "5.1",
          "6.0",
          "6.1"
        ],
        "simulator": true,
        "supportedLanguages": [
          "hr",
          "ro",
          "ca",
          "vi",
          "tr",
          "fr",
          "unknown",
          "hu",
          "unknown",
          "th",
          "id",
          "pt-PT",
          "en-GB",
          "fi",
          "unknown",
          "sv",
          "it",
          "sk",
          "ja",
          "uk",
          "es",
          "da",
          "ms",
          "ko",
          "ar",
          "he",
          "en",
          "nl",
          "cs",
          "el",
          "pl",
          "pt",
          "ru",
          "de"
        ],
        "timeHack": false,
        "variation": "Regular"
      }
    ]
  }
}

My C# code is
            DesiredCapabilities capabilities = DesiredCapabilities.IPhone();
            capabilities.SetCapability("language", "en");
            capabilities.SetCapability("variation", "Retina4");

```
        driver = new RemoteWebDriver(new Uri("http://<ip>:4444/wd/hub"), capabilities);
        IWebElement element = driver.FindElement(By.ClassName("UIATableCell"));
        element.Click();
```

I get the following error when running the code
?2013-12-31 14:59:54.994:INFO::jetty-7.x.y-SNAPSHOT
2013-12-31 14:59:55.103:INFO::Started SelectChannelConnector@0.0.0.0:4444
22:13:342 WARNING IOSServlet.getResponse  9974ms.   GET  /status
25:13:284 WARNING DefaultCommandListener.stderr  2013-12-31 15:25:13.281 instruments[6080:507] -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff7c314db0
25:13:292 WARNING DefaultCommandListener.stderr  2013-12-31 15:25:13.282 instruments[6080:507] Exception during preparation: -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff7c314db0
25:13:381 WARNING DefaultCommandListener.stderr  2013-12-31 15:25:13.380 instruments[6080:507] **\* Assertion failure in -[UIAInstrument _startAgentForApp:withPID:], /SourceCache/AutomationInstrument/AutomationInstrument-1000/Classes/UIAInstrument-Simulator.m:116
25:13:382 WARNING DefaultCommandListener.stderr  2013-12-31 15:25:13.381 instruments[6080:507] Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException

I checked other posts and found some similar ones saying we need the refractor branch for ios 7? is it required? If so, can you give me the detailed instructions?

I do not use Selenium server on the Mac server. Does the client-side binary version matter?  

How do I resolve this issue? Any tip is welcome.. I see a lot of samples for Java but not C#.. Wondering if this stuff could support C# perfectly.

**Comment by nicegraham** [comment]
the fix in this issue should sort your problem out
https://github.com/ios-driver/ios-driver/issues/186
