### ISSUE TITLE
How Selenium C# works with the Mobile Safari in simulator

### ISSUE THREAD

**Issue by winderdancer** [ios-driver/ios-driver#197]
Hi, I am looking for the detailed instructions to allow Selenium C# code to work with Mobile Safari in the simulator on Mavericks ios7..  I am a newbie to this. Please forgive any naive questions below. 

I followed the steps in http://ios-driver.github.io/ios-driver/safari.html and I assume the steps will be
1. Run sudo
   sudo chmod 666 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator*.sdk/Applications/MobileSafari.app/Info.plist
2. Start ios driver (public 0.6.5 version)
   java -jar /applications/ios-server-0.6.5.jar  -port 4444 -simulators
   (Is the command right? What shall i pass into the command for mobile safari?)
3. Start simulator by XCode?
   Is it needed? How to do that? How to just launch mobile safari without launching an app? 
4. Client C# code? Do I pass DesiredCapabilities.Safari() or iPhone?  There is no IOSCapacities in the C# world.. 
   
   ```
       DesiredCapabilities capabilities = DesiredCapabilities.Safari();
       capabilities.SetCapability("language", "en");
       capabilities.SetCapability("variation", "Retina4");
   
       driver = new RemoteWebDriver(new Uri("http://<>:4444/wd/hub"), capabilities);
   ```

That fails in the last line with device not supported unknown error (33)

Please share with me for the steps you successfully use C# client-code to launch mobile safari..

**Comment by nicegraham** [comment]
this https://github.com/ios-driver/ios-driver/issues/186
