### ISSUE TITLE
How to select from the UIAPickerWheel

### ISSUE THREAD

**Issue by gitnava** [ios-driver/ios-driver#198]
I have no success using the following code, it gives me the tag name exception.

   WebElement picker = webDriver.findElement(By.xpath("//UIAPickerWheel[contains(@value,'Month')]"));
   Select select = new Select(picker);
    select.selectByValue("1 - January");

And/Or please let me know if there is a way to scroll/swipe the UIAPickerWheel...

Any help is really appreciated!!!
Thank you :)

**Comment by darraghgrace** [comment]
Hi, you can do something like 

WebElement picker = webDriver.findElement(By.xpath("//UIAPickerWheel[contains(@value,'Month')]"));

((RemoteUIAPickerWheel) element).select("1 - January")

**Comment by gitnava** [comment]
Hi
Thank you...

I tried the following and got the error below:

Tried:
WebElement picker = webDriver.findElement(By.xpath("//UIAPickerWheel[contains(@value,'Month')]"));
((RemoteUIAPickerWheel) picker).select("1 - January");

ERROR:java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to org.uiautomation.ios.client.uiamodels.impl.RemoteUIAPickerWheel

any suggestion?
thanks

**Comment by darraghgrace** [comment]
Is your xpath for UIAPickerWheel correct? Double check that in inspector.

I just verified this works with UIACatalog for UIAPicker and UIAPickerWheel

((RemoteUIAPickerWheel) driver.findElement(By.xpath("//UIAPicker[2]//UIAPickerWheel[2]"))).select("March")

**Comment by gitnava** [comment]
I tried many combinations of xpaths. I don't think it is a xpath issue because when the xpath seems to be correct it shows the error below and when the xpath seems to be incorrect it shows the error: element can't be found. So I m still stuck, any further advice is really appreciated. Thanks a lot!

ERROR:java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to org.uiautomation.ios.client.uiamodels.impl.RemoteUIAPickerWheel

**Comment by darraghgrace** [comment]
It's difficult to debug this without access to your app. Are you using a recent version of ios-driver?

Are you sure that the element is not a UIAPicker as opposed to a UIAPickerWheel?

Have you tried to retrieve the values from the UIAPickerWheel?

WebElement element = webDriver.findElement(By.xpath("//UIAPickerWheel[contains(@value,'Month')]"));

((RemoteUIAPickerWheel) element).getValues()

Have you tried to inspect the element in inspector? http://localhost:4444/inspector/

**Comment by gitnava** [comment]
Yeah I understand.
I am currently using the build from the refactor branch. I am sure it is the UIAPickerWheel, I have attached the screenshot from the inspector.
The getvalues method is getting the same ClassCastException error, so no luck there either, which makes sense since it is casting the same way. So still cant cast the webElement into RemoteUIAPickerWheel ...

Is there a way to instantiate the RemoteUIAPickerWheel to use the select method without casting it?? 
What would be the correct approach?

Thanks !!!

![screen shot 2014-01-09 at 10 58 08 am](https://f.cloud.github.com/assets/1790938/1884129/78416d4e-7995-11e3-8f2a-2c48fe2d9c9c.png)

**Comment by pshakya** [comment]
darraghgrace, can you share the sample code that is working for you.

Thanks!

**Comment by darraghgrace** [comment]
@gitnava : I'm not sure why you get the casting error. In the inspector can you hit the ESC key to launch the xpath helper and try use an xpath like  "//UIAPicker[1]//UIAPickerWheel[1]" (assuming the is the only UIAPicker/UIAPickerWheel on the screen). 
I've demonstrated on one of the UIAPickers in UICatalog, see bitmap

![screen shot 2014-01-14 at 21 11 54](https://f.cloud.github.com/assets/2386816/1915024/a953cd54-7d60-11e3-868f-367589d179cc.png)

Values returned (latest refactor branch)
![screen shot 2014-01-14 at 21 15 42](https://f.cloud.github.com/assets/2386816/1915046/e8c6fc5e-7d60-11e3-99a6-76679df70254.png)

**Comment by darraghgrace** [comment]
@pshakya - What exactly are you after? Sample code in comments above on how to getValues and select on a UIAPicker.

**Comment by pshakya** [comment]
Typecasting WebElement to RemoteUIAPickerWheel is not working for me I get following error

Exception in thread "main" java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to org.uiautomation.ios.client.uiamodels.impl.RemoteUIAPickerWheel

Here is the code:

RemoteWebDriver driver;
WebElement element = driver.findElement(By.xpath("//UIAPickerWheel[3]"));
((RemoteUIAPickerWheel) element).select("1999");

**Comment by gitnava** [comment]
@darraghgrace, I am using the Xpather helper and its finding 1 result (not showing on the screenshot).
However, I am still seeing the cast issue like @pshakya when either selecting or getting the values.

I am gonna try to look into it some more, but PLEASE let us know if you come across any possible solution. In case we cant find a solution we will have to stop using ios-driver and pursue a different option.

Possible solution on RemoteUIAPickerWheel.java ??? 

Thank you !!

![screen shot 2014-01-14 at 7 08 40 pm](https://f.cloud.github.com/assets/1790938/1917341/70f578ae-7d92-11e3-9bd5-d61c3648549e.png)

**Comment by federicoviscomi** [comment]
could you try to use 

``` java
RemoteIOSDriver driver
```

instead of 

``` java
RemoteWebDriver driver
```

**Comment by darraghgrace** [comment]
@gitnava @pshakya  : If you could reproduce this on a public app like UICatalog it would be very helpful. As mentioned above, neither myself or @federicoviscomi can reproduce this issue, therefore we can't look into a solution. Alternatively if you could supply us with your app to repro it would help a lot.

**Comment by federicoviscomi** [comment]
the following code reproduce the issue on UICatalog2.10

``` java
public class issue198 extends BaseIOSDriverTest {

  @Test
  public void reproduceIssue198() throws JSONException {
    RemoteWebDriver driver = new RemoteWebDriver(SampleApps.uiCatalogCap());
    WebDriverWait webDriverWait = new WebDriverWait(driver, 2);

    //click on pickers cell
    By pickersCellLocator = By.xpath("//UIATableCell[contains(@name,'Pickers')]");
    webDriverWait.until(ExpectedConditions.visibilityOfElementLocated(pickersCellLocator));
    WebElement pickersCell = driver.findElement(pickersCellLocator);
    pickersCell.click();

    //click on date picker
    By datePickerButtonLocator = By.xpath("//*[contains(@name,'UIDatePicker')]");
    webDriverWait.until(ExpectedConditions.visibilityOfElementLocated(datePickerButtonLocator));
    WebElement datePickerButton = driver.findElement(datePickerButtonLocator);
    datePickerButton.click();

    //select year
    By yearPickerWheelLocator = By.xpath("//UIAPickerWheel[3]");
    WebElement element = driver.findElement(yearPickerWheelLocator);
    RemoteUIAPickerWheel yearWheel = ((RemoteUIAPickerWheel) element);
    yearWheel.select("1999");
  }
}
```

the result is
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to org.uiautomation.ios.client.uiamodels.impl.RemoteUIAPickerWheel
    at org.uiautomation.ios.e2e.uicatalogapp.issue198.reproduceIssue198(issue198.java:36)

**Comment by federicoviscomi** [comment]
but if you use RemoteIOSDriver instead of RemoteWebDriver it should work
you can replace it completely or replace it only when there is a wheel picker involved using the following code

``` java
 RemoteIOSDriver iosDriver = IOSDriverAugmenter.getIOSDriver(driver);
    WebElement element = iosDriver.findElement(yearPickerWheelLocator);
    RemoteUIAPickerWheel yearWheel = ((RemoteUIAPickerWheel) element);
    yearWheel.select("1999");
```

**Comment by pshakya** [comment]
That was the problem and it is solved now I an select date. I appreciate your help @darraghgrace and @federicoviscomi.

Thanks!!!

How do I dismiss datepicker pop up? Until I dismiss it, I cannot proceed further.

**Comment by pshakya** [comment]
I meant dismiss date picker on iPad.

**Comment by gitnava** [comment]
@federicoviscomi and @darraghgrace - Thank you so much!! it solved the problem.

Thanks again!!

**Comment by federicoviscomi** [comment]
@pshakya could you please upload a screenshot of the application when the application shows the date picker and you want to dismiss it

**Comment by pshakya** [comment]
@federicoviscomi 
Here is the screenshot on iPad. There is no button to dismiss date picker popup.

![screen shot 2014-01-21 at 11 14 46 am](https://f.cloud.github.com/assets/634605/1967077/b6f5f87c-82d0-11e3-8f2f-337ed29d2ac6.png)

**Comment by pshakya** [comment]
Starting new bug on this, since original bug is now resolved.

**Comment by shabana-parveen** [comment]
![Uploading Screen Shot 2016-07-15 at 4.36.37 PM.png…]()
@federicoviscomi , Please help for below Issue:

I try to select a random month with year, I m unable to select it as scroll/swipe is not working.

PS: It always try to select a current value only as I understand UIAPickerWheel isn't having list of values, so I try to scroll it, but could luck, any valuable suggestion will be appreciated. 

Below is my code snippet with image:

//Click on select from year dropdown        driver.findElement(By.xpath("//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIATextField[7]")).click();

//Get number of UIAPickerWheel's
        List<WebElement> DatePicker = driver.findElements(By.xpath("//UIAApplication[1]/UIAWindow[1]/UIAPicker[1]/UIAPickerWheel"));
        for (int i = 1; i <=DatePicker.size(); i++) {
            IOSElement we = (IOSElement) driver.findElementByXPath("//UIAApplication[1]/UIAWindow[1]/UIAPicker[1]/UIAPickerWheel["+(i)+"]");
            driver.scrollTo("June");
            we.sendKeys("June");
        }

**Comment by shabana-parveen** [comment]
any input will be appreciated.

**Comment by shekhar-ireslab** [comment]
@shabana-parveen  
You can use Horizontal and Vertical swipe functionality as scroll method is deprecated update your Java client jar file.
