### ISSUE TITLE
[refactor] Safari occasionally hangs waiting for Instruments registration

### ISSUE THREAD

**Issue by fionawhim** [ios-driver/ios-driver#199]
Using branch refactor as of today, iOS 7 in the simulator. Testing MobileSafari. Connecting through a Selenium hub.

After 5–10 successful test runs, each one followed by a quit() that seems to cleanly terminate MobileSafari, ios-driver will hang on creation of a new session. The logs I've turned on show:

00:18:731 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/phopkins/.ios-driver/safariCopies/MobileSafari-7.0.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app
00:19:278 FINE InstrumentsApple.start  waiting for registration request
01:19:835 FINE JSTemplate.generate  JS: var root = UIAutomation.cache.get('1');var result = root.element(-1,{"l10n":"none","expected":"UIAScrollView","matching":"exact","method":"type"});UIAutomation.createJSONResponse('7491af22-aa98-4e52-a688-e582ac374512',0,result);

The Simulator shows the iOS7 home screen, before the "about:blank" bookmark is clicked.

Is there any more info I can provide to diagnose this?

**Comment by nicegraham** [comment]
Are you running on VMs? We've found that they seem to get flaky after n test runs, even if you're on a physical machine the same could hold true - Instruments in itself isn't the most robust piece of software. To get around this we reboot the machines every x testcases. In order to do that we run SeleniumGridExtras [https://github.com/groupon/Selenium-Grid-Extras] on the node machines and then register to the grid specifying IOSRemoteProxy to use the changes in this commit:
https://github.com/ios-driver/ios-driver/commit/8e8c42b4ca0c45409b246c27830678016adfeec5

You can see how to build and compile the proxy into hub here http://ios-driver.github.io/ios-driver/scale.html

**Comment by fionawhim** [comment]
This is through a grid service, but it and everything else are running on a
local laptop, no VMs.

**Comment by nicegraham** [comment]
not sure what you mean by "grid service". We've found that the nodes become flaky after a number of runs and we've found that regular reboots have helped, regardless the grid implementation I think this could hold true.

**Comment by fionawhim** [comment]
Yeah, the grid aspect is irrelevant.

Do you have any tips for digging in to the issue with Instruments not
connecting with MobileSafari? Logging and suchlike? I'd like to try and
make it more solid.

(FWIW I'm using ios-driver with Huxley to generate screenshots for mobile
web pages.)

**Comment by nicegraham** [comment]
@rsalvador can you give any debug guidance on this?

**Comment by fionawhim** [comment]
FWIW, I ended up adding "-v" to the Instruments command line (in
InstrumentsApple#createInstrumentCommand) to see if that could aid
debugging and… the problem went away.

So whatever race condition is inside Instruments that causes it to flake
now and again in this manner was for me solved by forcing it to log
verbosely.

**Comment by freynaud** [comment]
hi,
can you try again with the dev branch ( without the -v )  and see if you still have the issue.
https://github.com/ios-driver/ios-driver/commit/4a526d461d943506b58381a5a22ee9a2d9003a39
should detect the "it hangs" problem.

I'll try with the -v option and see if it makes the issue go on slow VMs.
françois

**Comment by freynaud** [comment]
are you still facing this issue ?

**Comment by fionawhim** [comment]
We recently switched to the dev branch but have kept the verbose flag in.

**Comment by freynaud** [comment]
ok, I've added the flag in ios-driver.
