### ISSUE TITLE
Need some information

### ISSUE THREAD

**Issue by freynaud** [ios-driver/ios-driver#2]
Hi!

Can you please tell how to create the correct DesiredCapabilities object for test native applications on Python.

tried

a = webdriver.DesiredCapabilities.IPAD
a ['browserName'] = 'appCFBundleName'
a ['version'] = '1 .0

An error in IDE:

selenium.common.exceptions.WebDriverException: Message: u"Cannot cast null to DeviceType\nBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'\nSystem info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8', java.version: '1.6.0_35'\nDriver info: driver.version: unknown\nBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'\nSystem info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8', java.version: '1.6.0_35'\nDriver info: driver.version: unknown" ; Stacktrace: Method handle threw an error in NewSessionNHandler.java 

ios-server-0.6.0
python 2.7
selenium 2.31.0

P.S. Is there a forum where can ask questions like this?

**Comment by nicegraham** [comment]
@Kappasama you may also need to explicitly set Simulator to true if you aren't using a physical device. The Capabilities was setting this to false by default and it was causing some confusion.

**Comment by lukeis** [comment]
python capability should look like this:

cap = {
        'device' : 'iphone',
        'language': 'en',
        'locale': 'en_US',
        'CFBundleName': 'appCFBundleName',
        'simulator':True,
        'variation':'Regular'
    }

here's our email / forum:
  http://groups.google.com/group/ios-driver
