### ISSUE TITLE
What is the magic behind the "ARCHIVE" link on the http://localhost:5555/wd/hub/devices/all page?

### ISSUE THREAD

**Issue by rugh** [ios-driver/ios-driver#20]
Hey guys,

this is more sort of a question than an issue, but for completly automate a test on a real device vie the CLI i need to know what magic is executed when i press the "ARCHIVE" link below the desired application on http://localhost:5555/wd/hub/devices/all.
After some research in the code base it seemed to me, that method behind that button simply builds a CLI command with all necessary parameters and executes it afterwards. Am i correct?
It would be great to get some more information on this topic especially with focus on test automation.

Thanks in advance
Robert

**Comment by freynaud** [comment]
it archives the app from the device and copy it to the host.You can then use that for testing.
It's not a necessary step. You can also build the ipa yourself, it will work the same. It's just a convenience method.
François

**Comment by rugh** [comment]
Hey François,

this command did the job for me:

xcrun -sdk iphoneos6.1 PackageApplication -v "<path_to_builded_app>" -o "<path_to_desired_ipa_file>" --sign "<code_signing_identity>" --embed "<provisioning_profile>"

Thanks for the hint and nice greetings
Robert
