### ISSUE TITLE
Cannot Select Item from native UIAPickerWheel List

### ISSUE THREAD

**Issue by pshakya** [ios-driver/ios-driver#202]
I am not able to select item from the native UIAPickerWheel list.

element = driver.findElement(By.xpath("//UIAPickerWheel[1]")));
((RemoteUIAPickerWheel) element).select("CA");

Getting following error:
org.openqa.selenium.WebDriverException: - selectValue requires a valid value

"CA" is one of the value in the UIAPickerWheel list.

Can some one help?

Thanks.

**Comment by federicoviscomi** [comment]
I have the same problem with UICatalog2.10 and i am trying to figure it out.
What iOS SDK did you use to compile the application?
How do you create the driver?

**Comment by pshakya** [comment]
Here are the Detail.
XCode Version 4.6.3

```
"build": {
  "revision": "120cf4311807e2e137e519f4c4877cf6340d0cbc",
  "time": "20130927-1435",
  "version": "0.6.5"
},
"ios": {"simulatorVersion": "6.1"},
"java": {"version": "1.7.0_45"},
"os": {
  "arch": "x86_64",
  "name": "Mac OS X",
  "version": "10.8.5"
}
```

**Comment by federicoviscomi** [comment]
can it be that the picker wheel is not valid?
what does the following code return?

``` java
((RemoteUIAPickerWheel) element).isDisplayed();
```

I am assuming that you are not using the latest Xcode and iOS because you need to support older version, right?

**Comment by pshakya** [comment]
@federicoviscomi that is correct.
But problem got resolved after compiling app with Xcode 5 and using dev version of ios-driver (with iOS 7 support).

Thanks!
