### ISSUE TITLE
Can not access web view within the hybrid app

### ISSUE THREAD

**Issue by sukoneru** [ios-driver/ios-driver#205]
HI,

 I am trying to access webview flow within the native app and I noticed an exception as the element could not be identified.

 It's a simple flow in eBay app, to click the register button which takes to web view.

 I did try the switch to web mode(driver.switchTo().window("Web")) and access elements as defined in web page lay out.

 Below are more details include sample test code and stack trace. Any suggestions will be really helpful.

 My application:- eBay app
 Environment details:- 
   "build": {
      "revision": "120cf4311807e2e137e519f4c4877cf6340d0cbc",
      "time": "20130927-1435",
      "version": "0.6.5"
    },
    "ios": {"simulatorVersion": "6.1"},
    "java": {"version": "1.7.0_25"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.8.5"
    },

 Sample test code:-
    @Test
    public void testSignIn() throws Exception {

```
    IOSCapabilities eBay = null;
    eBay = IOSCapabilities.iphone("eBay","3.2.0");
//  WebDriver driver = new RemoteIOSDriver(new URL("http://localhost:8080/wd/hub"), eBay);
    WebDriver driver = new RemoteWebDriver(new URL("http://localhost:8080/wd/hub"), eBay);
    Thread.sleep(2000);
    driver.findElement(By.xpath("//UIAButton[2]")).click();
    Thread.sleep(2000);
    driver.findElement(By.xpath("//UIAButton[2]")).click();
    Thread.sleep(2000);       driver.findElement(By.xpath("//UIATableView/UIATableCell[3]/UIAButton[1]")).click();
    Thread.sleep(2000);
    driver.switchTo().window("Web");
    Thread.sleep(2000);
    driver.findElement(By.id("firstname")).sendKeys("surya");
    driver.quit();

}
```

 Stacktrace:-

org.openqa.selenium.NoSuchElementException: No element found for
{"using":"id","value":"firstname"} after waiting for 0 ms.
For documentation on this error, please visit:
http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5',
java.version: '1.7.0_25'
Driver info: driver.version: unknown
Command duration or timeout: 1.33 seconds
For documentation on this error, please visit:
http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5',
java.version: '1.7.0_25'
Driver info: driver.version: RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAcce
ssorImpl.java:57)
    at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstru
ctorAccessorImpl.java:45)

**Comment by freynaud** [comment]
Hello,

the app has several webviews.  driver.switchTo().window("Web"); is an alias for  driver.switchTo().window("Web_1"); and it switches to the first webview. In your case, you want the the last and third one. You can debug what webview you need doing : 

System.out.println(driver.getWindowHandles());

then switch to each webview, get the title and current URL for instance, and see if that's the one you need.

Then for better support of sendkeys + hybrid, you should turn off nativeEvents for now. The following test was working for me using version 3.2 and the latest build for the dev branch
https://dl.dropboxusercontent.com/u/24687868/ios-beta/ios-server-0.6.6-SNAPSHOT.jar
Please reopen if you still see the same problem after using this code.

```
driver.switchTo().window("Web_3");

WebElement e = driver.findElement(By.id("firstname"));

Configurable c = IOSDriverAugmenter.augment(driver);
c.setConfiguration(WebDriverLikeCommand.SET_VALUE, "nativeEvents", false);

e.sendKeys("surya");
```
