### ISSUE TITLE
FAQ entry for permission setting doesn't apply to Mavericks

### ISSUE THREAD

**Issue by shish** [ios-driver/ios-driver#206]
http://ios-driver.github.io/ios-driver/faq.html mentions editing /etc/authorization -- this file no longer exists in Mavericks, having been replaced with /var/db/auth.db

Have tried

```
sudo security authorizationdb write system.privilege.taskport allow
```

But am still getting the prompt "Instruments wants permission to analyze other processes" :(

**Comment by freynaud** [comment]
Hi,

can you try that : 
https://github.com/ios-driver/ios-driver/blob/dev/common/src/main/resources/permissions.sh
Go into the common/src/main/resources folder, and execute the script.

François

**Comment by shish** [comment]
The mac I was testing on is in the process of being reinstalled at the moment >_<  Those permissions are the ones I ended up using though

**Comment by freynaud** [comment]
ok. Please reopen if you still face that issue.

thanks,
françois
