### ISSUE TITLE
Cannot dismiss Native App Date Picker on iPad

### ISSUE THREAD

**Issue by pshakya** [ios-driver/ios-driver#207]
Not able to dismiss Date Picker on iPad. There is no "Done" button as in iPhone for date picker on iPad. How can it be dismissed? Other objects on page are invisible to driver because date picker is on top most layer.

![aaa](https://f.cloud.github.com/assets/634605/1984997/fb003e26-8436-11e3-9aa9-04df2288a971.png)

**Comment by azaytsev** [comment]
Try doing this as a temporary solution
driver.executeScript("UIATarget.localTarget().frontMostApp().mainWindow().tap()");
This should tap you out to the main window.

You can also try to tap to a specific screen location by using the offset. For example      driver.executeScript("UIATarget.localTarget().frontMostApp().mainWindow().tapWithOptions({tapOffset:{x:0.75, y:0.25}});");

**Comment by pshakya** [comment]
Thanks @azaytsev appreciate your help!
