### ISSUE TITLE
Simulator will not open 

### ISSUE THREAD

**Issue by mlmathisumes** [ios-driver/ios-driver#208]
java -jar ios-server-0.6.5.jar -simulators
33:32:870 INFO ApplicationStore.<init>  App archive folder:/Users/malikmathis/Desktop/JARFiles/applications
33:33:374 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
33:33:655 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
33:33:668 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
33:34:131 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
33:34:424 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
33:34:437 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
33:34:453 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:5555/inspector/
tests can access the server at http://0.0.0.0:5555/wd/hub
server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all

ERROR Recieved:

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: {simulator=true, timeHack=false, variation=Regular, locale=en_GB, CFBundleName=Safari, device=iphone, language=en}not available. Available are [Simulator]
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'

Code USED:
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.uiautomation.ios.IOSCapabilities;

public class SimulatorTest {
      public static void main(String[] args) throws Exception {
            DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
            RemoteWebDriver driver = new RemoteWebDriver(new URL("http://0.0.0.0:5555/wd/hub"), safari);

```
        driver.get("http://www.ebay.co.uk/");

        System.out.println(driver.getTitle());
        driver.quit();
    }
```

**Comment by bijoyv** [comment]
don't use -simulators as an argument for jar, if you don't provide the uuid of a real device attached, it always select simulator

**Comment by mach6** [comment]
please re-open if needed
