### ISSUE TITLE
No browsers shown in my GRID

### ISSUE THREAD

**Issue by garryralim** [ios-driver/ios-driver#210]
Hi,

This is what my GRID looks like after adding ios-driver (version 0.6.5) as a node.

![screen shot 2014-01-26 at 21 39 35](https://f.cloud.github.com/assets/6508758/2004948/1f8ab56a-86ca-11e3-8e55-04b69e83e167.png)

This is what I entered in Terminal: 

![screen shot 2014-01-26 at 21 42 42](https://f.cloud.github.com/assets/6508758/2004956/7b03652c-86ca-11e3-8a72-dcedcbea46c3.png)

My goal is use ios-driver to test websites on the mobile Safari the iOS simulators. Can anyone help me setting things up?

**Comment by nicegraham** [comment]
if you're expecting mobile safari - you'll need to add -simulators to your
start command.

**Comment by garryralim** [comment]
Thanks for you quick reply nicegraham. This is how my node looks like now. I'm assuming this is correct right?

![screen shot 2014-01-26 at 23 25 07](https://f.cloud.github.com/assets/6508758/2005244/e3355bba-86d8-11e3-926e-f309cd067181.png)

**Comment by nicegraham** [comment]
yeah, that should allow you to run safari tests. If you want native
applications you'll either need to specify them as part of the start
command or put the apps in the monitored folder.
