### ISSUE TITLE
Is 0.6.6 the next official release

### ISSUE THREAD

**Issue by sankarharidasmenon29** [ios-driver/ios-driver#212]
Hi, Pls let me know if 0.6.6 the next official release.

Thanks,
Sankar

**Comment by ghost** [comment]
How is this even an issue? Perhaps you meant to ask what updates are being made available in the next release. For more info, read up the release notes document from the current release which lists the items in the pipeline or post a question in the iOS-driver google group - https://groups.google.com/forum/#!forum/ios-driver
