### ISSUE TITLE
Click doesn't wait for page load

### ISSUE THREAD

**Issue by srizzling** [ios-driver/ios-driver#214]
I am getting a similar error to this: https://github.com/appium/appium/issues/1208 using the ios-driver. The page does not wait after clicking a button. Clicking the button causes it to reload the page, and before the page, tests cannot find the text for the test to pass. I have tried injecting some javascript before the click to wait for the element but its not a very nice soultion and it didn't really work. (Putting Waits is not a good solution either!)

**Comment by freynaud** [comment]
as far as I know, the webdriver protocol doesn't take care of page load.It's up to the test writer to handle the waiting. 
This is because "is loaded" is impossible to define. If you have a page with a lot of ajax, it may always refresh etc. I suggest you follow you click by an explicit wait.

**Comment by csnover** [comment]
it does. https://dvcs.w3.org/hg/webdriver/raw-file/default/webdriver-spec.html#page-load-strategies-1
