### ISSUE TITLE
Self-signed certificate gets cleaned up after automation

### ISSUE THREAD

**Issue by SerinaTan** [ios-driver/ios-driver#216]
I need to install a self-signed certificate on the ios simulator in order to run some website testing without pop-up warnings of not trusted servers. However, I notice that each time automation runs, the ios-driver will reset the contents of the simulator to default, in which case my certificate will vanish afterwards. I also notice that ios-driver will re-install trustStore after resetting so I am wondering if there is any way I can inject my own certificate in the source trustStore ios-driver is trying to copy. 

If you know anything about the certificate issue, I would really appreciate your help with it.

**Comment by rsalvador** [comment]
If you use 0.6.6 https://dl.dropboxusercontent.com/u/24687868/ios-beta/ios-server-0.6.6-SNAPSHOT.jar you can use the -trustStore flag, i.e: -trustStore TrustStore.sqlite3

**Comment by SerinaTan** [comment]
Thank you so much for your help! It seems that the trustStore flag works well with ios-server-0.6.5-with-dependencies.jar as well.

**Comment by kshlomi** [comment]
Hi, can you please explain how can I create the appropriate TrustStore.sqlite3 file in the first place ?
The various TrustStore.sqlite3 files that I have on my system don't seem to be affected when I manually add a new certificate to the iOS simulator. Thanks!
