### ISSUE TITLE
Cannot open URLs with in-url authorization

### ISSUE THREAD

**Issue by ivanlvasilev** [ios-driver/ios-driver#22]
When try to open url like http://user:pass@somesite.com a warning about fraudulent site appears. This can be disabled through the safari's setting however each time the simulator is started these settings are reset. Can you provide a way to either reuse settings through sessions or disable the warning

"build": {
"revision": "7fc89bb6547d85a55c9ea7caabc50c9343c8be3a",
"time": "20130327-1606",
"version": "0.6.0"
},
"ios": {"simulatorVersion": "6.1"},
"java": {"version": "1.6.0_45"},
"os": {
"arch": "x86_64",
"name": "Mac OS X",
"version": "10.8.3"
},

**Comment by lukeis** [comment]
should be fixed by this commit, thanks @nirvdrum
