### ISSUE TITLE
not able to launch the webapplication on safari simulator due to "can not find command for POST" error

### ISSUE THREAD

**Issue by kbommisetty** [ios-driver/ios-driver#220]
Server status before test execution:
22:28:750 INFO ApplicationStore.<init>  App archive folder:/Users/krishna.bv/Documents/qa/automation/lib/applications
22:29:404 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
22:29:809 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
22:29:828 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
22:29:895 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:4444/inspector/
tests can access the server at http://0.0.0.0:4444/wd/hub
server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/krishna.bv/Documents/qa/automation/lib/applications' for new applications
Archived apps /Users/krishna.bv/Documents/qa/automation/lib/applications
using xcode install : /Applications/Xcode.app
using IOS version 6.1
ios >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=Safari,CFBundleVersion=8536.25
```

2014-02-27 17:22:29.896:INFO::jetty-7.x.y-SNAPSHOT
2014-02-27 17:22:30.037:INFO::Started SelectChannelConnector@0.0.0.0:4444

---

Error while running the test:

23:57:123 WARNING DefaultCommandListener.stderr  2014-02-27 17:23:57.122 instruments[819:507] Failed to connect to local pid watcher service: (os/kern) no access
23:59:247 WARNING IOSServlet.getResponse  132ms.    POST     /session/:sessionId/element
24:00:919 WARNING IOSServlet.getResponse  38062ms.  POST     /session
24:00:939 WARNING IOSServlet.getResponse  1ms.  GET  /session/:sessionId
24:00:971 WARNING IOSServlet.getResponse  1ms.  POST     /session/:sessionId/timeouts
24:00:985 WARNING IOSServlet.getResponse  2ms.  
org.openqa.selenium.WebDriverException: Error processing response.cannot find command for POST, /session/051b511f-21bf-477d-a360-3c9f637978ff/window/current/maximize
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:121)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:57)

**Comment by kbommisetty** [comment]
It is working fine with the latest driver SNAPSHOT 0.6.6.

**Comment by spatchamatla01** [comment]
@kbommisetty can you share the webdriver code to open it in simulator

**Comment by kbommisetty** [comment]
@spatchamatla01 ---

I am on Mac Maverick 10.9.2 version
And Xcode 5.0.2

pre requisite:---

Run  these commands:
1. sudo chmod 666 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator*.sdk/Applications/MobileSafari.app/Info.plist
1. sudo chmod a+rw /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications
2. sudo chmod -R a+rw /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app

Steps i followed:
1. Download latest ios-driver - 0.6.6 snapshot.
2. Start the selenium server using: java -jar ios-server-standalone-latest.jar -port 4444 -simulators
3. Launch the iphone emulator from Xcode

Code Ran:
                DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
                safari.setCapability(IOSCapabilities.SIMULATOR, true);
                //safari.setCapability("sdkVersion", "7.0.3");
                safari.setCapability("variation", "Retina4");
                driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), safari);

Rest of the code is your application specific i.e which website you want to open etc..

**Comment by spatchamatla01** [comment]
@kbommisetty 

im using
Mac Maverick 10.9.2 version
And Xcode 5.1
and java 1.7.0_51

i tried the above steps, but gets the error

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Cannot find /instruments_no_delay/5.1/55044/instruments.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: IOSDualDriver
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Command duration or timeout: 1.37 seconds
Build info: version: '2.40.0', revision: 'fbe29a9', time: '2014-02-19 20:55:11'
System info: host: 'atl-mbp-mac33.local', ip: '10.29.1.164', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'

using the code

DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
        safari.setCapability(IOSCapabilities.SIMULATOR, true);
        safari.setCapability("variation", "Retina4");
        //safari.setCapability("simulatorVersion", "7.1");
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), safari);
        driver.get("http://www.ebay.co.uk/");
        System.out.println(driver.getTitle());

any suggestion?
Really appreciate your time.

Thank You.
