### ISSUE TITLE
IOS 7 : Getting InstrumentsFailedToStartException IOS simulator opens but Safari does not load

### ISSUE THREAD

**Issue by mdiwakar** [ios-driver/ios-driver#221]
java -jar ./ios/ios-server-0.6.6-SNAPSHOT-jar-with-dependencies.jar -port 5560 -simulators
19:46:636 INFO ApplicationStore.<init>  App archive folder:/Users/hudson/Desktop/stt/applications
19:47:729 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled (enabled by -simulators flag): true
Inspector: http://0.0.0.0:5560/inspector/
Tests can access the server at http://0.0.0.0:5560/wd/hub
Server status: http://0.0.0.0:5560/wd/hub/status
Connected devices: http://0.0.0.0:5560/wd/hub/devices/all
Applications: http://0.0.0.0:5560/wd/hub/applications/all
Capabilities: http://0.0.0.0:5560/wd/hub/capabilities/all
Monitoring '/Users/hudson/Desktop/stt/applications' for new applications
Archived apps: /Users/hudson/Desktop/stt/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140129-1350,sha:d698bccd3fade730c95785bd0ddf7e18b0dd3474)
Running on: Mac OS X 10.9 (x86_64)
Using java: 1.7.0_45
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.0.1, build: 51168
Using iOS version 7.0.3
iOS >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=Safari,CFBundleVersion=9537.53,/Users/hudson/.ios-driver/safariCopies/safari-7.0.3.app
```

2014-02-27 20:19:47.816:INFO::jetty-7.x.y-SNAPSHOT
2014-02-27 20:19:47.905:INFO::Started SelectChannelConnector@0.0.0.0:5560
20:05:391 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/hudson/.ios-driver/safariCopies/MobileSafari-7.0.3.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app
20:22:445 WARNING NewSessionNHandler.handle  Couldn't start instrument :Didn't get the capability back.
20:23:814 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/hudson/.ios-driver/safariCopies/MobileSafari-7.0.3.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app
org.uiautomation.ios.server.simulator.InstrumentsFailedToStartException: Didn't get the capability back.
    at org.uiautomation.ios.server.simulator.InstrumentsApple.start(InstrumentsApple.java:145)
    at org.uiautomation.ios.server.InstrumentsBackedNativeIOSDriver.start(InstrumentsBackedNativeIOSDriver.java:44)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:105)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:233)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:52)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:81)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:744)
^[[B^[[B^[[B40:49:266 WARNING IOSServlet.doDelete  org.openqa.selenium.WebDriverException: Error processing response.cannot find command for DELETE, /session/
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.7.0_45'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.7.0_45'
Driver info: driver.version: unknown
#

**Comment by mdiwakar** [comment]
Server status: http://0.0.0.0:5560/wd/hub/status

{
  "class": "org.openqa.selenium.remote.Response",
  "hCode": 678051095,
  "sessionId": null,
  "state": null,
  "status": 0,
  "value": {
    "build": {
      "revision": "d698bccd3fade730c95785bd0ddf7e18b0dd3474",
      "time": "20140129-1350",
      "version": "0.6.6-SNAPSHOT"
    },
    "ios": {"simulatorVersion": "7.0.3"},
    "java": {"version": "1.7.0_45"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.9"
    },
    "state": "success",
    "supportedApps": [{
      "CFBundleDevelopmentRegion": "English",
      "CFBundleDisplayName": "Safari",
      "CFBundleExecutable": "MobileSafari",
      "CFBundleIcons": {"CFBundlePrimaryIcon": {
        "CFBundleIconFiles": [
          "icon-spotlight~ipad.png",
          "icon-table~ipad.png",
          "icon-about~ipad.png",
          "icon-table~ipad.png",
          "icon-spotlight@2x.png",
          "icon-table@2x.png",
          "icon~ipad.png",
          "icon-about@2x.png",
          "icon@2x~iphone.png",
          "icon@2x~ipad.png"
        ],
        "UIPrenderedIcon": true
      }},
      "CFBundleIdentifier": "com.apple.mobilesafari",
      "CFBundleInfoDictionaryVersion": "6.0",
      "CFBundlePackageType": "APPL",
      "CFBundleShortVersionString": "7.0",
      "CFBundleSignature": "????",
      "CFBundleSupportedPlatforms": ["iPhoneSimulator"],
      "CFBundleURLTypes~ipad": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleURLTypes~iphone": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "Radar URL",
          "CFBundleURLSchemes": [
            "rdar",
            "radar"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleURLTypes~ipod": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "Radar URL",
          "CFBundleURLSchemes": [
            "rdar",
            "radar"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleVersion": "9537.53",
      "DTPlatformName": "iphonesimulator",
      "DTSDKName": "iphonesimulator7.0",
      "LSRequiresIPhoneOS": true,
      "MallocBehavior": {"NanoAllocator": false},
      "SBMatchingApplicationGenres": [
        "Productivity",
        "Utilities"
      ],
      "SBUsesNetwork": 3,
      "SafariProductVersion": "7.0",
      "UIApplicationDisableLegacyAutorotationKey": true,
      "UIBackgroundModes": [
        "audio",
        "continuousFallback"
      ],
      "UIBackgroundStyle": "UIBackgroundStyleDarkBlur",
      "UIDeviceFamily": [
        2,
        1
      ],
      "UIHasPrefs": true,
      "UIStatusBarTintParameters": {"UINavigationBar": {"Style": "UIBarStyleDefault"}},
      "UISupportedInterfaceOrientations": [
        "UIInterfaceOrientationPortrait",
        "UIInterfaceOrientationLandscapeLeft",
        "UIInterfaceOrientationLandscapeRight"
      ],
      "UISupportedInterfaceOrientations~ipad": [
        "UIInterfaceOrientationPortrait",
        "UIInterfaceOrientationLandscapeLeft",
        "UIInterfaceOrientationLandscapeRight",
        "UIInterfaceOrientationPortraitUpsideDown"
      ],
      "UIViewControllerBasedStatusBarAppearance": true,
      "applicationPath": "/Users/hudson/.ios-driver/safariCopies/safari-7.0.3.app",
      "device": "iphone",
      "deviceAlt": [
        "ipad",
        "iphone",
        "ipod"
      ],
      "device_Alt": [
        "iphone",
        "ipad"
      ],
      "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=2134756163"},
      "sdkVersion": "7.0.3",
      "sdkVersion_Alt": [
        "5.0",
        "5.1",
        "6.0",
        "6.1"
      ],
      "simulator": true,
      "supportedLanguages": [
        "ar",
        "ca",
        "cs",
        "da",
        "de",
        "el",
        "en",
        "en-GB",
        "es",
        "fi",
        "fr",
        "he",
        "hr",
        "hu",
        "id",
        "it",
        "ja",
        "ko",
        "ms",
        "nl",
        "no",
        "pl",
        "pt",
        "pt-PT",
        "ro",
        "ru",
        "sk",
        "sv",
        "th",
        "tr",
        "uk",
        "vi",
        "zh-CN",
        "zh-TW"
      ],
      "timeHack": false
    }]
  }
}

**Comment by mdiwakar** [comment]
Capabilities:
                  desiredCapabilities =
                          IOSCapabilities.ipad("Safari");
            desiredCapabilities.setCapability("sdkVersion", "7.0.3");
            desiredCapabilities.setCapability(IOSCapabilities.SIMULATOR, true);

**Comment by mdiwakar** [comment]
I built the ios-driver from dev, 
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140303-1635,aha:ad3258d1120e8a119a84aab239394240e5dd305b) it seems I am at least able to launch ios-simulator 
Capabilities desiredCapabilities = IOSCapabilities.ipad("Safari");
but getting the below mentioned error 

014-03-04 16:01:42.330 ScriptAgent[45861:3207] CLTilesManagerClient: init
01:42:332 WARNING DefaultCommandListener.stderr  /var/folders/hj/7tb17lx10g7_0wv_qypythfr   2014-03-04 16:01:42.331 ScriptAgent[45861:3207] CLTilesManagerClient: reconnecting, 0x9780c10
01:54:565 WARNING RemoteIOSWebDriver.<init>  session created but application size=0
java.lang.NullPointerException
    at org.uiautomation.ios.wkrdp.RemoteIOSWebDriver.get(RemoteIOSWebDriver.java:309)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:109)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:231)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.safeStart(NewSessionNHandler.java:82)

detail log: http://pastebin.com/uBhcqxMR

**Comment by freynaud** [comment]
can you try with the latest version, http://ios-driver-ci.ebaystratus.com/userContent/ios-server-standalone-0.6.6-SNAPSHOT.jar
session created but application size=0 means that you have some left over process from previous crashes. A restarts normally solves it for me.

**Comment by mdiwakar** [comment]
@freynaud Thanks, I will try and let you know the results. I did make sure launchd_sim were killed prior to I started ios-server

I am using mac VM, it seems the issue was instruments were crashing and i believe VM were very slow. I did the following

1) Added Safari Option to have clean session capability
2) upgraded to use selenium 2.37 instead of 2.35
3) Increased the TIMEOUT_SEC to 40 from 20 NewSessionHandler.java(configurable param)
4) small change args.add9("-v") to InstrumentsApple.java

with the above mentioned changes I am able to run my tests with less frequent crashes

**Comment by freynaud** [comment]
the simulator is very CPU intensive. When using VM, I need to have at least 4 cores to have anything reliable.
Using a mac mini server with 2 VMs on it gives the best results. 2VMs and it starts to become flaky.

Do you have your changes in a branch or a patch somewhere ? I'll add that to the project.

**Comment by darraghgrace** [comment]
@freynaud : FYI : Increasing the timeout in NewSessionHandler from 20 to 40 secs has eliminated a lot of flakiness for me. The app I test checks location on launch which can take a while.

**Comment by mdiwakar** [comment]
@freynaud  sorry for delayed response, will submit my changes by tomorrow, was busy with launch. do i have to sign CLA?

@darraghgrace   I think timeout should be parameterize in IOSServerConfiguration.java as start up param

**Comment by cavaIV** [comment]
@darraghgrace : I've got the same problem. 
Could you please share your .jar with the 40 sec timeout? Thx :)

**Comment by darraghgrace** [comment]
@cavaIV : You can change private static final long TIMEOUT_SEC = 20; https://github.com/ios-driver/ios-driver/blob/dev/server/src/main/java/org/uiautomation/ios/server/command/uiautomation/NewSessionNHandler.java and rebuild the jar. I will add something so that this is configurable in future

**Comment by freynaud** [comment]
-newSessiontimeoutSec 40 
will increase the timeout to 40 sec.
you can get the jar with the fix here : http://ios-driver-ci.ebaystratus.com/userContent/ios-server-standalone-0.6.6-SNAPSHOT.jar

**Comment by cavaIV** [comment]
Thank you very much :)

**Comment by lolemouine** [comment]
Where do you have to write : 
-newSessiontimeoutSec 40 
????

**Comment by lolemouine** [comment]
Got my answer. Had to call it in the browser, but you have to call : 
newSessionTimeoutSec 40

**Comment by klaask** [comment]
Same issue at my end - any help would be appreciated.

<pre>java -jar /path/to/jar/ios-server-standalone-0.6.6-SNAPSHOT.jar -port 5557 -hub http://xxx.xxx.xxx.xxx:4444/grid/register -host xxx.xxx.xxx.xxx -proxy org.uiautomation.ios.grid.IOSRemoteProxy -folder /path/to/apps -newSessionTimeoutSec 60</pre>

<pre>    @Test
    public void testSafari() throws MalformedURLException, IOException {
        DesiredCapabilities browser = IOSCapabilities.ipad("Safari");
        browser.setCapability(IOSCapabilities.SIMULATOR, true);
        browser.setCapability("simulatorVersion", "7.1");
        browser.setCapability("sdkVersion", "7.1");
        //browser.setCapability("variation", "Retina4");
        testMyPrettyWebsite(browser);
    }</pre>

<pre>10:29:606 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:5557/inspector/
Tests can access the server at http://0.0.0.0:5557/wd/hub
Server status: http://0.0.0.0:5557/wd/hub/status
Connected devices: http://0.0.0.0:5557/wd/hub/devices/all
Applications: http://0.0.0.0:5557/wd/hub/applications/all
Capabilities: http://0.0.0.0:5557/wd/hub/capabilities/all
Monitoring '/path/to/apps' for new applications
Archived apps: /path/to/apps
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140724-1617,sha:96e1d99ab1d959efde0634d2b841a18345016faf)
Running on: Mac OS X 10.9.4 (x86_64)
Using java: 1.8.0_05
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.1.1, build: 55045
Using iOS version 7.1
iOS >= 6.0. Safari and hybrid apps are supported.
Applications :
--------------- 
        CFBundleName=Safari,CFBundleVersion=9537.53,/Users/user/.ios-driver/safariCopies/safari-7.1.app
2014-07-24 17:10:29.768:INFO::jetty-7.x.y-SNAPSHOT
2014-07-24 17:10:29.905:INFO::Started SelectChannelConnector@0.0.0.0:5557
11:33:963 INFO IOSSafariSimulatorManager.copySafariToAllowInstallByInstruments  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/user/.ios-driver/safariCopies/MobileSafari-7.1.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/Mobile
Safari.app
12:37:132 WARNING InstrumentsCommandLine.start  instruments crashed (60 SEC)
12:39:175 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 60sec):Didn't get the capability back.Most likely, instruments crashed at startup.
12:43:830 INFO IOSSafariSimulatorManager.copySafariToAllowInstallByInstruments  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/user/.ios-driver/safariCopies/MobileSafari-7.1.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app
14:46:493 WARNING InstrumentsCommandLine.start  instruments crashed (120 SEC)
14:47:369 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 120sec):Didn't get the capability back.Most likely, instruments crashed at startup.
14:51:548 INFO IOSSafariSimulatorManager.copySafariToAllowInstallByInstruments  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/user/.ios-driver/safariCopies/MobileSafari-7.1.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app
17:54:274 WARNING InstrumentsCommandLine.start  instruments crashed (180 SEC)
17:55:629 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 180sec):Didn't get the capability back.Most likely, instruments crashed at startup.
org.openqa.selenium.SessionNotCreatedException: failed starting after 3retries.Final wait was 240
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'hostname', ip: 'xxx.xxx.xxx.xxx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.4', java.version: '1.8.0_05'
Driver info: driver.version: unknown
        at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:61)
        at org.uiautomation.ios.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:103)
        at org.uiautomation.ios.servlet.IOSServlet.getResponse(IOSServlet.java:151)
        at org.uiautomation.ios.servlet.IOSServlet.process(IOSServlet.java:82)
        at org.uiautomation.ios.servlet.IOSServlet.doPost(IOSServlet.java:57)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
        at org.eclipse.jetty.server.Server.handle(Server.java:352)
        at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
        at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
        at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
        at java.lang.Thread.run(Thread.java:745)</pre>

**Comment by klaask** [comment]
I forgot to mention, that a Launch Daemon starts the node.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Label</key>
        <string>xxx.xxx.ios-driver</string>
        <key>RunAtLoad</key>
        <true/>
        <key>UserName</key>
        <string>user</string>
        <key>ProgramArguments</key>
        <array>
                <string>/usr/bin/java</string>
                <string>-jar</string>
                <string>/path/to/jar/ios-server-standalone-0.6.6-SNAPSHOT.jar</string>
                <string>-port</string>
                <string>5557</string>
                <string>-hub</string>
                <string>http://xxx.xxx.xxx.xxx:4444/grid/register</string>
                <string>-host</string>
                <string>xxx.xxx.xxx.xxx</string>
                <string>-proxy</string>
                <string>org.uiautomation.ios.grid.IOSRemoteProxy</string>
                <string>-folder</string>
                <string>/path/to/apps</string>
                <string>-newSessionTimeoutSec</string>
                <string>60</string>
        </array>
        <key>ServiceDescription</key>
        <string>Selenium Server iOS</string>
        <key>StandardErrorPath</key>
        <string>/path/to/jar/logs/ios-driver-error.log</string>
        <key>StandardOutPath</key>
        <string>/path/to/jar/logs/ios-driver-output.log</string>
        <key>KeepAlive</key>
        <true/>
</dict>
</plist>
```

I just figured out that starting the node at command line works.

**Comment by freynaud** [comment]
Hi,
can you check without using a deamon and check if instruments requests you to enter your password ? I suspect it's a right issue.
When I set the node as a deamon, I need to do the following first :
1)sudo /usr/sbin/DevToolsSecurity -enable
2)add the user to the _developer group
3) set the following keys to true in authorizationdb
"domain" => "system.privilege.taskport",
                    "key" => "allow-root",
                    "value" => "true"
                },
                {
                    "domain" => "com.apple.dt.instruments.process.analysis",
                    "key" => "allow-root",
                    "value" => "true"
                }, {
                    "domain" => "com.apple.dt.instruments.process.kill",
                    "key" => "allow-root",
                    "value" => "true"

**Comment by klaask** [comment]
Thank you for the hints. Unfortunately instruments still crashes if ios-driver is started as a Launch Daemon. But it works removing the key "UserName" out of the job definition, moving the file to ~/Library/LaunchAgents and loading the job as a Launch Agent. I have to evaluate if this fits to our needs.

**Comment by freynaud** [comment]
that's how i launch my daemon, using chef.

```
template '/Library/LaunchDaemons/org.uiautomation.ios-driver.plist' do
      source 'org.uiautomation.ios-driver.plist.erb'
      mode 0644
      owner user
      variables(
          :client_bin => client_bin,
          :working_directory => "/Users/#{user}/",
          :user => user
      )
    end


 service "ios-driver" do
      supports :status => true
      service_name 'org.uiautomation.ios-driver'
      status_command "response=$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:5555/wd/hub/status);return $(($response-200))"
      action :start
    end
```

plist content = 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>StandardOutPath</key>
      <string><%= @working_directory %>/ios-service.out.log</string>
    <key>StandardErrorPath</key>
      <string><%= @working_directory %>/ios-service.err.log</string>
    <key>KeepAlive</key>
      <true/>
    <key>Label</key>
      <string>org.uiautomation.ios-driver</string>
    <key>ProgramArguments</key>
    <array>
      <string><%= @client_bin %></string>
    </array>
    <key>RunAtLoad</key>
      <true/>
    <key>SessionCreate</key>
      <false/>
    <key>WorkingDirectory</key>
      <string><%= @working_directory %></string>
  </dict>
</plist>

```

**Comment by SidBala** [comment]
@freynaud I am trying to run simulators inside VMs at the moment. Having a bunch of hangs and timeout issues. I've given my VMs 4 cores - the maximum I have on my mac - I am still hitting these issues.

What sort of issues were you facing when you tried this? When you say:

> 2VMs and it starts to become flaky

What exactly do you mean by flaky? Do you have the simulator boot up and then crash or does it just not boot up? Does it crash mid-way when it runs tests?

If you could shed any light on this, I would be super-grateful.
