### ISSUE TITLE
-beta and onDeviceAdded

### ISSUE THREAD

**Issue by ainthek** [ios-driver/ios-driver#222]
installed from:
brew info libimobiledevice
on OSX 10.9.2

getting error: 
47:03:059 INFO DeviceStore.onDeviceAdded  new device detected (3e0e3)uuu’s iPad
dyld: lazy symbol binding failed: Symbol not found: _instproxy_client_start_service
  Referenced from: /var/folders/cs/7zzbk12j0k14ykd00r62l3jc0000gn/T/jna--1081313245/jna6795739392080701973.tmp
  Expected in: /usr/local/lib/libimobiledevice.dylib

dyld: Symbol not found: _instproxy_client_start_service
  Referenced from: /var/folders/cs/7zzbk12j0k14ykd00r62l3jc0000gn/T/jna--1081313245/jna6795739392080701973.tmp
  Expected in: /usr/local/lib/libimobiledevice.dylib

**Comment by freynaud** [comment]
Can you try with the latest ? I fixed the loading of the libs I think.
http://ios-driver-ci.ebaystratus.com/userContent/ios-server-standalone-0.6.6-SNAPSHOT.jar

**Comment by darraghgrace** [comment]
@ainthek : Is this still an issue for you? Closing, please re-open if you are still having problems
