### ISSUE TITLE
Tests are failing after upgrading to Xcode 7.1 

### ISSUE THREAD

**Issue by pshakya** [ios-driver/ios-driver#226]
Tests are failing after upgrading to Xcode 7.1 with following message.

Cannot find /instruments_no_delay/5.1/55044/instruments.

Run Details:
35:57:421 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:4444/inspector/
Tests can access the server at http://0.0.0.0:4444/wd/hub
Server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all

Build info: ios-driver 0.6.6-SNAPSHOT (built:20140311-1046,sha:fb8461c6971bbe7498273fae251d210664913812)
Running on: Mac OS X 10.9.2 (x86_64)
Using java: 1.7.0_25
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.1, build: 55044
Using iOS version 7.1
iOS >= 6.0. Safari and hybrid apps are supported.

**Comment by rsalvador** [comment]
This commit fixes this: https://github.com/ios-driver/ios-driver/commit/ad328a7d34406829076ce86b73c82bf4076a946f

**Comment by pshakya** [comment]
Thanks for immediate response and quick fix on this issue!
