### ISSUE TITLE
Null sessionId - not able to use Inspector with Xcode 5.1 IOS 7.1

### ISSUE THREAD

**Issue by gitnava** [ios-driver/ios-driver#228]
I just got the latest code from the dev branch which should have the fix for the 7.1 issue (ios-server-standalone-0.6.6-SNAPSHOT.jar) and I am not able to start the ios-server with the -simulators parameter.

Error: Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -simulators

If I remove the -simulators (By looking at the code, this parameter has been removed as designed), I am able to start the server. However, I am not able to Inspect since the sessionId is NULL. URL looks like http://0.0.0.0:5555/inspector/session//home. 

What would the reason of a null sessionId??
Any help is really appreciated.

Thank you

**Comment by freynaud** [comment]
did you start the app before launching the inspector ?

**Comment by gitnava** [comment]
Sure, started the app and was invoking the inspector on breakpoint.
So I got the latest dev code again and reset everything.
Everything looks good now. It probably was my mistake. 

Thanks for checking:)

**Comment by freynaud** [comment]
cool. Please reopen if you see the issue again.
