### ISSUE TITLE
Timing out with large JS execution

### ISSUE THREAD

**Issue by nirvdrum** [ios-driver/ios-driver#23]
I have a need to serialize the DOM to JSON in mobile Safari and do so through "execute_script".  It may take a while to process for large pages and result in a large response payload.  Currently I'm seeing the client time out in such cases with the following response payload:

<pre>
{"message"=>"timeout waiting for a response for request id : 15\nBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'\nSystem info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.7.0_21'\nDriver info: driver.version: unknown", "screen"=>nil, "class"=>"org.openqa.selenium.WebDriverException", "stackTrace"=>[{"fileName"=>"DefaultWebKitResponseFinder.java", "lineNumber"=>52, "className"=>"org.uiautomation.ios.wkrdp.internal.DefaultWebKitResponseFinder", "methodName"=>"startSearch"}, {"fileName"=>"ResponseFinderList.java", "lineNumber"=>55, "className"=>"org.uiautomation.ios.wkrdp.ResponseFinderList$1", "methodName"=>"run"}, {"fileName"=>"Thread.java", "lineNumber"=>722, "className"=>"java.lang.Thread", "methodName"=>"run"}]}
</pre>

**Comment by freynaud** [comment]
I'll work on the JS part. About the getting the DOM part. the WKRDP is design to do debugging. It has functions to pull the DOM, the JS etc. I( you)  can add an extension that takes advantage of the protocol if needed.
