### ISSUE TITLE
Not able to query in JQM search box.

### ISSUE THREAD

**Issue by lohithCTA** [ios-driver/ios-driver#232]
Hi All,

```
We have a scenario, where user has to enter the query data in to the JQM search box and click on search button in iPad keyboard.
```

We are able to enter the data using below code.
driver.findElement( By.xpath( "//input[@rn=XXX" ) ).sendKeys("Benchmar*");

and also click on Search button which will bring up the iPad keyboard, below is the code to TAP search button.
driver.findElement( By.xpath( "//input[@rn=XXX" ) ).sendKeys(Keys.ENTER);

The issue arises in second line, where it will erase the queried data and makes the click on Search button. So it will queried for blank search.

Please let me know any one across JQM search issue.

Thanks,
Lohith

**Comment by freynaud** [comment]
there is no enter key on a mobile. You should click on the "Search" button directly. 
Let me know if that solves your issue

**Comment by lohithCTA** [comment]
Hi Frey,

```
 Thanks for the feedback.
```

When running, it enters the data in to the JQM search box and minimizes the keypad.

Please share me the code if you have any for clicking on Search button in the keypad.

Thanks,
Lohith

**Comment by freynaud** [comment]
do you have a page I can use to test ?

To get the locator of the button on the keyboard, you can you the inspector. 
The keyboard is a native element, so driver.switchTo("NATIVE"); driver.findElement(locatorSearch).click();

**Comment by lohithCTA** [comment]
Hey i will not be able to provide the Application URL, sorry.

Here is the similar Search box i found. Could you plz try for this.

http://www.w3schools.com/jquerymobile/tryit.asp?filename=tryjqmob_forms_search

Thanks,
Lohith

**Comment by freynaud** [comment]
driver.get("http://www.w3schools.com/jquerymobile/tryit.asp?filename=tryjqmob_forms_search");

// you don't need that on a normal ( without frames ) page
    driver.switchTo().frame("iframeResult");

```
WebElement element = driver.findElement(By.id("search"));
element.sendKeys("test");
```

// switch to native to get hold of the keyboard
    driver.switchTo().window("Native");
    WebElement searchButton = driver.findElement(By.name("Search"));
    searchButton.click();
// and back to web
    driver.switchTo().window("Web");

// continue tests

**Comment by lohithCTA** [comment]
Thank you very much Frey.

**Comment by lohithCTA** [comment]
Hi Frey, 
 I tried your code, its working fine for that particular site.

But i have one more issue. In JQM search control after entering the sendkeys, it will minimizes the keypad. So in the next line of code it switch to Native and  click on Search button, as keypad is minimized gives error saying "NO such element" found.

This happens only in our application. Is there any command which can bring up the Keypad, so that i can make click on required button?

Below is code.

// enter the data in Search control
WebElement element2 = driver.findElement(By.xpath("//input[@rn = 'Accounts_SearchInput']"));
element2.sendKeys("FinanceOne Corporation");
======> It will minimize the Keypad
// Switch to Native  
driver.switchTo().window("Native");
// click on Search button
WebElement searchButton1 = driver.findElement(By.name("Search"));
searchButton1.click();

Thanks,
Lohith

**Comment by freynaud** [comment]
if you click on the search field, it should make the keyboard appear again.
