### ISSUE TITLE
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -simulators

### ISSUE THREAD

**Issue by ghost** [ios-driver/ios-driver#239]
OS X 10.9.2 (13C64)

Java Version

Ashwajits-MacBook-Pro:imp ashwajitthukral$ java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

Ashwajits-MacBook-Pro:imp ashwajitthukral$ xcodebuild -showsdks
OS X SDKs:
    OS X 10.8                       -sdk macosx10.8
    OS X 10.9                       -sdk macosx10.9

iOS SDKs:
    iOS 7.1                         -sdk iphoneos7.1

iOS Simulator SDKs:
    Simulator - iOS 6.1             -sdk iphonesimulator6.1
    Simulator - iOS 7.1             -sdk iphonesimulator7.1

I am getting this error message when i run the iOS server command with -simulators

$ java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut InternationalMountains.app -port 4444 -simulators

Ashwajits-MacBook-Pro:imp ashwajitthukral$ java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut InternationalMountains.app -port 4444 -simulators
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -simulators
    at com.beust.jcommander.JCommander.parseValues(JCommander.java:723)
    at com.beust.jcommander.JCommander.parse(JCommander.java:275)
    at com.beust.jcommander.JCommander.parse(JCommander.java:258)
    at com.beust.jcommander.JCommander.<init>(JCommander.java:203)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:65)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:70)

When i try to run the iOS server command without -simulators

Ashwajits-MacBook-Pro:imp ashwajitthukral$ java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut InternationalMountains.app -port 4444
18:34:528 INFO ApplicationStore.<init>  App archive folder:/Users/ashwajitthukral/Desktop/IMP/applications
true
18:34:571 WARNING AppleLanguage.create  crazy-language isn't recognized. Please file a bug on github. You won't be able to start the app in that language.
18:35:792 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:4444/inspector/
Tests can access the server at http://0.0.0.0:4444/wd/hub
Server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/ashwajitthukral/Desktop/IMP/applications' for new applications
Archived apps: /Users/ashwajitthukral/Desktop/IMP/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140326-1201,sha:69eb457e39da8babb88070a47009ab8dceba0c6d)
Running on: Mac OS X 10.9.2 (x86_64)
Using java: 1.7.0_51
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.1, build: 55044
Using iOS version 7.1
iOS >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=InternationalMountains,CFBundleVersion=1.1,/Users/ashwajitthukral/Desktop/IMP/InternationalMountains.app
CFBundleName=Safari,CFBundleVersion=8536.25,/Users/ashwajitthukral/.ios-driver/safariCopies/safari-6.1.app
CFBundleName=Safari,CFBundleVersion=9537.53,/Users/ashwajitthukral/.ios-driver/safariCopies/safari-7.1.app
```

2014-04-03 00:18:35.898:INFO::jetty-7.x.y-SNAPSHOT
2014-04-03 00:18:35.957:INFO::Started SelectChannelConnector@0.0.0.0:4444

http://localhost:4444/wd/hub/status

{
  "class": "org.openqa.selenium.remote.Response",
  "hCode": 899565349,
  "sessionId": null,
  "state": null,
  "status": 0,
  "value": {
    "build": {
      "revision": "69eb457e39da8babb88070a47009ab8dceba0c6d",
      "time": "20140326-1201",
      "version": "0.6.6-SNAPSHOT"
    },
    "ios": {"simulatorVersion": "7.1"},
    "java": {"version": "1.7.0_51"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.9.2"
    },
    "state": "success",
    "supportedApps": [
      {
        "CFBundleDevelopmentRegion": "en",
        "CFBundleExecutable": "InternationalMountains",
        "CFBundleIconFile": "Icon.png",
        "CFBundleIdentifier": "com.yourcompany.InternationalMountains",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleName": "InternationalMountains",
        "CFBundlePackageType": "APPL",
        "CFBundleSignature": "????",
        "CFBundleSupportedPlatforms": ["iPhoneSimulator"],
        "CFBundleVersion": "1.1",
        "DTPlatformName": "iphonesimulator",
        "DTSDKName": "iphonesimulator5.1",
        "LSRequiresIPhoneOS": true,
        "NSMainNibFile": "MainWindow",
        "UIDeviceFamily": [1],
        "applicationPath": "/Users/ashwajitthukral/Desktop/IMP/InternationalMountains.app",
        "device": "iphone",
        "deviceAlt": [
          "iphone",
          "ipod"
        ],
        "device_Alt": [
          "iphone",
          "ipad"
        ],
        "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=-674408620"},
        "sdkVersion": "7.1",
        "sdkVersion_Alt": [
          "5.0",
          "5.1",
          "6.0",
          "6.1"
        ],
        "simulator": true,
        "supportedLanguages": [
          "en",
          "fr",
          "zh-Hant",
          "unknown"
        ],
        "timeHack": false
      },
      {
        "CFBundleDevelopmentRegion": "English",
        "CFBundleDisplayName": "Safari",
        "CFBundleExecutable": "MobileSafari",
        "CFBundleIcons": {"CFBundlePrimaryIcon": {
          "CFBundleIconFiles": [
            "icon~iphone.png",
            "icon~ipad.png",
            "icon@2x~iphone.png",
            "icon@2x~ipad.png",
            "icon-table.png",
            "icon-table@2x.png",
            "icon-spotlight~ipad.png",
            "icon-spotlight@2x~ipad.png"
          ],
          "UIPrenderedIcon": true
        }},
        "CFBundleIdentifier": "com.apple.mobilesafari",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "6.0",
        "CFBundleSignature": "????",
        "CFBundleSupportedPlatforms": ["iPhoneSimulator"],
        "CFBundleURLTypes~ipad": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          }
        ],
        "CFBundleURLTypes~iphone": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "Radar URL",
            "CFBundleURLSchemes": [
              "rdar",
              "radar"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          }
        ],
        "CFBundleURLTypes~ipod": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "Radar URL",
            "CFBundleURLSchemes": [
              "rdar",
              "radar"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          }
        ],
        "CFBundleVersion": "8536.25",
        "DTPlatformName": "iphonesimulator",
        "DTSDKName": "iphonesimulator6.1",
        "LSRequiresIPhoneOS": true,
        "SBMatchingApplicationGenres": [
          "Productivity",
          "Utilities"
        ],
        "SBUsesNetwork": 3,
        "SafariProductVersion": "6.0",
        "UIApplicationDisableLegacyAutorotationKey": true,
        "UIBackgroundModes": [
          "audio",
          "continuousFallback"
        ],
        "UIDeviceFamily": [
          1,
          2
        ],
        "UIHasPrefs": true,
        "UISupportedInterfaceOrientations": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight"
        ],
        "UISupportedInterfaceOrientations~ipad": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight",
          "UIInterfaceOrientationPortraitUpsideDown"
        ],
        "applicationPath": "/Users/ashwajitthukral/.ios-driver/safariCopies/safari-6.1.app",
        "device": "iphone",
        "deviceAlt": [
          "iphone",
          "ipod",
          "ipad"
        ],
        "device_Alt": [
          "iphone",
          "ipad"
        ],
        "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=707870789"},
        "sdkVersion": "7.1",
        "sdkVersion_Alt": [
          "5.0",
          "5.1",
          "6.0",
          "6.1"
        ],
        "simulator": true,
        "supportedLanguages": [
          "ar",
          "ca",
          "cs",
          "da",
          "de",
          "el",
          "en",
          "en-GB",
          "es",
          "fi",
          "fr",
          "he",
          "hr",
          "hu",
          "id",
          "it",
          "ja",
          "ko",
          "ms",
          "nl",
          "no",
          "pl",
          "pt",
          "pt-PT",
          "ro",
          "ru",
          "sk",
          "sv",
          "th",
          "tr",
          "uk",
          "vi",
          "zh-CN",
          "zh-TW"
        ],
        "timeHack": false
      },
      {
        "CFBundleDevelopmentRegion": "English",
        "CFBundleDisplayName": "Safari",
        "CFBundleExecutable": "MobileSafari",
        "CFBundleIcons": {"CFBundlePrimaryIcon": {
          "CFBundleIconFiles": [
            "icon-spotlight~ipad.png",
            "icon-table~ipad.png",
            "icon-about~ipad.png",
            "icon-table~ipad.png",
            "icon-spotlight@2x.png",
            "icon-table@2x.png",
            "icon~ipad.png",
            "icon-about@2x.png",
            "icon@2x~iphone.png",
            "icon@2x~ipad.png"
          ],
          "UIPrenderedIcon": true
        }},
        "CFBundleIdentifier": "com.apple.mobilesafari",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "7.0",
        "CFBundleSignature": "????",
        "CFBundleSupportedPlatforms": ["iPhoneSimulator"],
        "CFBundleURLTypes~ipad": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          },
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "MobileSafari Tab URL",
            "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
          }
        ],
        "CFBundleURLTypes~iphone": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "Radar URL",
            "CFBundleURLSchemes": [
              "rdar",
              "radar"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          },
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "MobileSafari Tab URL",
            "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
          }
        ],
        "CFBundleURLTypes~ipod": [
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "Web App URL",
            "CFBundleURLSchemes": ["webclip"]
          },
          {
            "CFBundleURLName": "Web site URL",
            "CFBundleURLSchemes": [
              "http",
              "https"
            ]
          },
          {
            "CFBundleURLName": "Radar URL",
            "CFBundleURLSchemes": [
              "rdar",
              "radar"
            ]
          },
          {
            "CFBundleURLName": "FTP URL",
            "CFBundleURLSchemes": ["ftp"]
          },
          {
            "CFBundleURLName": "Web Search URL",
            "CFBundleURLSchemes": ["x-web-search"]
          },
          {
            "CFBundleURLIsPrivate": true,
            "CFBundleURLName": "MobileSafari Tab URL",
            "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
          }
        ],
        "CFBundleVersion": "9537.53",
        "DTPlatformName": "iphonesimulator",
        "DTSDKName": "iphonesimulator7.1",
        "LSRequiresIPhoneOS": true,
        "MallocBehavior": {"NanoAllocator": false},
        "SBMatchingApplicationGenres": [
          "Productivity",
          "Utilities"
        ],
        "SBUsesNetwork": 3,
        "SafariProductVersion": "7.0",
        "UIApplicationDisableLegacyAutorotationKey": true,
        "UIBackgroundModes": [
          "audio",
          "continuousFallback"
        ],
        "UIBackgroundStyle~iphone": "UIBackgroundStyleDarkBlur",
        "UIDeviceFamily": [
          1,
          2
        ],
        "UIHasPrefs": true,
        "UIStatusBarTintParameters": {"UINavigationBar": {"Style": "UIBarStyleDefault"}},
        "UISupportedInterfaceOrientations": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight"
        ],
        "UISupportedInterfaceOrientations~ipad": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight",
          "UIInterfaceOrientationPortraitUpsideDown"
        ],
        "UIViewControllerBasedStatusBarAppearance": true,
        "applicationPath": "/Users/ashwajitthukral/.ios-driver/safariCopies/safari-7.1.app",
        "device": "iphone",
        "deviceAlt": [
          "iphone",
          "ipod",
          "ipad"
        ],
        "device_Alt": [
          "iphone",
          "ipad"
        ],
        "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=2134756163"},
        "sdkVersion": "7.1",
        "sdkVersion_Alt": [
          "5.0",
          "5.1",
          "6.0",
          "6.1"
        ],
        "simulator": true,
        "supportedLanguages": [
          "ar",
          "ca",
          "cs",
          "da",
          "de",
          "el",
          "en",
          "en-GB",
          "es",
          "fi",
          "fr",
          "he",
          "hr",
          "hu",
          "id",
          "it",
          "ja",
          "ko",
          "ms",
          "nl",
          "no",
          "pl",
          "pt",
          "pt-PT",
          "ro",
          "ru",
          "sk",
          "sv",
          "th",
          "tr",
          "uk",
          "vi",
          "zh-CN",
          "zh-TW"
        ],
        "timeHack": false
      }
    ]
  }
## }

I am new to iOS driver, Could you please tell me why the iOS server command is not working if i put -simulators at the end of the command.

Thanks in advance

**Comment by greg-dennis** [comment]
That flag is no longer needed to drive the simulator. ios-driver will
detect the simulator automatically.

**Comment by ghost** [comment]
Thanks Greg,

My iPhone simulator with International Mountains app will not launch automatically if i run the iOS server command without the -simulators flag. 

> > $ java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut 
> > InternationalMountains.app -port 4444

Do i need to open the iPhone simulator with International Mountains app manually after running the ios server command?

Thanks

Regards,
Ashwajit Thukral

**Comment by greg-dennis** [comment]
The app doesn't start until the request comes in, I believe.

**Comment by ghost** [comment]
Thanks Greg for helping me.

Okay i got your point for app but why the ios server command is not launching or detecting the iPhone simulator?

**Comment by greg-dennis** [comment]
You may need to run the permissions.sh script first:
  cd common/src/main/resources
  ./permissions.sh

**Comment by ghost** [comment]
Do we have any proper documentation of iOS driver for newbies? Other than iOS driver website.

Thanks

**Comment by ghost** [comment]
Can anyone provide me the full Java code for InternationalMountains app including all import files.

I am new to Java and don't know how to get import files

I need all the import files for the below code:

public static void main(String[] args) throws MalformedURLException {
    // create a selenium desiredCapabilities object with the right values.
    DesiredCapabilities cap = IOSCapabilities.iphone("InternationalMountains", "1.1");
    // start the application
    RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), cap);

```
// check that the 9 mountains of the app are there.
List<Weblement> cells = driver.findElements(By.className("UIATableCell"));
Assert.assertEquals(9,cells.size());


// get the 1st mountain
WebElement first = cells.get(0);
first.click();

// take a screenshot using the normal selenium api.
TakesScreenshot screen =(TakesScreenshot)new Augmenter().augment(driver);
File ss = new File("screenshot.png");
screen.getScreenshotAs(OutputType.FILE).renameTo(ss);
System.out.println("screenshot take :"+ss.getAbsolutePath());

// access the content
By selector = By.xpath("//UIAStaticText[contains(@name,'climbed')]");
WebElement text = driver.findElement(selector);
System.out.println(text.getAttribute("name"));

// end the test
driver.quit();
}
```

**Comment by darraghgrace** [comment]
You will probably need something like this.
import junit.framework.Assert;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.Augmenter;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.uiautomation.ios.IOSCapabilities;

import java.io.File;
import java.net.URL;
import java.util.List;

**Comment by ghost** [comment]
Thanks Grace for the help.

I tried with the imports you have given me.

Getting error related to Assert.
It's deprecated, can you help me what i have to do now?
