### ISSUE TITLE
java.net.SocketException: Protocol family unavailable

### ISSUE THREAD

**Issue by sq-maros** [ios-driver/ios-driver#240]
This error only happens when I spawn the jar as a Node.js child.

The error is [`java.net.SocketException: Protocol family unavailable`](https://github.com/ios-driver/ios-driver/blob/3b5d18ea6e769d30d64fb40a9a53ad1561400f68/server/src/main/java/org/uiautomation/ios/wkrdp/internal/SimulatorProtocolImpl.java#L58)

selenium-test.js:

```
var spawn = require('child_process').spawn;

var selenium = spawn('java', ['-jar', './lib/ios-server-standalone-0.6.6-SNAPSHOT.jar', '-port', '4444']);
selenium.stderr.setEncoding('utf8');
selenium.stderr.on('data', function (data){
  console.log(data);
});
```

webdriverjs-test.js ([webdriverjs](https://github.com/camme/webdriverjs))

```
var webdriverjs = require('webdriverjs');
var options = {
    desiredCapabilities: {
        browserName: 'safari',
        platform: 'OS X 10.9',
        version: '7.1',
        device: 'iphone'
    }
};

webdriverjs
  .remote(options)
  .init()
  .end();
```

**Comment by bijoyv** [comment]
it requires IPv6 configured on your mac
