### ISSUE TITLE
Travis CI broken for 4 months

### ISSUE THREAD

**Issue by csnover** [ios-driver/ios-driver#245]
Last successful build was [build 225](https://travis-ci.org/ios-driver/ios-driver/builds/13717986) in November 2013.

**Comment by nicegraham** [comment]
it was at least in part due to this... 
https://github.com/travis-ci/travis-ci/issues/1292#issuecomment-39809532

**Comment by freynaud** [comment]
I'm not using travis anymore.
Changes pushed to the dev brnahc are published here http://ios-driver-ci.ebaystratus.com/
