### ISSUE TITLE
Exception executing JavaScript

### ISSUE THREAD

**Issue by nirvdrum** [ios-driver/ios-driver#25]
I see an exception in the server log sometimes when running "execute_javascript."  This doesn't manifest as a client error immediately, but it's in the logs nonetheless:

<pre>
java.lang.NullPointerException
    at org.uiautomation.ios.wkrdp.message.BaseIOSWebKitMessage.<init>(BaseIOSWebKitMessage.java:17)
    at org.uiautomation.ios.wkrdp.message.MessageFactory.create(MessageFactory.java:37)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.process(DefaultMessageHandler.java:73)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.access$000(DefaultMessageHandler.java:31)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler$1.run(DefaultMessageHandler.java:64)
</pre>

**Comment by freynaud** [comment]
is it for large messages by any chance ? the WKRDP implementation I use only implements the <8K messages.

**Comment by nirvdrum** [comment]
I can't be certain of the payload size, but it's probably bigger than 8K.  It seemed to be paired with the time out issue I was seeing in #23.

**Comment by ghost** [comment]
I'm having this issue when I try and pull back the page source (lots of javascript + content on the page). I see this issue has been closed however it appears that the payload of 8k hasn't changed? Any idea how to work around this issue?

**Comment by nirvdrum** [comment]
Did you build from the dev branch?  As far as I know, this hasn't made its way into an actual release yet.

**Comment by ghost** [comment]
I'm using the released version. I guess I can install eclipse/ maven/ etc... and muddle my way through building the dev branch. Any ideas when we'll get an updated release build?

**Comment by lukeis** [comment]
no need to install eclipse... just need maven, then after you clone and checkout dev, just run `mvn clean package -DskipTests=true`  <- you don't want to run the tests ;)

**Comment by ghost** [comment]
I had an error when I did this. Just using deduction from this I removed the libimobile-java from the pom.xml file (modules). (there's nothing in the libimobile-java folder after I did a "git clone https://github.com/ios-driver/ios-driver.git").

**Comment by lukeis** [comment]
it's a submodule... you'd need to run `git submodule update --init`  after initial clone

**Comment by ghost** [comment]
Getting Permission denied (publickey). Every time it tries to get libimobile-java.git

**Comment by ghost** [comment]
I basically cloned the libimobile-java.git and dropped it in the folder. After updating to java sdk 1.7 it appears I'm finally in business. Thanks for the help.

**Comment by nirvdrum** [comment]
I think the problem is you need to have an SSH key set up in GitHub to do the submodule clone.  But what you did should be fine as well, so long as you don't commit it :-)
