### ISSUE TITLE
SendKeys() does not only send keys but also click 'Done'

### ISSUE THREAD

**Issue by cavaIV** [ios-driver/ios-driver#251]
If I sendkeys() to write something into a textbox the ios driver automatically clicks keyboard Done afterwards instead of simply hiding the keyboard.

This sometimes causes unexpected page updates.

**Comment by julianhaslinger** [comment]
As for the Selenium API, the SendKeys method should only send keys to a web element. However, the ios-driver implementation seems to do a little bit more (clicks "Done"). This action should not be in the scope of the method SendKeys. In my opinion, you should leave this decision (whether or not "Done" should be clicked) to the users of the different Selenium implementations.

**Comment by freynaud** [comment]
makes sense. Would you be happy with "clicks done by default, and default can be changed".
I you don't remove the keyboard after sendKeys by default, you have most script failing as they won't be able to interact with a page without removing the keyboard first.

**Comment by cavaIV** [comment]
Yeah clicking done by a changeable default would be nice

**Comment by azaytsev** [comment]
A Capability has been added to allow a user to keep the keyboard on the screen after sendKeys() command has been issues. To show/hide keyboard the following capability can be used

```
IOSCapabilities caps = IOSCapabilities.iphone("Safari");
caps.setCapability(IOSCapabilities.SHOW_KEYBOARD_AFTER_CLICK_AND_TYPE, true);
```

The keyboard will be hidden by default unless that capability is set to true.
