### ISSUE TITLE
Exception - no devices available. Known devices: [Simulator[in use by ios-driver]]

### ISSUE THREAD

**Issue by mitulgohel** [ios-driver/ios-driver#252]
Hi Sir,

I am trying to run test script but getting error "no devices available. Known devices: [Simulator[in use by ios-driver]]". Was working fine two days a go:
    public static void main(String[] args) throws Exception {
        DesiredCapabilities safari = IOSCapabilities.ipad("Safari");
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), safari);
        driver.get("http://google.com/");
        ((Rotatable)new Augmenter().augment(driver)).rotate(ScreenOrientation.LANDSCAPE);
        driver.quit();
    }  
    }

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: {simulator=true, timeHack=false, locale=en_GB, CFBundleName=Safari, device=ipad, language=en} no devices available.
    Known devices: [Simulator[in use by ios-driver]]
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'

Running latest snapshot 0.6.6-SNAPSHOT.

Xcode Version 5.1.1

System requirements for OSX:
OS X SDKs:
    OS X 10.8                       -sdk macosx10.8
    OS X 10.9                       -sdk macosx10.9
iOS SDKs:
    iOS 7.1                         -sdk iphoneos7.1
iOS Simulator SDKs:
    Simulator - iOS 7.1             -sdk iphonesimulator7.1

Please Help. Not sure what can be the issue and why is it not working now. 

Thank you,

**Comment by darraghgrace** [comment]
Make sure IOS Simulator and instruments are not running.
There were some commits for xcode 5.1.1 support recently I am not sure if these made it into the latest 0.6.6-SNAPSHOT- https://github.com/ios-driver/ios-driver/commit/34596894c11161e9ffee7ab4763d3a3c9f580fa6
Can you build the dev branch and try again? See this issue for build instructions - https://github.com/ios-driver/ios-driver/issues/249

**Comment by mitulgohel** [comment]
It worked! Thank you!

**Comment by mitulgohel** [comment]
Do you know if I can run the same script on real device? Or do you have any documents that can tell me how to run it on real device?

**Comment by darraghgrace** [comment]
Have a look at this issue - https://github.com/ios-driver/ios-driver/pull/237 and here
https://github.com/ios-driver/ios-driver/issues/168
