### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: failed starting after 3retries.Final wait was 60 Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.7.0_55' 

### ISSUE THREAD

**Issue by gobim** [ios-driver/ios-driver#253]
I have started my first test in mobile safari and finished the final setup. while starting testing java code runing without any error.
I have loaded simulator with blank page or with only the about:blank button or the one with Disney etc bookmarks or sometimes its suddenly quit often before safari launch

I have started server with
java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -port 4444

Using below java code
DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
safari.setCapability(IOSCapabilities.SIMULATOR, true);
safari.setCapability("simulatorVersion", "7.0.3");
safari.setCapability("sdkVersion", "7.0.3");
safari.setCapability("variation", "Retina4");
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5544/wd/hub"), safari);
driver.get("http://hp.mobileweb.ebay.co.uk/home");
WebElement search = driver.findElement(By.id("srchDv"));
search.sendKeys("ipod");
search.submit();

this will be ended with org.openqa.selenium.SessionNotCreatedException: failed starting after 3retries.Final wait was 60
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.7.0_55'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.7.0_55'
Driver info: driver.version: unknown
....................

In terminal received the below error:

Instruments : Instruments Accepted Command
02:26:849 WARNING DefaultCommandListener.stderr /var/folders/61/7n0c9s_j1cnf31gj40hk5298 Instruments : Preparing To Start Trace
02:26:849 WARNING DefaultCommandListener.stderr /var/folders/61/7n0c9s_j1cnf31gj40hk5298 Instruments : Starting Instrument(s)
02:47:287 WARNING InstrumentsApple.start instruments crashed (20 SEC)
02:49:084 WARNING NewSessionNHandler.safeStart Instruments failed to start in the allocated time ( 20sec):Didn't get the capability back.Most likely, instruments crashed at startup.
02:49:950 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/labuser/.ios-driver/safariCopies/MobileSafari-7.0.3.app /Applications/Xcode 2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app

**Comment by darraghgrace** [comment]
Are you running the test with the simulator or instruments already open? Make sure both are closed before running your tests.

**Comment by gobim** [comment]
Now i am able to run with Simulator and facing the below issue while running on real device.

error: uncaughtException: connect ECONNREFUSED date=Mon May 12 2014 14:38:01 GMT+0530 (IST), pid=3581, uid=501, gid=20, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.10.26, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --address, 172.196.16.36, --port, 7777, --command-timeout, 7200, --safari, --browser-name, Safari, --udid, 977fa83cf6f1b7bd72f7e69a2ae956f6af06c, --default-device], rss=52789248, heapTotal=56160000, heapUsed=18933560, loadavg=[1.3798828125, 1.57373046875, 1.96923828125], uptime=30371, trace=[column=11, file=net.js, function=errnoException, line=904, method=null, native=false, column=19, file=net.js, function=Object.afterConnect [as oncomplete], line=895, method=afterConnect [as oncomplete], native=false], stack=[Error: connect ECONNREFUSED,     at errnoException (net.js:904:11),     at Object.afterConnect [as oncomplete](net.js:895:19)]

Suspect the issue because of the below:
While running  ios_webkit_debug_proxy -c UDID:7777 -d

ss.add_fd(3)
select_port() failed
ss.recv fd=3 len=978
ss.add_server_fd(4)
ss.add_fd(6)
wi.send_packet[245]:
 00 00 00 F1 62 70 6C 69 73 74 30 30 D1 01 02 5F 10 12 57  ....bplist00..._..W
 49 52 46 69 6E 61 6C
How to fix this select_port failed issue?

**Comment by freynaud** [comment]
Hello,
this doesn't seem to be ios-driver related.You're using appium, which is not related to ios-driver.
Did you follow the steps here ? : http://ios-driver.github.io/ios-driver/

**Comment by jigtest** [comment]
The safari browser does not open even though the simulator launches.

The configuration as shown on terminal by running the command - 
java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -newSessionTimeoutSec 40 -port 5555

Running on: Mac OS X 10.10 (x86_64)
Using java: 1.8.0_45
Using Xcode install: /Applications/Xcode.app
Using instruments: version:6.3.2, build: 57082
Using iOS version 8.3
iOS >= 6.0. Safari and hybrid apps are supported.
Applications :
CFBundleName=Safari,CFBundleVersion=600.1.4,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/Applications/MobileSafari.app

The java code I used is as follows:
DesiredCapabilities caps = IOSCapabilities.iphone("Safari");
caps.setCapability(IOSCapabilities.SIMULATOR, true);
caps.setBrowserName("safari");

RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), caps);
driver.get("http://www.google.com/");

The following lines are displayed on terminal:

59:05:611 WARNING InstrumentsCommandLine.start  instruments crashed (40 SEC)
59:06:040 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 40sec):Didn't get the capability back.Most likely, instruments crashed at startup.
59:06:476 WARNING NewSessionNHandler.safeStart  app has crashed at startup :normal
59:06:482 INFO IOSServerManager.findAllMatchingApplications  Safari application requested for SDK version: 8.3

Any help from anyone would be appreciated.
