### ISSUE TITLE
Start server from script instead of command line

### ISSUE THREAD

**Issue by gitnava** [ios-driver/ios-driver#256]
We currently use Maven and we would like to run the scripts without having to run the command line first as an isolated event:
java -jar ios-server-0.6.6-SNAPSHOT-standalone.jar -autpath/to/aut.app -port 4444

is it possible to bypass this step and integrate it to the maven testng webdriver setup?
What would be the key points for doing so?
How to use the IOSServerConfiguration?
Changes to the pom file?

Any help or guidance is really appreciated.
Thanks:)

**Comment by freynaud** [comment]
you can start the server for java if you want. It would look like what you can see in the unit test :
https://github.com/ios-driver/ios-driver/blob/dev/server/src/test/java/org/uiautomation/ios/BaseIOSDriverTest.java#L57
Change the -aut to the path of your own app, or remove the -aut if you want safari only.

**Comment by gitnava** [comment]
Great!! In order to use IOSServer and IOSServerConfiguration, what should I add to the pom file?

I am able to make it work by running mvn command on the ios-driver-dev folder (git from dev branch). This way a pull everything that I need to my local .m2 folder. Also, because maven central does not have 0.6.6-SNAPSHOT, they have up 0.6.5 only. So, what would be the desirable approach, as far as pom file changes, to support 0.6.6-SNAPSHOT without running maven command on the ios-driver-dev folder? 

Thanks a lot for your guidance.
