### ISSUE TITLE
iOS Driver - parsing of installed SDK fails when there is a plugin warning

### ISSUE THREAD

**Issue by OmerObaid** [ios-driver/ios-driver#257]
Im trying to run iOS driver server.
This is the command Im running
" java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut /Users/ebryx/iOS_Driver/InternationalMountains.app -port 4444  "

and the output is:
23:52:680 WARNING AppleLanguage.create  crazy-language isn't recognized. Please file a bug on github. You won't be able to start the app in that language.
23:55:557 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled : false
Inspector: http://0.0.0.0:4444/inspector/
Tests can access the server at http://0.0.0.0:4444/wd/hub
Server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/ebryx/iOS_Driver/applications' for new applications
Archived apps: /Users/ebryx/iOS_Driver/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140326-1201,sha:69eb457e39da8babb88070a47009ab8dceba0c6d)
Running on: Mac OS X 10.8.5 (x86_64)
Using java: 1.7.0_51
## Applications :

```
CFBundleName=InternationalMountains,CFBundleVersion=1.1,/Users/ebryx/iOS_Driver/InternationalMountains.app
```

2014-05-13 14:23:56.157:INFO::jetty-7.x.y-SNAPSHOT
2014-05-13 14:23:56.606:INFO::Started SelectChannelConnector@0.0.0.0:4444

Regards,
Omer Obaid

**Comment by freynaud** [comment]
what's the problem ? the server seems to be running on 4444 from your logs.

**Comment by OmerObaid** [comment]
Thanks for your fast Reply :)
These two line bothering me
1)23:52:680 WARNING AppleLanguage.create crazy-language isn't recognized. Please file a bug on github. You won't be able to start the app in that language.
2)Simulator enabled : false

Im following this link: http://ios-driver.github.io/ios-driver/?page=setup
and when i open this in my Chrome http://localhost:4444/wd/hub/status
Im getting this :
{
message: "bug.-1 Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_51' Driver info: driver.version: unknown",
screen: null,
cause: {
message: "-1",
screen: null,
class: "java.lang.ArrayIndexOutOfBoundsException",
stackTrace: [
{
fileName: "ArrayList.java",
lineNumber: 400,
className: "java.util.ArrayList",
methodName: "elementData"
},
{
fileName: "ArrayList.java",
lineNumber: 413,
className: "java.util.ArrayList",
methodName: "get"
},
{
fileName: "ClassicCommands.java",
lineNumber: 149,
className: "org.uiautomation.ios.utils.ClassicCommands",
methodName: "getDefaultSDK"
},
{
fileName: "ServerStatusNHandler.java",
lineNumber: 57,
className: "org.uiautomation.ios.server.command.uiautomation.ServerStatusNHandler",
methodName: "handle"
},
{
fileName: "BaseCommandHandler.java",
lineNumber: 104,
className: "org.uiautomation.ios.server.command.BaseCommandHandler",
methodName: "handleAndRunDecorators"
},
{
fileName: "IOSServlet.java",
lineNumber: 137,
className: "org.uiautomation.ios.server.servlet.IOSServlet",
methodName: "getResponse"
},
{
fileName: "IOSServlet.java",
lineNumber: 81,
className: "org.uiautomation.ios.server.servlet.IOSServlet",
methodName: "process"
},
{
fileName: "IOSServlet.java",
lineNumber: 46,
className: "org.uiautomation.ios.server.servlet.IOSServlet",
methodName: "doGet"
},
{
fileName: "HttpServlet.java",
lineNumber: 707,
className: "javax.servlet.http.HttpServlet",
methodName: "service"
},
{
fileName: "HttpServlet.java",
lineNumber: 820,
className: "javax.servlet.http.HttpServlet",
methodName: "service"
},
{
fileName: "ServletHolder.java",
lineNumber: 533,
className: "org.eclipse.jetty.servlet.ServletHolder",
methodName: "handle"
},
{
fileName: "ServletHandler.java",
lineNumber: 475,
className: "org.eclipse.jetty.servlet.ServletHandler",
methodName: "doHandle"
},
{
fileName: "SessionHandler.java",
lineNumber: 224,
className: "org.eclipse.jetty.server.session.SessionHandler",
methodName: "doHandle"
},
{
fileName: "ContextHandler.java",
lineNumber: 920,
className: "org.eclipse.jetty.server.handler.ContextHandler",
methodName: "doHandle"
},
{
fileName: "ServletHandler.java",
lineNumber: 403,
className: "org.eclipse.jetty.servlet.ServletHandler",
methodName: "doScope"
},
{
fileName: "SessionHandler.java",
lineNumber: 184,
className: "org.eclipse.jetty.server.session.SessionHandler",
methodName: "doScope"
},
{
fileName: "ContextHandler.java",
lineNumber: 856,
className: "org.eclipse.jetty.server.handler.ContextHandler",
methodName: "doScope"
},
{
fileName: "ScopedHandler.java",
lineNumber: 117,
className: "org.eclipse.jetty.server.handler.ScopedHandler",
methodName: "handle"
},
{
fileName: "HandlerList.java",
lineNumber: 47,
className: "org.eclipse.jetty.server.handler.HandlerList",
methodName: "handle"
},
{
fileName: "HandlerWrapper.java",
lineNumber: 114,
className: "org.eclipse.jetty.server.handler.HandlerWrapper",
methodName: "handle"
},
{
fileName: "Server.java",
lineNumber: 352,
className: "org.eclipse.jetty.server.Server",
methodName: "handle"
},
{
fileName: "HttpConnection.java",
lineNumber: 596,
className: "org.eclipse.jetty.server.HttpConnection",
methodName: "handleRequest"
},
{
fileName: "HttpConnection.java",
lineNumber: 1049,
className: "org.eclipse.jetty.server.HttpConnection$RequestHandler",
methodName: "headerComplete"
},
{
fileName: "HttpParser.java",
lineNumber: 590,
className: "org.eclipse.jetty.http.HttpParser",
methodName: "parseNext"
},
{
fileName: "HttpParser.java",
lineNumber: 212,
className: "org.eclipse.jetty.http.HttpParser",
methodName: "parseAvailable"
},
{
fileName: "HttpConnection.java",
lineNumber: 426,
className: "org.eclipse.jetty.server.HttpConnection",
methodName: "handle"
},
{
fileName: "SelectChannelEndPoint.java",
lineNumber: 510,
className: "org.eclipse.jetty.io.nio.SelectChannelEndPoint",
methodName: "handle"
},
{
fileName: "SelectChannelEndPoint.java",
lineNumber: 34,
className: "org.eclipse.jetty.io.nio.SelectChannelEndPoint",
methodName: "access$000"
},
{
fileName: "SelectChannelEndPoint.java",
lineNumber: 40,
className: "org.eclipse.jetty.io.nio.SelectChannelEndPoint$1",
methodName: "run"
},
{
fileName: "QueuedThreadPool.java",
lineNumber: 450,
className: "org.eclipse.jetty.util.thread.QueuedThreadPool$2",
methodName: "run"
},
{
fileName: "Thread.java",
lineNumber: 744,
className: "java.lang.Thread",
methodName: "run"
}
]
},
class: "org.openqa.selenium.WebDriverException",
stackTrace: [
{
fileName: "IOSServlet.java",
lineNumber: 158,
className: "org.uiautomation.ios.server.servlet.IOSServlet",
methodName: "getResponse"
},
{
fileName: "IOSServlet.java",
lineNumber: 81,
className: "org.uiautomation.ios.server.servlet.IOSServlet",
methodName: "process"
},
{
fileName: "IOSServlet.java",
lineNumber: 46,
className: "org.uiautomation.ios.server.servlet.IOSServlet",
methodName: "doGet"
},
{
fileName: "HttpServlet.java",
lineNumber: 707,
className: "javax.servlet.http.HttpServlet",
methodName: "service"
},
{
fileName: "HttpServlet.java",
lineNumber: 820,
className: "javax.servlet.http.HttpServlet",
methodName: "service"
},
{
fileName: "ServletHolder.java",
lineNumber: 533,
className: "org.eclipse.jetty.servlet.ServletHolder",
methodName: "handle"
},
{
fileName: "ServletHandler.java",
lineNumber: 475,
className: "org.eclipse.jetty.servlet.ServletHandler",
methodName: "doHandle"
},
{
fileName: "SessionHandler.java",
lineNumber: 224,
className: "org.eclipse.jetty.server.session.SessionHandler",
methodName: "doHandle"
},
{
fileName: "ContextHandler.java",
lineNumber: 920,
className: "org.eclipse.jetty.server.handler.ContextHandler",
methodName: "doHandle"
},
{
fileName: "ServletHandler.java",
lineNumber: 403,
className: "org.eclipse.jetty.servlet.ServletHandler",
methodName: "doScope"
},
{
fileName: "SessionHandler.java",
lineNumber: 184,
className: "org.eclipse.jetty.server.session.SessionHandler",
methodName: "doScope"
},
{
fileName: "ContextHandler.java",
lineNumber: 856,
className: "org.eclipse.jetty.server.handler.ContextHandler",
methodName: "doScope"
},
{
fileName: "ScopedHandler.java",
lineNumber: 117,
className: "org.eclipse.jetty.server.handler.ScopedHandler",
methodName: "handle"
},
{
fileName: "HandlerList.java",
lineNumber: 47,
className: "org.eclipse.jetty.server.handler.HandlerList",
methodName: "handle"
},
{
fileName: "HandlerWrapper.java",
lineNumber: 114,
className: "org.eclipse.jetty.server.handler.HandlerWrapper",
methodName: "handle"
},
{
fileName: "Server.java",
lineNumber: 352,
className: "org.eclipse.jetty.server.Server",
methodName: "handle"
},
{
fileName: "HttpConnection.java",
lineNumber: 596,
className: "org.eclipse.jetty.server.HttpConnection",
methodName: "handleRequest"
},
{
fileName: "HttpConnection.java",
lineNumber: 1049,
className: "org.eclipse.jetty.server.HttpConnection$RequestHandler",
methodName: "headerComplete"
},
{
fileName: "HttpParser.java",
lineNumber: 590,
className: "org.eclipse.jetty.http.HttpParser",
methodName: "parseNext"
},
{
fileName: "HttpParser.java",
lineNumber: 212,
className: "org.eclipse.jetty.http.HttpParser",
methodName: "parseAvailable"
},
{
fileName: "HttpConnection.java",
lineNumber: 426,
className: "org.eclipse.jetty.server.HttpConnection",
methodName: "handle"
},
{
fileName: "SelectChannelEndPoint.java",
lineNumber: 510,
className: "org.eclipse.jetty.io.nio.SelectChannelEndPoint",
methodName: "handle"
},
{
fileName: "SelectChannelEndPoint.java",
lineNumber: 34,
className: "org.eclipse.jetty.io.nio.SelectChannelEndPoint",
methodName: "access$000"
},
{
fileName: "SelectChannelEndPoint.java",
lineNumber: 40,
className: "org.eclipse.jetty.io.nio.SelectChannelEndPoint$1",
methodName: "run"
},
{
fileName: "QueuedThreadPool.java",
lineNumber: 450,
className: "org.eclipse.jetty.util.thread.QueuedThreadPool$2",
methodName: "run"
},
{
fileName: "Thread.java",
lineNumber: 744,
className: "java.lang.Thread",
methodName: "run"
}
]
}
Tutorial output is different ...

Regards,
Omer Obaid

**Comment by freynaud** [comment]
WARNING AppleLanguage.create  : that's ok. Intl mountain is a test app that has wrong data in it on purpose, to help testing that the server doesn't crash when wrong apps are used.

Your output seems to indicate that you have something not setup with xcode.
What happens if you type in the command line :
$xcodebuild -showsdks

**Comment by OmerObaid** [comment]
xcodebuild -showsdks
2014-05-13 14:56:34.997 xcodebuild[3246:1207] [MT] PluginLoading: Required plug-in compatibility UUID 37B30044-3B14-46BA-ABAA-F01000C27B63 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
OS X SDKs:
    OS X 10.8                       -sdk macosx10.8

iOS SDKs:
    iOS 7.0                         -sdk iphoneos7.0

iOS Simulator SDKs:
    Simulator - iOS 5.0             -sdk iphonesimulator5.0
    Simulator - iOS 5.1             -sdk iphonesimulator5.1
    Simulator - iOS 6.0             -sdk iphonesimulator6.0
    Simulator - iOS 7.0             -sdk iphonesimulator7.0

**Comment by freynaud** [comment]
bug. I've never seen this plugin loading line before.It breaks the parsing. I'll work on it.

**Comment by OmerObaid** [comment]
so cuz of that bug my server not running ? or what is happening cuz of that bug?
When i run my JAVA code Im getting exception there:
May 13, 2014 1:21:25 PM org.uiautomation.ios.server.application.APPIOSApplication findSafariLocation
WARNING: safari app doesn't exist: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/Applications/MobileSafari.app
Exception in thread "main" org.openqa.selenium.WebDriverException: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/Applications/MobileSafari.app should be the safari app, but doesn't exist.
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:18:15'
System info: host: 'Irfans-Mac-Mini-2.local', ip: '192.168.2.182', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_51'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.application.APPIOSApplication.findSafariApp(APPIOSApplication.java:334)
    at org.uiautomation.ios.server.application.APPIOSApplication.main(APPIOSApplication.java:54)

**Comment by freynaud** [comment]
Can you run the same command:
xcodebuild -showsdks
then right after that, type 
echo $? 

that should return you an int. I suspect it's not 0 for you due to that warning. Can you confirm ?

**Comment by OmerObaid** [comment]
xcodebuild -showsdks
echo $ 
result of this command: "$". 
But Important thing is i deleted "Shared" folder from the following directory  /Library/Application Support/Developer/ after deleting this folder result of "xcodebuild -showsdks" is: 
OS X SDKs:
    OS X 10.8                       -sdk macosx10.8

iOS SDKs:
    iOS 7.0                         -sdk iphoneos7.0

iOS Simulator SDKs:
    Simulator - iOS 5.0             -sdk iphonesimulator5.0
    Simulator - iOS 5.1             -sdk iphonesimulator5.1
    Simulator - iOS 6.0             -sdk iphonesimulator6.0
    Simulator - iOS 7.0             -sdk iphonesimulator7.0

And now the problem Im facing is when i run my JAVA code Im getting exception: 
May 13, 2014 4:45:42 PM org.uiautomation.ios.server.application.APPIOSApplication findSafariLocation
WARNING: safari app doesn't exist: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/Applications/MobileSafari.app
Exception in thread "main" org.openqa.selenium.WebDriverException: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/Applications/MobileSafari.app should be the safari app, but doesn't exist.
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:18:15'
System info: host: 'Irfans-Mac-Mini-2.local', ip: '192.168.2.182', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_51'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.application.APPIOSApplication.findSafariApp(APPIOSApplication.java:334)
    at org.uiautomation.ios.server.application.APPIOSApplication.main(APPIOSApplication.java:54)

Do you know what can be the reason?

**Comment by freynaud** [comment]
echo $? , with the question mark after the dollar sign.

it seems safari is misisng. can you start safari on your simulator without starting ios-driver at all ?

**Comment by OmerObaid** [comment]
echo $? with question mark is printing 0.
And Yes Safari is working on Simulator(iPhone, iOS 6)

**Comment by freynaud** [comment]
how are you starting the server ? APPIOSApplication.java:54 should never be called

**Comment by OmerObaid** [comment]
Command: "java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut /Users/ebryx/iOS_Driver/InternationalMountains.app -port 4444"
OutPut:
26:22:844 INFO ApplicationStore.<init>  App archive folder:/Users/ebryx/iOS_Driver/applications
true
26:23:378 WARNING AppleLanguage.create  crazy-language isn't recognized. Please file a bug on github. You won't be able to start the app in that language.
26:34:825 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:4444/inspector/
Tests can access the server at http://0.0.0.0:4444/wd/hub
Server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/ebryx/iOS_Driver/applications' for new applications
Archived apps: /Users/ebryx/iOS_Driver/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140326-1201,sha:69eb457e39da8babb88070a47009ab8dceba0c6d)
Running on: Mac OS X 10.8.5 (x86_64)
Using java: 1.7.0_51
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.0, build: 51166
Using iOS version 7.0.3
iOS >= 6.0. Safari and hybrid apps are supported.

## Applications :

```
CFBundleName=InternationalMountains,CFBundleVersion=1.1,/Users/ebryx/iOS_Driver/InternationalMountains.app
CFBundleName=Safari,CFBundleVersion=8536.25,/Users/ebryx/.ios-driver/safariCopies/safari-6.0.app
CFBundleName=Safari,CFBundleVersion=9537.53,/Users/ebryx/.ios-driver/safariCopies/safari-7.0.3.app
```

2014-05-13 17:26:35.083:INFO::jetty-7.x.y-SNAPSHOT
2014-05-13 17:26:35.225:INFO::Started SelectChannelConnector@0.0.0.0:4444

**Comment by freynaud** [comment]
ok, so the server works fine.
1) Can you access /wd/status ?
2) what did you run to get the exception  
at org.uiautomation.ios.server.application.APPIOSApplication.findSafariApp(APPIOSApplication.java:334)
at org.uiautomation.ios.server.application.APPIOSApplication.main(APPIOSApplication.java:54)

**Comment by OmerObaid** [comment]
1)http://localhost:4444/wd/hub/status
{
class: "org.openqa.selenium.remote.Response",
hCode: 480022291,
sessionId: null,
state: null,
status: 0,
value: {
build: {
revision: "69eb457e39da8babb88070a47009ab8dceba0c6d",
time: "20140326-1201",
version: "0.6.6-SNAPSHOT"
},
ios: {
simulatorVersion: "7.0.3"
},
java: {
version: "1.7.0_51"
},
os: {
arch: "x86_64",
name: "Mac OS X",
version: "10.8.5"
},
state: "success",
supportedApps: [
{
CFBundleDevelopmentRegion: "en",
CFBundleExecutable: "InternationalMountains",
CFBundleIconFile: "Icon.png",
CFBundleIdentifier: "com.yourcompany.InternationalMountains",
CFBundleInfoDictionaryVersion: "6.0",
CFBundleName: "InternationalMountains",
CFBundlePackageType: "APPL",
CFBundleSignature: "????",
CFBundleSupportedPlatforms: [
"iPhoneSimulator"
],
CFBundleVersion: "1.1",
DTPlatformName: "iphonesimulator",
DTSDKName: "iphonesimulator5.1",
LSRequiresIPhoneOS: true,
NSMainNibFile: "MainWindow",
UIDeviceFamily: [
1
],
applicationPath: "/Users/ebryx/iOS_Driver/InternationalMountains.app",
device: "iphone",
deviceAlt: [
"iphone",
"ipod"
],
device_Alt: [
"iphone",
"ipad"
],
resources: {
CFBundleIconFile: "/wd/hub/resources/hash=-674408620"
},
sdkVersion: "7.0.3",
sdkVersion_Alt: [
"5.0",
"5.1",
"6.0",
"6.1"
],
simulator: true,
supportedLanguages: [
"en",
"fr",
"zh-Hant",
"unknown"
],
timeHack: false
},
{
CFBundleDevelopmentRegion: "English",
CFBundleDisplayName: "Safari",
CFBundleExecutable: "MobileSafari",
CFBundleIcons: {
CFBundlePrimaryIcon: {
CFBundleIconFiles: [
"icon~iphone.png",
"icon~ipad.png",
"icon@2x~iphone.png",
"icon@2x~ipad.png",
"icon-table.png",
"icon-table@2x.png",
"icon-spotlight~ipad.png",
"icon-spotlight@2x~ipad.png"
],
UIPrenderedIcon: true
}
},
CFBundleIdentifier: "com.apple.mobilesafari",
CFBundleInfoDictionaryVersion: "6.0",
CFBundlePackageType: "APPL",
CFBundleShortVersionString: "6.0",
CFBundleSignature: "????",
CFBundleSupportedPlatforms: [
"iPhoneSimulator"
],
CFBundleURLTypes~ipad: [
{
CFBundleURLIsPrivate: true,
CFBundleURLName: "Web App URL",
CFBundleURLSchemes: [
"webclip"
]
},
{
CFBundleURLName: "Web site URL",
CFBundleURLSchemes: [
"http",
"https"
]
},
{
CFBundleURLName: "FTP URL",
CFBundleURLSchemes: [
"ftp"
]
},
{
CFBundleURLName: "Web Search URL",
CFBundleURLSchemes: [
"x-web-search"
]
}
],
CFBundleURLTypes~iphone: [
{
CFBundleURLIsPrivate: true,
CFBundleURLName: "Web App URL",
CFBundleURLSchemes: [
"webclip"
]
},
{
CFBundleURLName: "Web site URL",
CFBundleURLSchemes: [
"http",
"https"
]
},
{
CFBundleURLName: "Radar URL",
CFBundleURLSchemes: [
"rdar",
"radar"
]
},
{
CFBundleURLName: "FTP URL",
CFBundleURLSchemes: [
"ftp"
]
},
{
CFBundleURLName: "Web Search URL",
CFBundleURLSchemes: [
"x-web-search"
]
}
],
CFBundleURLTypes~ipod: [
{
CFBundleURLIsPrivate: true,
CFBundleURLName: "Web App URL",
CFBundleURLSchemes: [
"webclip"
]
},
{
CFBundleURLName: "Web site URL",
CFBundleURLSchemes: [
"http",
"https"
]
},
{
CFBundleURLName: "Radar URL",
CFBundleURLSchemes: [
"rdar",
"radar"
]
},
{
CFBundleURLName: "FTP URL",
CFBundleURLSchemes: [
"ftp"
]
},
{
CFBundleURLName: "Web Search URL",
CFBundleURLSchemes: [
"x-web-search"
]
}
],
CFBundleVersion: "8536.25",
DTPlatformName: "iphonesimulator",
DTSDKName: "iphonesimulator6.0",
LSRequiresIPhoneOS: true,
SBMatchingApplicationGenres: [
"Productivity",
"Utilities"
],
SBUsesNetwork: 3,
SafariProductVersion: "6.0",
UIApplicationDisableLegacyAutorotationKey: true,
UIBackgroundModes: [
"audio",
"continuousFallback"
],
UIDeviceFamily: [
1,
2
],
UIHasPrefs: true,
UISupportedInterfaceOrientations: [
"UIInterfaceOrientationPortrait",
"UIInterfaceOrientationLandscapeLeft",
"UIInterfaceOrientationLandscapeRight"
],
UISupportedInterfaceOrientations~ipad: [
"UIInterfaceOrientationPortrait",
"UIInterfaceOrientationLandscapeLeft",
"UIInterfaceOrientationLandscapeRight",
"UIInterfaceOrientationPortraitUpsideDown"
],
applicationPath: "/Users/ebryx/.ios-driver/safariCopies/safari-6.0.app",
device: "iphone",
deviceAlt: [
"iphone",
"ipod",
"ipad"
],
device_Alt: [
"iphone",
"ipad"
],
resources: {
CFBundleIconFile: "/wd/hub/resources/hash=707870789"
},
sdkVersion: "7.0.3",
sdkVersion_Alt: [
"5.0",
"5.1",
"6.0",
"6.1"
],
simulator: true,
supportedLanguages: [
"ar",
"ca",
"cs",
"da",
"de",
"el",
"en",
"en-GB",
"es",
"fi",
"fr",
"he",
"hr",
"hu",
"id",
"it",
"ja",
"ko",
"ms",
"nl",
"no",
"pl",
"pt",
"pt-PT",
"ro",
"ru",
"sk",
"sv",
"th",
"tr",
"uk",
"vi",
"zh-CN",
"zh-TW"
],
timeHack: false
},
{
CFBundleDevelopmentRegion: "English",
CFBundleDisplayName: "Safari",
CFBundleExecutable: "MobileSafari",
CFBundleIcons: {
CFBundlePrimaryIcon: {
CFBundleIconFiles: [
"icon-spotlight~ipad.png",
"icon-table~ipad.png",
"icon-about~ipad.png",
"icon-table~ipad.png",
"icon-spotlight@2x.png",
"icon-table@2x.png",
"icon~ipad.png",
"icon-about@2x.png",
"icon@2x~iphone.png",
"icon@2x~ipad.png"
],
UIPrenderedIcon: true
}
},
CFBundleIdentifier: "com.apple.mobilesafari",
CFBundleInfoDictionaryVersion: "6.0",
CFBundlePackageType: "APPL",
CFBundleShortVersionString: "7.0",
CFBundleSignature: "????",
CFBundleSupportedPlatforms: [
"iPhoneSimulator"
],
CFBundleURLTypes~ipad: [
{
CFBundleURLIsPrivate: true,
CFBundleURLName: "Web App URL",
CFBundleURLSchemes: [
"webclip"
]
},
{
CFBundleURLName: "Web site URL",
CFBundleURLSchemes: [
"http",
"https"
]
},
{
CFBundleURLName: "FTP URL",
CFBundleURLSchemes: [
"ftp"
]
},
{
CFBundleURLName: "Web Search URL",
CFBundleURLSchemes: [
"x-web-search"
]
},
{
CFBundleURLIsPrivate: true,
CFBundleURLName: "MobileSafari Tab URL",
CFBundleURLSchemes: [
"com-apple-mobilesafari-tab"
]
}
],
CFBundleURLTypes~iphone: [
{
CFBundleURLIsPrivate: true,
CFBundleURLName: "Web App URL",
CFBundleURLSchemes: [
"webclip"
]
},
{
CFBundleURLName: "Web site URL",
CFBundleURLSchemes: [
"http",
"https"
]
},
{
CFBundleURLName: "Radar URL",
CFBundleURLSchemes: [
"rdar",
"radar"
]
},
{
CFBundleURLName: "FTP URL",
CFBundleURLSchemes: [
"ftp"
]
},
{
CFBundleURLName: "Web Search URL",
CFBundleURLSchemes: [
"x-web-search"
]
},
{
CFBundleURLIsPrivate: true,
CFBundleURLName: "MobileSafari Tab URL",
CFBundleURLSchemes: [
"com-apple-mobilesafari-tab"
]
}
],
CFBundleURLTypes~ipod: [
{
CFBundleURLIsPrivate: true,
CFBundleURLName: "Web App URL",
CFBundleURLSchemes: [
"webclip"
]
},
{
CFBundleURLName: "Web site URL",
CFBundleURLSchemes: [
"http",
"https"
]
},
{
CFBundleURLName: "Radar URL",
CFBundleURLSchemes: [
"rdar",
"radar"
]
},
{
CFBundleURLName: "FTP URL",
CFBundleURLSchemes: [
"ftp"
]
},
{
CFBundleURLName: "Web Search URL",
CFBundleURLSchemes: [
"x-web-search"
]
},
{
CFBundleURLIsPrivate: true,
CFBundleURLName: "MobileSafari Tab URL",
CFBundleURLSchemes: [
"com-apple-mobilesafari-tab"
]
}
],
CFBundleVersion: "9537.53",
DTPlatformName: "iphonesimulator",
DTSDKName: "iphonesimulator7.0",
LSRequiresIPhoneOS: true,
MallocBehavior: {
NanoAllocator: false
},
SBMatchingApplicationGenres: [
"Productivity",
"Utilities"
],
SBUsesNetwork: 3,
SafariProductVersion: "7.0",
UIApplicationDisableLegacyAutorotationKey: true,
UIBackgroundModes: [
"audio",
"continuousFallback"
],
UIBackgroundStyle: "UIBackgroundStyleDarkBlur",
UIDeviceFamily: [
1,
2
],
UIHasPrefs: true,
UIStatusBarTintParameters: {
UINavigationBar: {
Style: "UIBarStyleDefault"
}
},
UISupportedInterfaceOrientations: [
"UIInterfaceOrientationPortrait",
"UIInterfaceOrientationLandscapeLeft",
"UIInterfaceOrientationLandscapeRight"
],
UISupportedInterfaceOrientations~ipad: [
"UIInterfaceOrientationPortrait",
"UIInterfaceOrientationLandscapeLeft",
"UIInterfaceOrientationLandscapeRight",
"UIInterfaceOrientationPortraitUpsideDown"
],
UIViewControllerBasedStatusBarAppearance: true,
applicationPath: "/Users/ebryx/.ios-driver/safariCopies/safari-7.0.3.app",
device: "iphone",
deviceAlt: [
"iphone",
"ipod",
"ipad"
],
device_Alt: [
"iphone",
"ipad"
],
resources: {
CFBundleIconFile: "/wd/hub/resources/hash=2134756163"
},
sdkVersion: "7.0.3",
sdkVersion_Alt: [
"5.0",
"5.1",
"6.0",
"6.1"
],
simulator: true,
supportedLanguages: [
"ar",
"ca",
"cs",
"da",
"de",
"el",
"en",
"en-GB",
"es",
"fi",
"fr",
"he",
"hr",
"hu",
"id",
"it",
"ja",
"ko",
"ms",
"nl",
"no",
"pl",
"pt",
"pt-PT",
"ro",
"ru",
"sk",
"sv",
"th",
"tr",
"uk",
"vi",
"zh-CN",
"zh-TW"
],
timeHack: false
}
]
}
}

2) JAVA code
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.Augmenter;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.Assert;

//import org.openqa.selenium.remote.*;
import org.uiautomation.ios.IOSCapabilities;

public class FirstTestClass {

public static void main(String[] args) throws MalformedURLException {

```
DesiredCapabilities cap = IOSCapabilities.iphone("InternationalMountains", "1.1");
// start the application
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), cap);

// check that the 9 mountains of the app are there.
List<WebElement> cells = driver.findElements(By.className("UIATableCell"));
Assert.assertEquals(9,cells.size());


// get the 1st mountain
WebElement first = cells.get(0);
first.click();

// take a screenshot using the normal selenium api.
TakesScreenshot screen =(TakesScreenshot)new Augmenter().augment(driver);
File ss = new File("screenshot.png");
screen.getScreenshotAs(OutputType.FILE).renameTo(ss);
System.out.println("screenshot take :"+ss.getAbsolutePath());

// access the content
By selector = By.xpath("//UIAStaticText[contains(@name,'climbed')]");
WebElement text = driver.findElement(selector);
System.out.println(text.getAttribute("name"));

// end the test
driver.quit();
}
```

}

**Comment by freynaud** [comment]
ok, and that fails where ?
you can also join irc , #ios-driver on freenode if you want :)

**Comment by OmerObaid** [comment]
I dunno about FreeNode but ill join Thank you very much :).
and like i said before Im getting exception when i run JAVA code

**Comment by freynaud** [comment]
you need to tell me what code you execute, and what line throw the exception. Otherwise it's tricky for me to debug

**Comment by OmerObaid** [comment]
Here is the Code:
public static void main(String[] args) throws MalformedURLException {

```
System.out.println("I'm in Main");

DesiredCapabilities cap = IOSCapabilities.iphone("InternationalMountains", "1.1");
// start the application
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), cap);

// check that the 9 mountains of the app are there.
List<WebElement> cells = driver.findElements(By.className("UIATableCell"));
Assert.assertEquals(9,cells.size());


// get the 1st mountain
WebElement first = cells.get(0);
first.click();

// take a screenshot using the normal selenium api.
TakesScreenshot screen =(TakesScreenshot)new Augmenter().augment(driver);
File ss = new File("screenshot.png");
screen.getScreenshotAs(OutputType.FILE).renameTo(ss);
System.out.println("screenshot take :"+ss.getAbsolutePath());
```

}

And its not even priniting "I'm in Main"

Exception is: May 13, 2014 6:28:40 PM org.uiautomation.ios.server.application.APPIOSApplication findSafariLocation
WARNING: safari app doesn't exist: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/Applications/MobileSafari.app
Exception in thread "main" org.openqa.selenium.WebDriverException: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/Applications/MobileSafari.app should be the safari app, but doesn't exist.
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:18:15'
System info: host: 'Irfans-Mac-Mini-2.local', ip: '192.168.2.182', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_51'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.application.APPIOSApplication.findSafariApp(APPIOSApplication.java:334)
    at org.uiautomation.ios.server.application.APPIOSApplication.main(APPIOSApplication.java:54)

**Comment by freynaud** [comment]
that seems more a java problem. You should see your system out.

**Comment by OmerObaid** [comment]
Okay Thank you very much :+1 :+1:  )
