### ISSUE TITLE
Unable to launch demo native app from eclipse using simulator 

### ISSUE THREAD

**Issue by Althafbasha** [ios-driver/ios-driver#266]
Hi,

   I have done set-up process successfully for ios driver as mentioned in http://ios-driver.github.io/ios-driver. when i try to run given demo app "Internation Mountains" using "$java -jar ios-server-0.6.6-SNAPSHOT.jar -aut ~/InternationalMountains.app -port 5555 -simulators" command facing the below problem

   1)Error: Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -simulators
   2)From which path above command should run in terminal is not given in http://ios-driver.github.io/ios-driver/?page=native
   3)Currently i am using java code in eclipse.My doubt is how simulator supports automation when we launch app from eclipse

   I am strucked in launching demo app in simulator. please help me for proceed further

**Comment by kumaravel-jayakumar** [comment]
@Althafbasha
'-simulator' parameter is not required.
You may require the ios-server-standalone-***-jar-with-depedencies to run the test case.
Use the following command to start the ios-driver.

java -jar ios-server-standalone-0.6.6-SNAPSHOT-***-jar-with-dependencies.jar -port 4444 -aut <Path to the application>

Run the command from the folder that has the ios-server-standalone-0.6.6-SNAPSHOT-***-jar-with-dependencies.jar
