### ISSUE TITLE
ClassCastException when retrieving pageSource

### ISSUE THREAD

**Issue by operatiay** [ios-driver/ios-driver#283]
when calling `driver.getPageSource()` I'm getting following error message (stack trace):

```
java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String
    at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:459)
```

Is there a way to get the page source (basically the structure with available attributes) other than via inspector? Unfortunately the page is too big and the inspector is hanging for a minute and then terminates the server.... On the other hand this would be another issue. So let's concentrate on the `.getPageSource()` problem here.

**Comment by azaytsev** [comment]
@operatiay Can you provide a small sample test where I can reproduce this issue. I tried doing a simple test below and it works without any issues. 
        driver.get("https://www.google.com");
        driver.getPageSource();

**Comment by operatiay** [comment]
@azaytsev I was using native app rather than web.
ios-driver has an extra method provided by RemoteIOSDriver: `.logElementTree` which returns a JSONObject.

**Comment by ILikeToNguyen** [comment]
@operatiay 
Is this still valid?  With the latest ios-driver, I did driver.getPageSource on the international mountains native app and it performed just fine.

**Comment by operatiay** [comment]
@ILikeToNguyen: sorry, I'm not working on iOS automation right now and can't test it with the latest ios-driver. If you consider it working then you can close the issue.

**Comment by mach6** [comment]
@operatiay @ILikeToNguyen closing this since it seems like it can not be reproduced anymore
