### ISSUE TITLE
I am trying to register a node on one of my grid hub in Win 7

### ISSUE THREAD

**Issue by shashidhargsg** [ios-driver/ios-driver#285]
I am trying to register a node on one of my grid hub in Win 7

java -cp ios-grid-0.6.6-SNAPSHOT.jar;selenium-server-standalone-2.42.2.jar org.openqa.grid.selenium.GridLauncher -role hub

and to register a node in MAC I am running below command-

java -jar ios-server-0.6.6-jar-with-dependencies.jar -hub http://IP:4444/grid/register -proxy org.uiautomation.ios.grid.IOSRemoteProxy -host IP -port 5555 -beta

I see below exception on my MAC-
Exception in thread "Thread-15" org.openqa.selenium.WebDriverException: Error sending the registration request.

I checked the network firewall its fine

I am using a real device

Please let me know what could be the issue

**Comment by mach6** [comment]
@shashidhargsg Is this still and issue? Have you tried with `IOSMutableRemoteProxy`? `IOSRemoteProxy` is deprecated.  Please re-open if you still need assistance.
