### ISSUE TITLE
Use the latest code, cannot run it on iOS

### ISSUE THREAD

**Issue by fqlyu** [ios-driver/ios-driver#292]
I have downloaded the ios-driver code and try to run it with xcode6:
1.  but it failed to get the http response, so it will time out between 2 commands.
2. it always throw MessageFactory.create form error. The reason is : when create a new webkitpage, some page do not have WIRURLKey, so it throw null point exception.

**Comment by bijoyv** [comment]
It is difficult to reproduce the problem with the description, can you please post the exact steps/code to reproduce the issue

**Comment by mach6** [comment]
@fqlyu closing this. we need further details.
