### ISSUE TITLE
meet a 'Cannot load win32-x86-64/libcrypto.dll' error when launch the ios-driver 

### ISSUE THREAD

**Issue by leoxiao24** [ios-driver/ios-driver#299]
full error message in windows command line:
D:\Thirdparty\selenium>java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut path/to/aut.app -port 4444
Cannot load win32-x86-64/libcrypto.dll
Oct 20, 2014 11:57:21 PM org.uiautomation.ios.IOSServer main
SEVERE: cannot start ios-driver server.
java.lang.NullPointerException
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
        at org.libimobiledevice.ios.driver.binding.raw.JNAInit.copy(JNAInit.java:131)
        at org.libimobiledevice.ios.driver.binding.raw.JNAInit.unpack(JNAInit.java:117)
        at org.libimobiledevice.ios.driver.binding.raw.JNAInit.init(JNAInit.java:74)
        at org.uiautomation.ios.IOSServer.start(IOSServer.java:259)
        at org.uiautomation.ios.IOSServer.main(IOSServer.java:104)

I was trying on a windows 2008 R2 visual machine. No way to start with anything for IOS test, any suggestion please ?

**Comment by leoxiao24** [comment]
What's more, the OS is x64. The chromedriver, firefox driver and phantomjs driver all works fine.

**Comment by pshakya** [comment]
Error happens to me when I run, ios-driver based automation from windows machine to mac as selenium host.

**Comment by mach6** [comment]
This is because the file is not part of the `libimobiledevice-wrapper` jar. The code below extracts said file (a resource) from the jar to the `~/.ios-driver/jna` folder

https://github.com/ios-driver/libimobiledevice-wrapper/blob/dc6feb10989259f827681a44c798f82d9f801feb/src/main/java/org/libimobiledevice/ios/driver/binding/raw/JNAInit.java#L101

However, it is not (yet) part of the source -- https://github.com/ios-driver/libimobiledevice-wrapper/tree/dc6feb10989259f827681a44c798f82d9f801feb/src/main/resources

Only `darwin` is (currently) available.

**Comment by leoxiao24** [comment]
@mach6 Thanks for your reply! However, I'm not sure if I'm understanding right, did you mean the winx86-64 is currently not supported with the ios-driver? Or any direction I should turn to look at to setup the ios-driver on a windows 64bit machine ?

**Comment by mach6** [comment]
@leoxiao24 it means you can't run (presently) ios server (in your case standalone is starting the server) on a windows machine. You need a mac for the server even if your goal is to just tether physical devices.

@pshakya i'm a bit surprised by your case. ping me offline so we can walk through it together. I need more info at this point.

**Comment by pshakya** [comment]
Thanks @mach6, I will sync up with you offline.

**Comment by leoxiao24** [comment]
@mach6 Thanks!

**Comment by hossainelahi7** [comment]
@mach6 is ios_driver working now in windows platform???
