### ISSUE TITLE
iOS 8.1 is supported?

### ISSUE THREAD

**Issue by maznikoff** [ios-driver/ios-driver#304]
Hi everybody. I'm trying to start iOS 8.1 simulator, but I have one result: Cannot create iOS driver! org.openqa.selenium.SessionNotCreatedException: failed starting after 3 retries.Final wait was 80.

Command for execution is : "java -jar %s-port 4444 -newSessionTimeoutSec 120" , where %s is path to ios_server_compiled_jar. 

My capabilities: 

DesiredCapabilities safariIphone = IOSCapabilities.iphone("Safari");
            safariIphone.setCapability(IOSCapabilities.SIMULATOR, true);
            safariIphone.setCapability("variation", "iPhone5");
            safariIphone.setCapability(IOSCapabilities.LANGUAGE, "en");
            safariIphone.setCapability(IOSCapabilities.LOCALE, "en_US");
            driver = new IOSCustomDriver(new URL("http://localhost:4444/wd/hub"), safariIphone);

Help me please :(

**Comment by bijoyv** [comment]
I've seen similar problems in the past when tried to use the already built-and-provided apps like International mountains, can you see your apps run fine with 8.1 simulator (not through ios-driver)

**Comment by mach6** [comment]
@plastex closing this. please re-open if you need further assistance.
