### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: iPhone variation incompatible with SDK 7.1, a compatible variation is Retina4

### ISSUE THREAD

**Issue by RahulS99** [ios-driver/ios-driver#310]
Hi, I've been trying to start a Selenium test on an iPhone simulator for quite some time but I keep getting the same error. I only want to test mobile Safari (I'm not testing any native or hybrid apps).

I have followed instructions in your documentation, first started the simulator in Xcode and then ran those commands in the terminal:

$xcodeVersion=`xcode-select --print-path`
$sudo chmod a+rw "$xcodeVersion/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications"
$sudo chmod -R a+rw "$xcodeVersion/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app"
After that, started the server with this command

$ java -jar ios-server-0.6.6-SNAPSHOT-standalone.jar  -port 4444

Server has started and I got the right JSON object also:

{
  "class": "org.openqa.selenium.remote.Response",
  "hCode": 1303550662,
  "sessionId": "894bd53a-7260-4644-81b2-69df9575fc7e",
  "state": null,
  "status": 0,
  "value": {
    "build": {
      "revision": "120cf4311807e2e137e519f4c4877cf6340d0cbc",
      "time": "20130927-1435",
      "version": "0.6.5"
    },
    "ios": {"simulatorVersion": "7.1"},
    "java": {"version": "1.8.0_05"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.9.2"
    },
    "state": "success",
    "supportedApps": [{
      "CFBundleDevelopmentRegion": "English",
      "CFBundleDisplayName": "Safari",
      "CFBundleExecutable": "MobileSafari",
      "CFBundleIcons": {"CFBundlePrimaryIcon": {
        "CFBundleIconFiles": [
          "icon-spotlight~ipad.png",
          "icon-table~ipad.png",
          "icon-about~ipad.png",
          "icon-table~ipad.png",
          "icon-spotlight@2x.png",
          "icon-table@2x.png",
          "icon~ipad.png",
          "icon-about@2x.png",
          "icon@2x~iphone.png",
          "icon@2x~ipad.png"
        ],
        "UIPrenderedIcon": true
      }},
      "CFBundleIdentifier": "com.apple.mobilesafari",
      "CFBundleInfoDictionaryVersion": "6.0",
      "CFBundlePackageType": "APPL",
      "CFBundleShortVersionString": "7.0",
      "CFBundleSignature": "????",
      "CFBundleSupportedPlatforms": ["iPhoneSimulator"],
      "CFBundleURLTypes~ipad": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleURLTypes~iphone": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "Radar URL",
          "CFBundleURLSchemes": [
            "rdar",
            "radar"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleURLTypes~ipod": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "Radar URL",
          "CFBundleURLSchemes": [
            "rdar",
            "radar"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleVersion": "9537.53",
      "DTPlatformName": "iphonesimulator",
      "DTSDKName": "iphonesimulator7.1",
      "LSRequiresIPhoneOS": true,
      "MallocBehavior": {"NanoAllocator": false},
      "SBMatchingApplicationGenres": [
        "Productivity",
        "Utilities"
      ],
      "SBUsesNetwork": 3,
      "SafariProductVersion": "7.0",
      "UIApplicationDisableLegacyAutorotationKey": true,
      "UIBackgroundModes": [
        "audio",
        "continuousFallback"
      ],
      "UIBackgroundStyle~iphone": "UIBackgroundStyleDarkBlur",
      "UIDeviceFamily": [
        2,
        1
      ],
      "UIHasPrefs": true,
      "UIStatusBarTintParameters": {"UINavigationBar": {"Style": "UIBarStyleDefault"}},
      "UISupportedInterfaceOrientations": [
        "UIInterfaceOrientationPortrait",
        "UIInterfaceOrientationLandscapeLeft",
        "UIInterfaceOrientationLandscapeRight"
      ],
      "UISupportedInterfaceOrientations~ipad": [
        "UIInterfaceOrientationPortrait",
        "UIInterfaceOrientationLandscapeLeft",
        "UIInterfaceOrientationLandscapeRight",
        "UIInterfaceOrientationPortraitUpsideDown"
      ],
      "UIViewControllerBasedStatusBarAppearance": true,
      "applicationPath": "/Users/rahulshinde/.ios-driver/safariCopies/safari-7.1.app",
      "device": "iphone",
      "deviceAlt": [
        "ipad",
        "iphone",
        "ipod"
      ],
      "device_Alt": [
        "iphone",
        "ipad"
      ],
      "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=2134756163"},
      "sdkVersion": "7.1",
      "sdkVersion_Alt": [
        "5.0",
        "5.1",
        "6.0",
        "6.1"
      ],
      "simulator": true,
      "supportedLanguages": [
        "unknown",
        "it",
        "fi",
        "ru",
        "pt",
        "de",
        "hr",
        "hu",
        "fr",
        "unknown",
        "uk",
        "sk",
        "es",
        "id",
        "ca",
        "sv",
        "ko",
        "ms",
        "el",
        "ja",
        "cs",
        "ar",
        "en",
        "en-GB",
        "vi",
        "th",
        "unknown",
        "pl",
        "da",
        "nl",
        "he",
        "ro",
        "tr",
        "pt-PT"
      ],
      "timeHack": false,
      "variation": "Regular"
    }]
  }
}
when i am trying to create driver i am facing below issue:

Code:
           serverConfig  = new IOSServerConfiguration();
       serverConfig.setPort(4444);
       serverConfig.setSimulators(true);
       // Start IOS server
       iOSServer = new IOSServer(serverConfig);
       iOSServer.start();
           DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
       driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), safari);

Log:
"org.openqa.selenium.SessionNotCreatedException: iPhone variation incompatible with SDK 7.1, a compatible variation is Retina4
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'LM-SYD-00321310', ip: '10.10.10.104', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.8.0_05'
Driver info: driver.version: IOSDualDriver
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'LM-SYD-00321310', ip: '10.10.10.104', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.8.0_05'
Driver info: driver.version: unknown
Command duration or timeout: 1.60 seconds
Build info: version: '2.35.0', revision: '8df0c6bedf70ff9f22c647788f9fe9c8d22210e2', time: '2013-08-17 12:46:41'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.8.0_05'
Driver info: org.openqa.selenium.remote.RemoteWebDriver”

Please help me understanding what causing this issue at my end.

**Comment by bijoyv** [comment]
ios driver uses iPhone Retina (4-inch) for sdk 7.1 by default, seems like that device configuration is not there in your simulator (see Hardware->Device menu for your simulator). Alternatively you may set a device variation present in your simulator, for example say if iPhone 4s is present in your simulator, you may try altering your code as follows and try

serverConfig = new IOSServerConfiguration();
serverConfig.setPort(4444);
serverConfig.setSimulators(true);
// Start IOS server
iOSServer = new IOSServer(serverConfig);
iOSServer.start();

IOSCapabilities safari = IOSCapabilities.iphone("Safari");
safari.setDeviceVariation(DeviceVariation.iPhone4s);

driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), (DesiredCapabilities)safari);

**Comment by azaytsev** [comment]
@RahulS99 what version of XCode/ios sdk do you have installed? You can run xcodebuild -showsdks
to display it. 

I suspect you have ios 8 / Xcode 6 installed which doesn't have a profile for "iPhone Retina (4-inch)" simulator. There are two ways to resolve it.
1) Set a DeviceVariation to a simulator you have installed (4s, 5, etc). See the code example @bijoyv provided above. This is a preferred method
2) Open your ios simulator.   Click Hardware->Device->Manage Devices. Click the "+" on the screen that pops-up and add a new simulator named "iPhone Retina (4-inch)" that points to iPhone 4s device. This a temporary hack that create a simulator with the name "iPhone Retina (4-inch)".

This should resolve your issue.

**Comment by mach6** [comment]
please re-open if needed
