### ISSUE TITLE
Node repeatedly registering and unregistering with grid.

### ISSUE THREAD

**Issue by JoolsCaesar** [ios-driver/ios-driver#324]
I'm try to connect an iOS node to my grid following the instruction given at http://ios-driver.github.io/ios-driver/?page=scaling

I run my grid with the following command on my hub machine (qawintest4):

java -cp ios-grid-plugin-0.6.6-SNAPSHOT.jar:ios-server-standalone-0.6.6-SNAPSHOT.jar:selenium-server-standalone-2.44.0.jar org.openqa.grid.selenium.GridLauncher -role hub 

I had to add the ios server snapshot to the classpath as I was getting undefined class exceptions for things like org/json. It seems to start ok with the following output:

Nov 20, 2014 10:20:50 AM org.openqa.grid.selenium.GridLauncher main
INFO: Launching a selenium grid server
2014-11-20 10:20:51.463:INFO:osjs.Server:jetty-7.x.y-SNAPSHOT
2014-11-20 10:20:51.536:INFO:osjsh.ContextHandler:started o.s.j.s.ServletContextHandler{/,null}
2014-11-20 10:20:51.544:INFO:osjs.AbstractConnector:Started SocketConnector@0.0.0.0:4444
Nov 20, 2014 10:20:54 AM org.openqa.grid.internal.BaseRemoteProxy <init>
WARNING: Max instance not specified. Using default = 1 instance

I start my ios node with the following command on my mac (macpro) :

java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -hub http://qawintest:444/grid/register -proxy org.uiautomation.ios.grid.IOSRemoteProxy -host macpro -port 5555

The output is as follows:

25:15:454 INFO ApplicationStore.<init>  App archive folder:/Applications/selenium/applications
version:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560
Beta features enabled (enabled by -real flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:5555/inspector/
Tests can access the server at http://0.0.0.0:5555/wd/hub
Server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Applications/selenium/applications' for new applications
Archived apps: /Applications/selenium/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20141009-1559,sha:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560)
Running on: Mac OS X 10.9.5 (x86_64)
Using java: 1.8.0_20
Using Xcode install: /Applications/Xcode.app
Using instruments: version:6.1, build: 56160
Using iOS version 8.1
iOS >= 6.0. Safari and hybrid apps are supported.
Applications :
CFBundleName=Safari,CFBundleVersion=600.1.4,/Users/jrc/.ios-driver/safariCopies/safari-8.1.app
2014-11-20 10:25:16.868:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2014-11-20 10:25:16.941:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:5555
25:17:171 INFO StoppableRegisteringRemote.startRegistrationProcess  using the json request : {"capabilities":[{"NSLocationWhenInUseUsageDescription":"Websites you visit may request your location.","CFBundleDevelopmentRegion":"English","UIBackgroundStyle":"UIBackgroundStyleDarkBlur","SBUsesNetwork":3,"CFBundleURLTypes~ipod":[{"CFBundleURLName":"Web App URL","CFBundleURLSchemes":["webclip"],"CFBundleURLIsPrivate":true},{"CFBundleURLName":"Web site URL","CFBundleURLSchemes":["http","https"]},{"CFBundleURLName":"Radar URL","CFBundleURLSchemes":["rdar","radar"]},{"CFBundleURLName":"FTP URL","CFBundleURLSchemes":["ftp"]},{"CFBundleURLName":"Web Search URL","CFBundleURLSchemes":["x-web-search"]},{"CFBundleURLName":"MobileSafari Tab URL","CFBundleURLSchemes":["com-apple-mobilesafari-tab"],"CFBundleURLIsPrivate":true}],"CFBundleIdentifier":"com.apple.mobilesafari","SBMatchingApplicationGenres":["Productivity","Utilities"],"LSRequiresIPhoneOS":true,"CFBundleExecutable":"MobileSafari","instruments":true,"SafariProductVersion":"8.0","supportedLanguages":["ar","ca","cs","da","de","el","en","en-GB","es","fi","fr","fr-CA","he","hi","hr","hu","id","it","ja","ko","ms","nl","no","pl","pt","pt-PT","ro","ru","sk","sv","th","tr","uk","vi","zh-CN","zh-HK","zh-TW"],"MPSupportsExternallyPlayableContent":true,"CFBundlePackageType":"APPL","CFBundleURLTypes~ipad":[{"CFBundleURLName":"Web App URL","CFBundleURLSchemes":["webclip"],"CFBundleURLIsPrivate":true},{"CFBundleURLName":"Web site URL","CFBundleURLSchemes":["http","https"]},{"CFBundleURLName":"FTP URL","CFBundleURLSchemes":["ftp"]},{"CFBundleURLName":"Web Search URL","CFBundleURLSchemes":["x-web-search"]},{"CFBundleURLName":"MobileSafari Tab URL","CFBundleURLSchemes":["com-apple-mobilesafari-tab"],"CFBundleURLIsPrivate":true}],"CFBundleSupportedPlatforms":["iPhoneSimulator"],"simulator":true,"CFBundleDisplayName":"Safari","timeHack":false,"NSUserActivityTypes":["NSUserActivityTypeBrowsingWeb"],"UIViewControllerBasedStatusBarAppearance":true,"UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight","UIInterfaceOrientationPortraitUpsideDown"],"resources":{"CFBundleIconFile":"/wd/hub/resources/hash=-2111658072"},"UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"CFBundleInfoDictionaryVersion":"6.0","CFBundleSignature":"????","DTSDKName":"iphonesimulator8.1","UIStatusBarTintParameters":{"UINavigationBar":{"Style":"UIBarStyleDefault"}},"CFBundleVersion":"600.1.4","applicationPath":"/Users/jrc/.ios-driver/safariCopies/safari-8.1.app","deviceAlt":["iphone","ipod","ipad"],"UIDeviceFamily":[1,2],"device_Alt":["iphone","ipad"],"UIApplicationDisableLegacyAutorotationKey":true,"UIBackgroundModes":["audio","continuousFallback"],"CFBundleShortVersionString":"8.0","sdkVersion_alt":["8.1"],"sdkVersion":"8.1","CFBundleIcons":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["icon-about@2x.png","icon-about@3x~iphone.png","icon-about~ipad.png","icon-spotlight@2x.png","icon-spotlight@3x~iphone.png","icon-spotlight~ipad.png","icon-table@2x.png","icon-table@3x~iphone.png","icon-table~ipad.png","icon@2x~ipad.png","icon@2x~iphone.png","icon@3x~iphone.png","icon~ipad.png"],"UIPrenderedIcon":true}},"MallocBehavior":{"NanoAllocator":false},"UIHasPrefs":true,"DTPlatformName":"iphonesimulator","device":"iphone","CFBundleURLTypes~iphone":[{"CFBundleURLName":"Web App URL","CFBundleURLSchemes":["webclip"],"CFBundleURLIsPrivate":true},{"CFBundleURLName":"Web site URL","CFBundleURLSchemes":["http","https"]},{"CFBundleURLName":"Radar URL","CFBundleURLSchemes":["rdar","radar"]},{"CFBundleURLName":"FTP URL","CFBundleURLSchemes":["ftp"]},{"CFBundleURLName":"Web Search URL","CFBundleURLSchemes":["x-web-search"]},{"CFBundleURLName":"MobileSafari Tab URL","CFBundleURLSchemes":["com-apple-mobilesafari-tab"],"CFBundleURLIsPrivate":true}]}],"configuration":{"proxy":"org.uiautomation.ios.grid.IOSRemoteProxy","remoteHost":"http://macpro:5555","hubHost":"qawintest4","maxSession":1,"registerCycle":5000,"hubPort":4444,"register":true},"class":"org.openqa.grid.common.RegistrationRequest"}
25:17:173 INFO StoppableRegisteringRemote$1.run  Starting auto register thread. Will try to register every 5000 ms.
25:17:173 INFO StoppableRegisteringRemote.registerToHub  Registering the node to hub :http://qawintest4:4444/grid/register
25:22:251 INFO StoppableRegisteringRemote.registerToHub  Registering the node to hub :http://qawintest4:4444/grid/register

Every five seconds it repeatedly registers to the hub and hub repeats:

Nov 20, 2014 10:35:43 AM org.openqa.grid.internal.BaseRemoteProxy <init>
WARNING: Max instance not specified. Using default = 1 instance
Nov 20, 2014 10:35:44 AM org.openqa.grid.selenium.proxy.DefaultRemoteProxy onEvent
WARNING: Unregistering the node.
Nov 20, 2014 10:35:44 AM org.openqa.grid.internal.Registry removeIfPresent
WARNING: Proxy 'host :http://macpro:5555' was previously registered.  Cleaning up any stale test sessions.

**Comment by kumaravel-jayakumar** [comment]
@JoolsCaesar 

Instead of using 

java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -hub http://qawintest:444/grid/register -proxy org.uiautomation.ios.grid.IOSRemoteProxy -host macpro -port 5555

to start the node can you try 

java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -hub http://qawintest:444/grid/register -proxy org.uiautomation.ios.grid.IOSMutableRemoteProxy -host macpro -port 5555

IOSRemoteProxy is a deprecated class, I tried with IOSMutableRemoteProxy and it seemed to function well.

**Comment by JoolsCaesar** [comment]
@kumaravel-jayakumar 

Thanks for responding.
I've changed my node command to:

java -jar /Applications/selenium/ios-server-standalone-0.6.6-SNAPSHOT.jar -hub http://qawintest4:4444/grid/register -proxy org.uiautomation.ios.grid.IOSMutableRemoteProxy -host macpro -port 5555 -newSessionTimeoutSec 40 &

and while it seems to be connecting to the hub in a stable manner, all the capabilities are reporting null.

The grid console says:
WebDriver
v:nullnullnull

I'm guessing there are 3 nulls because I have 3 copies of safari
CFBundleName=Safari,CFBundleVersion=9537.53,/Users/jrc/.ios-driver/safariCopies/safari-7.0.3.app
    CFBundleName=Safari,CFBundleVersion=9537.53,/Users/jrc/.ios-driver/safariCopies/safari-7.1.app
    CFBundleName=Safari,CFBundleVersion=600.1.4,/Users/jrc/.ios-driver/safariCopies/safari-8.1.app

The configuration listed on the grid reads:
port:4444
servlets:[]
host:null
cleanUpCycle:5000
browserTimeout:0
hubHost:qawintest4
registerCycle:5000
capabilityMatcher:org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout:-1
remoteHost:http://macpro:5555
prioritizer:null
register:true
throwOnCapabilityNotPresent:true
nodePolling:5000
proxy:org.uiautomation.ios.grid.IOSMutableRemoteProxy
maxSession:1
role:hub
jettyMaxThreads:-1
hubPort:4444
timeout:300000

**Comment by kumaravel-jayakumar** [comment]
@JoolsCaesar 
You can backup your '.ios-driver/' folder or delete it, I should be recreated during launch. Try running a test on the grid and see if you can succeed.

You can also log into http://macpro:<your-ios-server-port>/wd/hub/capabilities/all to check the available capabilites

**Comment by JoolsCaesar** [comment]
@kumaravel-jayakumar 

I deleted .ios-driver and relaunched the node. My grid displayed the same config as above.

I went on  http://macpro:5555/wd/hub/capabilities/all and found 3 instances of  com.app.mobilesafari on iphone(Simulator), as I suspected one for each sdk

I tried to run a test and got an exception when calling RemoteWebDriver(URL remoteAddress, Capabilities desiredCapabilities);

Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: Error forwarding the new session cannot find : Capabilities [{platform=MAC, browserName=iPad, version=}]

I get the desired capabilities using DesiredCapabilities.ipad() and remoteAddress is my grid "http://qawintest4:4444/wd/hub"

As an experiment I also tried to get it to go straight to the macpro rather than through the grid and got:

org.openqa.selenium.SessionNotCreatedException: The server cannot run Capabilities [{sdkVersion=8.1, CFBundleIdentifier=com.apple.mobilesafari, locale=en_GB, CFBundleName=Safari, device=ipad, version=, platform=MAC, variation=Retina}] at the moment.org.uiautomation.ios.application.APPIOSApplication cannot be cast to org.uiautomation.ios.application.IPAApplication

**Comment by JoolsCaesar** [comment]
@kumaravel-jayakumar 
Thanks a lot for your help. You fixed my original issue. I guess someone should update the documentation that I linked too up top, so that it reflects your fix. My remaining issue was actually just #309 . I needed to update my test code to use the new IOSCapabilities class, so `IOSCapabilities.ipad("Safari")` rather than the old `DesiredCapabilities.ipad()`

**Comment by kumaravel-jayakumar** [comment]
@JoolsCaesar
Glad you got it. I will look into your other issue. In the meanwhile the 
The grid console says:
WebDriver
v:nullnullnull
seems to be broken. I will try to fix it and send a pull request.
Cheers!

**Comment by kumaravel-jayakumar** [comment]
@JoolsCaesar
What is the version on Xcode you are using. The other ticket "309" seems to have provided a solution. Did you try that?

**Comment by JoolsCaesar** [comment]
@kumaravel-jayakumar 
The Xcode version is 6.1 The data given in my output for starting the node is correct:
Running on: Mac OS X 10.9.5 (x86_64)
Using java: 1.8.0_20
Using Xcode install: /Applications/Xcode.app
Using instruments: version:6.1, build: 56160

I've stepped through my test code and the behaviour is pretty weird.

I call new RemoteWebDriver on my grid with the following capabilities
Capabilities [{simulator=true, timeHack=false, locale=en_GB, CFBundleName=Safari, variation=iPadRetina, device=ipad, language=en, instruments=true}]

I get this through the IOSCapabilities class
IOSCapabilities capability = IOSCapabilities.ipad("Safari");
capability.setDeviceVariation(DeviceVariation.iPadRetina);

Oddly it returns a RemoteWebDriver with the following capabilities:
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, webdriver.remote.sessionid=3fc50a0a-84c4-47d0-953e-4b1a664d5f6c, version=11, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=http://localhost:47195/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]

I've shutdown all of my nodes apart from the iOS node run via 
java -jar /Applications/selenium/ios-server-standalone-0.6.6-SNAPSHOT.jar -hub http://qawintest4:4444/grid/register -proxy org.uiautomation.ios.grid.IOSMutableRemoteProxy -host macpro -port 5555 -newSessionTimeoutSec 40 

The test runs without the simulator ever starting up on the mac. My test takes a screenshot which for some reason is 948x343. But this never appears on the screen. It's as though it's using phantom js or something.

And yes my grid console still reports as 
WebDriver
v:nullnullnull

**Comment by JoolsCaesar** [comment]
@kumaravel-jayakumar 

The grid doesn't seem to be able to understand the iOS capability request properly. I was getting strange screenshots because it was actually running the test on other machines. My grid contains a handful of nodes of differing browsers and OSs.

If I request a web driver with the following capabilities:

Capabilities [{simulator=true, timeHack=false, locale=en_GB, CFBundleName=Safari, variation=iPadRetina, device=ipad, language=en, instruments=true}] 

The grid returns any of its nodes (Windows, Mac, Firefox, IE), perhaps in the order they were registered. So it only works if I shut down every other node forcing it to land on the correct one.

**Comment by kumaravel-jayakumar** [comment]
@JoolsCaesar 
I think this behavior is because your setup is using the DefaultCapabilityMatcher of selenium and you create a capability with "IOSCapabilities capability = IOSCapabilities.ipad("Safari");". This could create a capability with empty PLATFORM, BROWSER_NAME, and VERSION parameters. I think these parameters are used by Selenium to pick a node. You can use "org.uiautomation.ios.grid.IOSCapabilityMatcher" as a capabilites matcher when you start the grid with the option "-capabilityMatcher org.uiautomation.ios.grid.IOSCapabilityMatcher"

but this will match only IOS nodes and all other nodes will not be scanned due the limitation of IOSCapabilitesMatcher itself. This has to be addressed

The perfect thing would be to use a capability matcher like "SeLionCapabilitiesMatcher" as in "https://github.com/paypal/SeLion/blob/develop/server/src/main/java/com/paypal/selion/grid/internal/SeLionCapabilitiesMatcher.java", but you will have to create a jar using this lone class and feed it as a classpath parameter to the above command.

**Comment by JoolsCaesar** [comment]
I don't understand what you mean when you say,
"but this will match only IOS nodes and all other nodes will not be scanned due the limitation of IOSCapabilitesMatcher itself. This has to be addressed"

What you specified is the command to launch a node. Why would that stop my hub from matching all of the other nodes?

**Comment by JoolsCaesar** [comment]
I tried the command and it threw an exception "Unknown option: -capabilityMatcher"

**Comment by kumaravel-jayakumar** [comment]
@JoolsCaesar 
Sorry my bad, use that option -capabilityMatcher while starting your grid. I have updated the comment. The limitation I was talking about is the way in which IOSCapabilitiesMatcher is designed - it does not consider the other nodes in the grid. Just look into "https://github.com/ios-driver/ios-driver/blob/dev/grid/src/main/java/org/uiautomation/ios/grid/IOSCapabilityMatcher.java", where it does not delegate to the default matcher of sort if a match is not found. The other SeLionCapabilitesMatcher should give a idea.

**Comment by JoolsCaesar** [comment]
Thanks. I've written a one-liner capability matcher that tries with the ioscapabilitymatcher and falls back to the default. This has allowed me to move all my nodes back onto the same grid. I had temporarily been running two grids, with the ios node on its own.

I wonder what happened to this:
"You can run ios-driver as a regular node in a Selenium Grid. This allows you to scale your ios tests and to reuse your existing Selenium Grid infrastructure."

I definitely used to be able to do that. Now I need to specify a proxy for the node and include three extra jars to classpath of my customised hub. The latest hub command is:

java -cp ios-grid-plugin-0.6.6-SNAPSHOT.jar:ios-server-standalone-0.6.6-SNAPSHOT.jar:selenium-server-standalone-2.44.0.jar:OmniCapabilityMatcher.jar org.openqa.grid.selenium.GridLauncher -capabilityMatcher omni.OmniCapabilityMatcher -role hub

Anyway, thank you for all your help. I guess that's everything sorted apart from the hub console displaying:

IOSMutableRemoteProxy (version : 0.6.6-SNAPSHOT)
id : http://macpro:5555, OS : ANY
Browsers:
WebDriver
v:null
Configuration:
port:4444
servlets:[]
host:null
cleanUpCycle:5000
browserTimeout:0
hubHost:qawintest4
registerCycle:5000
capabilityMatcher:omni.OmniCapabilityMatcher
newSessionWaitTimeout:-1
remoteHost:http://macpro:5555
prioritizer:null
register:true
throwOnCapabilityNotPresent:true
nodePolling:5000
proxy:org.uiautomation.ios.grid.IOSMutableRemoteProxy
maxSession:1
role:hub
jettyMaxThreads:-1
hubPort:4444
timeout:300000

but as long as it's actually working, I'm not too bothered what it displays here. I guess it's just a side effect of having to use the custom proxy.

**Comment by mach6** [comment]
Please re-open if needed.

**Comment by arun290636** [comment]
I have followed above steps, now i am able to send request to Hub but my hub is not doing anything at all with my request.Using below line of code to initiate driver 
  var _Driver = new RemoteWebDriver(commandExecutorUri, DesiredCapabilities.IPad());

**Comment by arun290636** [comment]
Getting below response when i hit http://macpro:/wd/hub/capabilities/all
{"status":13,"value":{"message":"Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.\nActive sessions are[]","class":"org.openqa.grid.common.exception.GridException","stackTrace":[{"fileName":"ActiveTestSessions.java","lineNumber":110,"className":"org.openqa.grid.internal.ActiveTestSessions","methodName":"getExistingSession"},{"fileName":"Registry.java","lineNumber":423,"className":"org.openqa.grid.internal.Registry","methodName":"getExistingSession"},{"fileName":"RequestHandler.java","lineNumber":238,"className":"org.openqa.grid.web.servlet.handler.RequestHandler","methodName":"getSession"},{"fileName":"RequestHandler.java","lineNumber":119,"className":"org.openqa.grid.web.servlet.handler.RequestHandler","methodName":"process"},{"fileName":"DriverServlet.java","lineNumber":83,"className":"org.openqa.grid.web.servlet.DriverServlet","methodName":"process"},{"fileName":"DriverServlet.java","lineNumber":61,"className":"org.openqa.grid.web.servlet.DriverServlet","methodName":"doGet"},{"fileName":"HttpServlet.java","lineNumber":735,"className":"javax.servlet.http.HttpServlet","methodName":"service"},{"fileName":"HttpServlet.java","lineNumber":848,"className":"javax.servlet.http.HttpServlet","methodName":"service"},{"fileName":"ServletHolder.java","lineNumber":565,"className":"org.seleniumhq.jetty7.servlet.ServletHolder","methodName":"handle"},{"fileName":"ServletHandler.java","lineNumber":479,"className":"org.seleniumhq.jetty7.servlet.ServletHandler","methodName":"doHandle"},{"fileName":"SessionHandler.java","lineNumber":225,"className":"org.seleniumhq.jetty7.server.session.SessionHandler","methodName":"doHandle"},{"fileName":"ContextHandler.java","lineNumber":1031,"className":"org.seleniumhq.jetty7.server.handler.ContextHandler","methodName":"doHandle"},{"fileName":"ServletHandler.java","lineNumber":406,"className":"org.seleniumhq.jetty7.servlet.ServletHandler","methodName":"doScope"},{"fileName":"SessionHandler.java","lineNumber":186,"className":"org.seleniumhq.jetty7.server.session.SessionHandler","methodName":"doScope"},{"fileName":"ContextHandler.java","lineNumber":965,"className":"org.seleniumhq.jetty7.server.handler.ContextHandler","methodName":"doScope"},{"fileName":"ScopedHandler.java","lineNumber":117,"className":"org.seleniumhq.jetty7.server.handler.ScopedHandler","methodName":"handle"},{"fileName":"HandlerWrapper.java","lineNumber":111,"className":"org.seleniumhq.jetty7.server.handler.HandlerWrapper","methodName":"handle"},{"fileName":"Server.java","lineNumber":349,"className":"org.seleniumhq.jetty7.server.Server","methodName":"handle"},{"fileName":"AbstractHttpConnection.java","lineNumber":452,"className":"org.seleniumhq.jetty7.server.AbstractHttpConnection","methodName":"handleRequest"},{"fileName":"BlockingHttpConnection.java","lineNumber":47,"className":"org.seleniumhq.jetty7.server.BlockingHttpConnection","methodName":"handleRequest"},{"fileName":"AbstractHttpConnection.java","lineNumber":884,"className":"org.seleniumhq.jetty7.server.AbstractHttpConnection","methodName":"headerComplete"},{"fileName":"AbstractHttpConnection.java","lineNumber":938,"className":"org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler","methodName":"headerComplete"},{"fileName":"HttpParser.java","lineNumber":634,"className":"org.seleniumhq.jetty7.http.HttpParser","methodName":"parseNext"},{"fileName":"HttpParser.java","lineNumber":230,"className":"org.seleniumhq.jetty7.http.HttpParser","methodName":"parseAvailable"},{"fileName":"BlockingHttpConnection.java","lineNumber":66,"className":"org.seleniumhq.jetty7.server.BlockingHttpConnection","methodName":"handle"},{"fileName":"SocketConnector.java","lineNumber":254,"className":"org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint","methodName":"run"},{"fileName":"QueuedThreadPool.java","lineNumber":599,"className":"org.seleniumhq.jetty7.util.thread.QueuedThreadPool","methodName":"runJob"},{"fileName":"QueuedThreadPool.java","lineNumber":534,"className":"org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3","methodName":"run"},{"fileName":"Thread.java","lineNumber":745,"className":"java.lang.Thread","methodName":"run"}]}}
