### ISSUE TITLE
Licence not clear

### ISSUE THREAD

**Issue by marcpawl** [ios-driver/ios-driver#43]
Some files have an Apache 2.0 licence at the top, and some have no licence information at all.

The root of the project has no LICENCE file.

What is the licence for the project as a whole?

**Comment by freynaud** [comment]
Apache 2.
adding license : c85f7f3b7d4c94489df003a8efec1a3b3198d8db
it was also mentioned in the pom : https://github.com/ios-driver/ios-driver/blob/dev/pom.xml#L57
