### ISSUE TITLE
link missing for  server-standalone-1.0.0-SNAPSHOT.jar on website

### ISSUE THREAD

**Issue by marcpawl** [ios-driver/ios-driver#47]
http://ios-driver.github.io/ios-driver/setup.html

Launching ios-driver

Download server-standalone-1.0.0-SNAPSHOT.jar

The location for the jar file is not given.  The current selenium driver is selenium-server-standalone-2.32.0.  Is this the file needed?  If a specific file is needed, then it would be nice if it was in github source of the project, and link was provided to it.

**Comment by freynaud** [comment]
big blue banner at the top saying "download 0.6.0" :)

**Comment by marcpawl** [comment]
I saw that, the name of the file downloaded is different from the
instructions.  I though we had to download two files.
