### ISSUE TITLE
Import maven project from dev repo, dependency problem

### ISSUE THREAD

**Issue by ehongvc** [ios-driver/ios-driver#48]
Hi again,

Thanks for the fast response to my previous question. I have now cloned from the dev repo and tried to import all the projects into eclipse. However I am running into a dependency problem with ios-selenium-tests and ios-server.

Missing artifact org.uiautomation:ios-driver-jni:jar:0.7-SNAPSHOT   pom.xml 

I am quite new to this area, where can i find this artifact ?

Thanks!

**Comment by darraghgrace** [comment]
Hey there,

You need to take down a submodule..

cd into your project dir and run
git submodule init
git submodule update

that should do it for you.

**Comment by ehongvc** [comment]
Thank you for the fast response! I am quite new to this, appreciate the patience in helping me out.
