### ISSUE TITLE
Not able to connect to Safari on iphone simulator after following documentation

### ISSUE THREAD

**Issue by IlyasPatel** [ios-driver/ios-driver#51]
I have followed the documentation on this page - http://ios-driver.github.io/ios-driver/safari.html but have not been able to connect to the simulator. Steps I have followed:

```
sudo chmod 666 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator*.sdk/Applications/MobileSafari.app/Info.plist
```

I then start up selenium-standalone 2.32 on port 3001. I then run the sample code provided on the ios-driver site:

```
public static void main(String[] args) throws Exception {
DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:3001/wd/hub"), safari);

driver.get("http://www.ebay.co.uk/");

System.out.println(driver.getTitle());
driver.quit();
```

}

I get "unable to connect" error. Am I supposed to install webdriver on the simulator/device as well which I think is how the IPhoneDriver works?

I am using OSX Mountain Lion with all up-to-date software.

Thanks

**Comment by lukeis** [comment]
You need to download and run the ios-driver server jar (instead of Selenium's standalone server). 

Linked from the "download" link on the documentation pages. 
http://ios-driver.github.io/ios-driver/

https://s3-eu-west-1.amazonaws.com/ios-driver/ios-server-0.6.0.jar
