### ISSUE TITLE
Installed Applications are not visible 

### ISSUE THREAD

**Issue by dev-kumar** [ios-driver/ios-driver#56]
Testing with real device ipad .I have installed application on my device by xcode but,
Installed Applications are not visible on page http://localhost:5555/wd/hub/devices/all
i have followed all setup steps given on page http://ios-driver.github.io/ios-driver/setup.html

i'm using ios-server-0.6.0.jar and my code is

IOSCapabilities cap = IOSCapabilities.ipad("InternationalMountains", "1.1");
cap.setCapability(IOSCapabilities.DEVICE, DeviceType.ipad);
cap.setCapability(IOSCapabilities.SIMULATOR, false);
        cap.setCapability(IOSCapabilities.UUID,"uuid");
WebDriver driver = new RemoteIOSDriver(new URL("http://localhost:5555/wd/hub"), cap);

any help will be appreciated most

**Comment by nicegraham** [comment]
are you running ios-server-0.6.0.jar with the -beta flag? you need to be in order to use real devices.
http://ios-driver.github.io/ios-driver/setup.html#real

**Comment by dev-kumar** [comment]
yes i'm running ios-server-0.6.0.jar with -beta flag 
could you tell me the proper string to start ios-server for real device i just want to confirm.

result of http://localhost:5555/wd/hub/devices/all   page is--

iPad3,1 IOS:6.1.3(dev‚Äôs iPad)
Device info:

name: dev‚Äôs iPad
id: fad7e4gh93vfe5ea7
type: ipad
build: ---
product: iPad3,1
SDK: 6.1.3
Applications:

in console window where server is running ---- 

20:28:844 WARNING DeviceInstallerService.extractApplications  Error parsing the xml returned : null , xml=
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>

**Comment by dev-kumar** [comment]
hey nicegraham please suggest me how to resolve this warning

**Comment by nicegraham** [comment]
This should work:
java -jar ios-server-0.6.0.jar -beta -host your.ip.address.here -port 5555 

The device you're using has been provisioned for dev work? and the application has been prepared and deployed like the documentation?

**Comment by dev-kumar** [comment]
yes i have provisioned the device for dev  and the application has been deployed according to documentation. but still apps are not visible on page http://localhost:5555/wd/hub/devices/all

**Comment by nicegraham** [comment]
does it list the device at least?

**Comment by dev-kumar** [comment]
yes device is added in console where sever is running

**Comment by nicegraham** [comment]
Is the device listed on the devices/all page too?

It sounds like there's a problem with how you've deployed your app. In xcode I open my application, on the menu bar I select Product > Profile. This builds the app and then on the subsequent popup I select Automation and hit the profile button. This opens Instruments which you can close. At this point you should have an instrumented version of your app on the device. 

Even if you had ios-server running throughout that process the application should be available on the devices/all page if your refresh.

I've just done the above process and it all worked as expected.

**Comment by dev-kumar** [comment]
Error parsing the xml returned : null  
This error is displayed on console where server running . while opening the page http://localhost:5555/wd/hub/devices/all

yes the device is listed on this page

**Comment by nicegraham** [comment]
That would have been helpful earlier. 

What device is it, what ios version etc?

**Comment by dev-kumar** [comment]
Device is ipad and software version is 6.1.3

**Comment by dev-kumar** [comment]
All the applications installed on my ipad is displayed as an of plist in console window where server is running with a warning message Error parsing the xml returned : null

**Comment by nicegraham** [comment]
not sure what's happening for you. I just updated my os from 6.0.2 to 6.1.3 to match your situation and it works fine for me:
https://gist.github.com/nicegraham/5597507

**Comment by freynaud** [comment]
what's the name of your device ? Can you paste here the character that ios-driver cannot display. We'll try to reproduce on our end. A quick workaround for you  is to rename your device using asci characters. 

thanks,
françois

**Comment by dev-kumar** [comment]
my device name is Abhay iPad

**Comment by freynaud** [comment]
github can't display that either

**Comment by dev-kumar** [comment]
I have renamed the device and followed all the procedure but stucked with same error at same place..

**Comment by freynaud** [comment]
can you come on irc ? #ios-driver @ freenode

**Comment by dev-kumar** [comment]
Sorry for being late ..........
i'm using ipad3 , is it a reason in my case 
because i read some where Iphone3G does not support UIAutomation.

**Comment by nicegraham** [comment]
No, thats not the problem.

You'll need to come on irc as @freynaud asked for us to help you.

**Comment by dev-kumar** [comment]
As installed applications are not visible on link http://localhost:5555/wd/hub/devices/all.
Is it a ipad permission related issue ,i'm quite confuse. please tell me...

**Comment by nicegraham** [comment]
can you create a gist of the full console output after you launch like we talked about on irc? include the full xml output if there is any.

**Comment by dev-kumar** [comment]
Please check this console xml output...
https://gist.github.com/dev-kumar/2c4a597d878980e32949

**Comment by nicegraham** [comment]
Ok, the issue is this line:
https://gist.github.com/dev-kumar/2c4a597d878980e32949#file-gistfile1-txt-L4345

the empty node is throwing a null pointer - but we're the parsing code isn't ours so I don't know how to proceed... @freynaud ?

@dev-kumar is Scrumpad Pro your app? as a test could you try uninstalling it?

update: 
I created an issue here https://code.google.com/p/plist/issues/detail?id=42&thanks=42&ts=1369307086

**Comment by dev-kumar** [comment]
Thanks a lot to all of you for all your assistance .Finally i'm able to run on real device.
