### ISSUE TITLE
Unable to locate iTunesMetadata.plist in archive

### ISSUE THREAD

**Issue by dev-kumar** [ios-driver/ios-driver#60]
I have manually archived my app to test on real device but i'm getting error on console where ios server is running 
Error--
could not locate iTunesMetadat.plist in archive!
could not locate Payload/2012 Olympics.app/SC_Info/2012 Olympics.sinf in archive!

any help will be appreciated

**Comment by dev-kumar** [comment]
application is getting launched on real device but after some time instrument crashed error is displayed

**Comment by hzy00** [comment]
You have solved this problem？ Could you share the solution,please? Now, I'm in this dilemma.
