### ISSUE TITLE
Can't drive the mobile Safari in a real device 

### ISSUE THREAD

**Issue by baechul** [ios-driver/ios-driver#61]
I am not sure if it supported. 

http://localhost:4444/wd/hub/devices/all
shows the connected device.

The following codes run on the Safari in the simulator not on the real device.
DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), safari);

**Comment by nicegraham** [comment]
There currently isn't support for Mobile Safari on physical devices, it will eventually get limited support :
- no native event
- no window switching 
- no popup support

If safari on real device is a priority for you, please join us on irc, #ios-driver on freenode, and you can start contributing to the project.
