### ISSUE TITLE
iOS driver does't work with iOS app whose Localizable.strings file is in text format rather than binary [Follow-Up]

### ISSUE THREAD

**Issue by xuyuansi** [ios-driver/ios-driver#63]
This is a follow-up thread on issue https://github.com/ios-driver/ios-driver/issues/18
@nicegraham @freynaud 
Thanks for the code change!

I reverted the code to commit 2b56e9d, but it still doesn't work. While debugging into the code, I found: 
When PlistFileUtils.java executes ASCIIPropertyListParser.parse(bplist), and followed by ASCIIPropertyListParser executes expect(char... expectedSymbols), the code throws a ParseException containing the following message:
org.openqa.selenium.WebDriverException: Cannot parse info.plist : Expected '{' or '(' but found '"'

Does it mean that if the "bplist" file is parsed by ASCIIPropertyListParser, the "bplist" file is required to start with '{' or '('? But the app I am testing against is working well.

Then I reverted the code to commit HEAD, where PlistFileUtils.java contains change by commit 0c380d, the parsing still doesn't work because it has not yet support for a file starting with '"'.

Thanks

**Comment by freynaud** [comment]
remove all non generic parsing.

**Comment by xuyuansi** [comment]
Could you provide more details please? 

Thanks!

**Comment by xuyuansi** [comment]
Hello folks, 

Let me put it in a more detailed way. The following block of code is the place to read all the "l10nFiles" of the app, including the localization files:

  private Map<String, Object> read(File plist) {
    try {
      NSObject object = PropertyListParser.parse(plist); //<----- Place_A
      ApplicationInfo info = new ApplicationInfo(object);
      return info.getProperties();
    } catch (Exception ex) {
      throw new WebDriverException(
          "Cannot parse " + plist.getAbsolutePath() + ": " + ex.getMessage(), ex);
    }
  }

"PropertyListParser" on line "Place_A" comes from an artifact (com.googlecode.plist:dd-plist:1.3) which I cannot modify. 

Here is a challenge I bring: According to the JavaDoc, PropertyListParser is "JavaCC based parser for the PropertyList format". And Property list files use the filename extension .plist. Does it mean that PropertyListParser can only be safely used to parse files whose extension is .plist? However, iOS driver also use the parser to parse localizable.strings files which are not property list files because their extension is .strings rather than .plist. 

Thanks, 

Xuyuan

**Comment by freynaud** [comment]
9ee426eacb524affc736a9a0ac36faf6cd58c0de should fix the problem. Let us know if you still see the issue after this change.

@xuyuansi  The file extension doesn't impact its format.

**Comment by freynaud** [comment]
please try with https://s3-eu-west-1.amazonaws.com/ios-driver/ios-server-0.7.13d8f4db88688b0b6d4e6581118e421025c40027.jar and reopen if that doesn't fix your problem.
