### ISSUE TITLE
I do not succeed to start ios server from a remote PC

### ISSUE THREAD

**Issue by fsauvetgoichon** [ios-driver/ios-driver#64]
Hello,

I have a test execution frame running on a PC. I want to do test automation with webdriver on the IOS simulator located on a Mac.
It works fine as long as I start the ios server locally from the Mac.
But I would like to start the ios server from the PC. So I tried to start the server through an ssh connection.
The server starts correctly.
When I start my test script, I see the IOS simulator opened, Safari is opened, but nothing more happens.

In the log I can see 2 warnings that are not present in the local activation mode :

48:00:716 WARNING DefaultCommandListener.stderr  Failed to authorize rights (0x2) with status: -60007.
48:01:325 WARNING DefaultCommandListener.stderr  Failed to authorize rights (0x2) with status: -60007.

Did I miss anything ? Is there a way to start ios server remotely?
Thanks.

Regards
Francois

**Comment by freynaud** [comment]
Hi,
do you see what's happening on the remote mac ? There is a popup from instruments the first time you start it.

thanks,
François

**Comment by freynaud** [comment]
Hello,

do you still this this problem ?

**Comment by kazimiru** [comment]
Hi.
I have the same problem but i'm not starting simulator for the first time.
What could be wrong?

p.s. ios-server 0.6.2

**Comment by kazimiru** [comment]
Hmm...

found a problem for my case...

First I started ios-server remotely via ssh and no popup where shown.
Then I started ios-server directly from so called test machine and popup appeared asking for creds.

Is there any way to pass creds from script because we're planning to setup CI and starting ios-server from 
Hudson\Jenkins job could face this issue.

Thanks

**Comment by nicegraham** [comment]
No but if

dev is enabjed on the machine
your user is in the dev group
And
You have the allow root key in the access list

You may have to fill in the dialog once but after reboot it should persist.

**Comment by fsauvetgoichon** [comment]
Hello,
I finally changed to use appium, but I had the same problem.
In my case I solved the problem by

```
editing file /etc/authorization
modify key system.privilege.taskport
change value of allow-root to true
```

It is probably applicable to ios server too.
Regards

**Comment by nicegraham** [comment]
just in case someone else has this problem - we have this already documented on our FAQ:
http://ios-driver.github.io/ios-driver/faq.html
