### ISSUE TITLE
Not able to start server for web testing

### ISSUE THREAD

**Issue by rakesh725** [ios-driver/ios-driver#65]
rpatel:ios-driver rpatel$ java -jar ios-server-0.6.0.jar -beta -aut https://www.google.com
43:47:134 INFO ApplicationStore.<init>  App archive folder:/Users/rpatel/MobSources/Otsuka_Sprint7/ios-driver/applications
loading lib /generated/libiosdriver.jnilib
Exception in thread "main" org.openqa.selenium.WebDriverException: https://www.google.com isn't an IOS app.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.7.0_17'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:127)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:88)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:61)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:65)
43:49:474 INFO DeviceStore.onDeviceAdded  ADDED : Jacqueline's iPad,IOS 6.1.2[c54f3b97bcbe1ceed2cc8845f7240bb88b2005e3]

**Comment by nicegraham** [comment]
Hi,

Can you provide your test code? It looks like you're not specifying a valid application, it seems like you're specifying a URL as the application. 

Graham

**Comment by nicegraham** [comment]
sorry, I see in your first line you're specifying that url after the -aut, that's not correct - you use that flag if you want to add an application to the server, it should be a valid .app file. You should be just running:
java -jar ios-server-0.6.0.jar -beta -host your.ip.address.here -port 5555 

you can see more info on the flags here:
http://ios-driver.github.io/ios-driver/setup.html#cli

**Comment by rakesh725** [comment]
Thanks for the input. I was able to start the server, though getting
following error running the test. I did change the file permission as per:
http://freynaud.github.io/ios-driver/safari.html

I am trying to use ios-driver to run selenium test on iOS devices.

org.openqa.selenium.SessionNotCreatedException: error starting instrument
for session c3ff9a3b-7006-4a10-a3f8-917330a9aa9d, Cannot change the default
device for the
app./Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/Applications/MobileSafari.app/Info.plist
(Permission denied)
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3',
java.version: '1.7.0_17'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3',
java.version: '1.7.0_17'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3',
java.version: '1.7.0_17'
Driver info: driver.version: unknown
Command duration or timeout: 8.65 seconds
Build info: version: '2.31.0', revision:
'1bd294d185a80fa4206dfeab80ba773c04ac33c0', time: '2013-02-27 13:51:26'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3',
java.version: '1.7.0_17'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at
org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:187)
    at
org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:151)
    at
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
    at
org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
    at
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
    at
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
    at com.mob.selbase.utils.TestUtils.getWebDriver(TestUtils.java:149)
    at com.otsukaweb.caregiver.test.LoginTest.setUp(LoginTest.java:161)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:47)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:47)
    at org.junit.rules.RunRules.evaluate(RunRules.java:18)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

java.lang.NullPointerException
    at com.otsukaweb.caregiver.test.LoginTest.tearDown(LoginTest.java:172)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:36)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:47)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:47)
    at org.junit.rules.RunRules.evaluate(RunRules.java:18)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by nicegraham** [comment]
It's a permissions error, you can see the message....

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/Applications/MobileSafari.app/Info.plist

(Permission denied)
On 11 Jun 2013 18:09, "rakesh725" notifications@github.com wrote:

Thanks for the input. I was able to start the server, though getting
following error running the test. I did change the file permission as per:
http://freynaud.github.io/ios-driver/safari.html

I am trying to use ios-driver to run selenium test on iOS devices.

org.openqa.selenium.SessionNotCreatedException: error starting instrument
for session c3ff9a3b-7006-4a10-a3f8-917330a9aa9d, Cannot change the default
device for the
app./Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/Applications/MobileSafari.app/Info.plist

(Permission denied)
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3',
java.version: '1.7.0_17'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3',
java.version: '1.7.0_17'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3',
java.version: '1.7.0_17'
Driver info: driver.version: unknown
Command duration or timeout: 8.65 seconds
Build info: version: '2.31.0', revision:
'1bd294d185a80fa4206dfeab80ba773c04ac33c0', time: '2013-02-27 13:51:26'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3',
java.version: '1.7.0_17'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)

at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
at
org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:187)

at
org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:151)

at
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)

at
org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)

at
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
at
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
at com.mob.selbase.utils.TestUtils.getWebDriver(TestUtils.java:149)
at com.otsukaweb.caregiver.test.LoginTest.setUp(LoginTest.java:161)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:601)
at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)

at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)

at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)

at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)

at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:47)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:47)
at org.junit.rules.RunRules.evaluate(RunRules.java:18)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)

at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)

at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)

at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)

at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)

at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)

at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)

at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)

at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

java.lang.NullPointerException
at com.otsukaweb.caregiver.test.LoginTest.tearDown(LoginTest.java:172)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:601)
at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)

at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)

at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)

at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:36)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:47)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:47)
at org.junit.rules.RunRules.evaluate(RunRules.java:18)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)

at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)

at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)

at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)

at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)

at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)

at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)

at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)

at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

On Tue, Jun 11, 2013 at 12:04 PM, Graham Abell notifications@github.comwrote:

> sorry, I see in your first line you're specifying that url after the
> -aut,
> that's not correct - you use that flag if you want to add an application
> to
> the server, it should be a valid .app file. You should be just running:
> java -jar ios-server-0.6.0.jar -beta -host your.ip.address.here -port
> 5555
> 
> you can see more info on the flags here:
> http://ios-driver.github.io/ios-driver/setup.html#cli
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/ios-driver/ios-driver/issues/65#issuecomment-19284934>
> .

—
Reply to this email directly or view it on
GitHubhttps://github.com/ios-driver/ios-driver/issues/65#issuecomment-19295845
.

**Comment by rakesh725** [comment]
As per your instructions:
rpatel:selenium rpatel$ chmod +rw
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/
rpatel:selenium rpatel$ chmod +rw
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/Applications/MobileSafari.app/Info.plist
rpatel:selenium rpatel$ ls -l
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/Applications/MobileSafari.app/Info.plist
-rw-r--r--  1 root  wheel  1847 Oct 17  2012
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/Applications/Mobile

Not able to change permission on oug:
rpatel:selenium rpatel$ chmod oug+rw
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/Applications/MobileSafari.app/Info.plist
chmod: Unable to change file mode on
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/Applications/MobileSafari.app/Info.plist:
Operation not permitted

Thanks,
Rakesh

**Comment by nicegraham** [comment]
You'll probably need to sudo

**Comment by rakesh725** [comment]
Yes, I did sudo, was able to change permission.

I am getting following exception running tests:

_exception on eclispe:
*org.openqa.selenium.WebDriverException: cannot find command for GET, /
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3',
java.version: '1.7.0_17'
Driver info: driver.version: unknown
    at
org.uiautomation.ios.communication.WebDriverLikeCommand.getCommand(WebDriverLikeCommand.java:289)
    at
org.uiautomation.ios.communication.WebDriverLikeRequest.getGenericCommand(WebDriverLikeRequest.java:115)
    at
org.uiautomation.ios.communication.WebDriverLikeRequest.getVariableValue(WebDriverLikeRequest.java:119)
    at
org.uiautomation.ios.communication.WebDriverLikeRequest.getSession(WebDriverLikeRequest.java:132)
    at
org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at
org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:82)
    at
org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:45)_

*
_Error on terminal:_
org.openqa.selenium.WebDriverException: cannot find command for GET, /
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3',
java.version: '1.7.0_17'
Driver info: driver.version: unknown
    at
org.uiautomation.ios.communication.WebDriverLikeCommand.getCommand(WebDriverLikeCommand.java:289)
    at
org.uiautomation.ios.communication.WebDriverLikeRequest.getGenericCommand(WebDriverLikeRequest.java:115)
    at
org.uiautomation.ios.communication.WebDriverLikeRequest.getVariableValue(WebDriverLikeRequest.java:119)
    at
org.uiautomation.ios.communication.WebDriverLikeRequest.getSession(WebDriverLikeRequest.java:132)
    at
org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at
org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:82)
    at
org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:45)

*
*
*Test:
*
*
-    DesiredCapabilities safari = DesiredCapabilities.iphone();
      RemoteWebDriver driver = new RemoteWebDriver(new URL("
  http://localhost:5555/wd/hub"), safari);
  
  ```
  // And now use this to visit Google
  driver.get("http://www.google.com");
  ```

Appreciate your help...
