### ISSUE TITLE
push jar to public maven

### ISSUE THREAD

**Issue by nicegraham** [ios-driver/ios-driver#66]
this came up after the talk today - I forgot we never actually pushed this, I know we talked about it...

**Comment by ags313** [comment]
If you're busy I could actually help with that.

**Comment by nicegraham** [comment]
I believe @lukeis was supposed to be sorting that out... :)

**Comment by rgrzesk** [comment]
@lukeis any news about the issue?

**Comment by nicegraham** [comment]
@robal7 @ags313 I've opened a ticket to get this resolved.

**Comment by nicegraham** [comment]
@ags313 I think you've already created the repository... do you want to catch up on irc to push something up?

**Comment by nicegraham** [comment]
it's done:
http://repo1.maven.org/maven2/org/uiautomation/
