### ISSUE TITLE
Cannot connect to app if it returns an empty list of supported languages

### ISSUE THREAD

**Issue by freynaud** [ios-driver/ios-driver#7]
If the AUT returns an empty list of languages then it's impossible to create a new session. Either an exception is thrown because "en" can't be found in the list of languages, or, if the capabilities have the language nulled out, an exception of "org.openqa.selenium.SessionNotCreatedException: Cannot find null in the supported languages for the app." is thrown.

**Comment by freynaud** [comment]
The same issue was there in my case. I have managed to talk to my developers and enabled some languages in my application.

**Comment by freynaud** [comment]
added to 0.6 TODO.

**Comment by freynaud** [comment]
I've managed to get around this by adding

`currentLanguage = new AppleLocale("en");
//throw new WebDriverException("Cannot find " + lang + " in the supported languages for the app.");`

at the end of setLanguage() and adding

`return new AppleLocale("en");
//throw new WebDriverException("Cannot find AppleLocale for " + languageCode);`

at the end of getAppleLocaleFromLanguageCode() in IOSApplication.java. Basically sets the default locale to English if its null within the bundle info. This was just a quick fix, I've yet to see the implications on localized strings.

**Comment by freynaud** [comment]
I have a fix working locally. I need some more tests to validate everything and I'll push the changes.

The localized stuff is used for selectors.
If you don't have it, you end up having hardcoded content ;
 By selector = By.xpath("//UIAStaticText[contains(@name,'climbed')]");
   if you have the l10n loaded, you can have :+1: 
By contentFree = By.xpath("//UIAStaticText[matches(@name,l10n('sentenceFormat'))]");

instead.

**Comment by freynaud** [comment]
Awesome. As I said, this was a quick fix; looking forward to updates, our team is very interested in this project.

**Comment by freynaud** [comment]
I've seen something similar - basically when running tests in Safari, Safari doesn't have "en" available as a language but it does list "en_GB" but that then causes problem when it tries to set the locale because it can't one matching "en_GB". 

I've added a workaround locally that if the language is "en_GB" in the set locale method then I convert it to "en" for the purposes of finding the locale. 

Is this just my setup and does Safari list "en" as a supported language for everyone else?

**Comment by freynaud** [comment]
Can you try with 0.6 beta from here :
https://s3-eu-west-1.amazonaws.com/ios-driver/ios-server-0.6.0-SNAPSHOT.jar

The new behavior is :
- if the app doesn't have any localization folder, let you pick any language, but the l10n(key) function won't be available.
- if the app has some localization folder, you can only start in one of those language ( so for the intlMountain example that support [fr,zh,en] , starting with de will throw.

@nicegraham : Can you post the list of supported language you see in wb/hub/status. en should be supported ( but won't be visible if you open the .app. In the .app you'll probably see "English" )
The reason is explain here :
name for localization has changed in 10.4 from English , French ( old ) to en , fr ( new )
http:// stackoverflow.com/questions/7051120/why-doesnt-my-file-move-into-en-lproj-but-instead-into- a-new-english-lproj

**Comment by freynaud** [comment]
sure, the supported languages are:
"hu","it_IT","pt_PT","zh_TW","en_GB","no","sk","ro","zh_CN","en_SG","th","iw_IL","tr","cs","fi","ca","uk","de","es","ru","in_ID","ko","vi","hr","pt","nl","ar","pl","fr","da","sv","ja_JP","el","ms"

full details:
https://gist.github.com/freynaud/4999800

**Comment by freynaud** [comment]
is that with 0.6 beta from here :
https://s3-eu-west-1.amazonaws.com/ios-driver/ios-server-0.6.0-SNAPSHOT.jar

It should show the commit id, not unknown

**Comment by freynaud** [comment]
apologies, no it was running it from source [but probably a couple of days old]. I'm on a different laptop now but I'm getting the same kind of list [no "en"].

status:
https://gist.github.com/nicegraham/4999885

**Comment by freynaud** [comment]
no sure where the difference comes from. I checked on some old xcode, new ones. I always have English.lproj in safari :
https://gist.github.com/freynaud/5000141

**Comment by freynaud** [comment]
I'm getting pretty much the same on my machine:
https://gist.github.com/nicegraham/5003641

Could it be and Irish thing?! @darraghgrace could you check one of your machines?

**Comment by freynaud** [comment]
I'm getting the same
https://gist.github.com/darraghgrace/5004245

**Comment by freynaud** [comment]
with 0.6 beta from here ? https://s3-eu-west-1.amazonaws.com/ios-driver/ios-server-0.6.0-SNAPSHOT.jar

**Comment by freynaud** [comment]
Using https://s3-eu-west-1.amazonaws.com/ios-driver/ios-server-0.6.0-SNAPSHOT.jar the output for wd/hub/status is.....

OS X 10.8.2 - https://gist.github.com/darraghgrace/5004710

and OS X 10.7.5 - https://gist.github.com/darraghgrace/5004741

**Comment by freynaud** [comment]
just to wrap this up - it's not happening in the newest code

**Comment by contactkkiran** [comment]
Hi Freynaud,

I'm new to IOSDriver, I was evaluating this tool and was able to run the sample app 'InternationalMountains' successfully. However, for further evaluation, I tried to run the tests on a different app 'AustralianPostcodes' and I'm getting the below exception:

I checkout the latest code and build the  IOS server jar and still i was facing the same issue. Also tried other jars that were mentioned in Issue thread but no luck. Appreciate for any quick help on this issue

Caused by: org.openqa.selenium.SessionNotCreatedException: Language requested, en ,isn't supported.Supported are : []
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.2', java.version: '1.6.0_45'
Driver info: driver.version: IOSDriver

Regards,
Kiran

**Comment by nicegraham** [comment]
@contactkkiran can you look at this thread:
https://groups.google.com/forum/?fromgroups=#!topic/ios-driver/a0sDcTCfqt8

**Comment by contactkkiran** [comment]
Hi Graham,

I tried the workaround.I had created the dummy strings file under Resources
folder and still I'm getting the same error. Could you please point me to
some sample apps with which i can continue my evaluation.

Regards,
Kiran

On Sat, Apr 20, 2013 at 8:19 PM, Graham Abell notifications@github.comwrote:

> @contactkkiran https://github.com/contactkkiran can you look at this
> thread:
> https://groups.google.com/forum/?fromgroups=#!topic/ios-driver/a0sDcTCfqt8
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ios-driver/ios-driver/issues/7#issuecomment-16705169
> .

## 

Regards,
Kiran K

**Comment by nicegraham** [comment]
what about the other questions I asked in that thread? do the folders and files exist?

most freely available sample apps should work. Once we tested the basics in the tutorials we moved onto our actual apps which we wanted to test.

**Comment by contactkkiran** [comment]
Hi Graham,

I dont see the language folders. I could see Just the resource folders.
Attached is the project screen shot.

Regards,
Kiran

On Sat, Apr 20, 2013 at 11:10 PM, Graham Abell notifications@github.comwrote:

> what about the other questions I asked in that thread? do the folders and
> files exist?
> 
> most freely available sample apps should work. Once we tested the basics
> in the tutorials we moved onto our actual apps which we wanted to test.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ios-driver/ios-driver/issues/7#issuecomment-16708037
> .

## 

Regards,
Kiran K
