### ISSUE TITLE
Is there a way to run PlistBuddy and update Settings value for a native App?

### ISSUE THREAD

**Issue by skdaniel** [ios-driver/ios-driver#71]
I would like to change the config settings of an app.

**Comment by freynaud** [comment]
what values do you need to update ?

**Comment by skdaniel** [comment]
We have a native app, that can login to different production servers.
The users have the option to change the server URL value.
The value can be changed either by going to Settings-- App Name --Change the value (or)
from the command line I can  /usr/lib/PlistBuddy -c "Set server-host hostURL"  com.company.App
I would like this to be available programmatically or through some startup settings while testing using iOS-Driver

**Comment by freynaud** [comment]
is this plist inside your app or is it a the setting plist ? I assume this is only working on simulator.
If you can come on IRC, #ios-driver on freenode to discuss exactly what you need, that would help.
I think we have some code already close to what you're asking for, so it should be easy-ish

**Comment by lukeis** [comment]
gonna close this, I think we have a working idea of a solution :)
