### ISSUE TITLE
With Ruby-binding getting undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by rohitkadam19** [ios-driver/ios-driver#73]
Structure for my test :-
1. I have one sinatra server running(after hitting url for this sinatra server it will open a page. Page has html buttons)
2. Now I run ios server using command:-
      java -jar ios-server-0.6.0.jar
3. It started server at 5555 port
4. I started iOS simulator(5.0) manually on my machine.
5. Now I am running my ruby code to get the webdriver object. It looks as:-

```
 require 'selenium-webdriver'
 driver = Selenium::WebDriver.for :remote, :url => "http://localhost:5555/wd/hub", :desired_capabilities => :iphone
```
1. After running above code I get error as 
   NoMethodError: undefined method `downcase' for nil:NilClass
   from /Users/neerajapte/.rvm/gems/ruby-1.9.2-p290/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/remote/capabilities.rb:139:in`json_create'
   from /Users/neerajapte/.rvm/gems/ruby-1.9.2-p290/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/remote/bridge.rb:96:in `create_session'
   from /Users/neerajapte/.rvm/gems/ruby-1.9.2-p290/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/remote/bridge.rb:68:in`initialize'
   from /Users/neerajapte/.rvm/gems/ruby-1.9.2-p290/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/common/driver.rb:33:in `new'
   from /Users/neerajapte/.rvm/gems/ruby-1.9.2-p290/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver/common/driver.rb:33:in`for'
   from /Users/neerajapte/.rvm/gems/ruby-1.9.2-p290/gems/selenium-webdriver-2.31.0/lib/selenium/webdriver.rb:67:in `for'
   from (irb):2
   from /Users/neerajapte/.rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in`<main>'
2. Here in above steps, I am not sure whether my setup is incorrect or there is bug in ruby bindings.

**Comment by nicegraham** [comment]
can you try this with selenium 2.33.0?

**Comment by nicegraham** [comment]
can you try with the latest version https://github.com/ios-driver/ios-driver/releases/tag/0.6.2 and reopen if you still have problems
