### ISSUE TITLE
Regarding Region Format Change Issue

### ISSUE THREAD

**Issue by faisalkarim16** [ios-driver/ios-driver#74]
This is a weird one. Here is what I am doing -
1. Starting ios-server (java -jar ios-server-0.6.0.jar -aut 'application/Test iOS App.app' -port 4444)
2. Created test case using Java and TestNG test framework.
3. Run test using ANT
4. Test runs successfully on simulator

Here is the weird issue I am facing after test run is finished. 
1. I launched the simulator.
2. Tapped on settings
3. Tapped on General
4. Tapped on International
5. I see Region Format is changed from United States to United Kingdom

NOTE: I am not defining region format or language change anywhere in my code. Specifically when initializing the driver with DesiredCapabilities. Here is the code that initializes the driver -

DesiredCapabilities capabilities = IOSCapabilities.ipad( "Test iOS App" );
RemoteWebDriver remoteWebDriver = new RemoteWebDriver( "http://localhost:4444/wd/hub", capabilities );
// Click a button by name
remoteWebDriver.quit()

I don't see any reason why the Region Format would change because of this. Any ideas?

Thanks in advance everyone. Let me know if any questions.

**Comment by freynaud** [comment]
this is working as expected. If you don't specify anything, each new simulator starting by ios-driver defaults to language= english and  locale=UK.

https://github.com/ios-driver/ios-driver/blob/dev/common/src/main/java/org/uiautomation/ios/IOSCapabilities.java#L96
thanks,
François

**Comment by faisalkarim16** [comment]
Thank you so much for pointing this out. I set my locale to en_US and now Region sets as US.
