### ISSUE TITLE
inspector not working for app in landscape mode

### ISSUE THREAD

**Issue by nicegraham** [ios-driver/ios-driver#79]
we have an app that's locked to landscape...

**Comment by aneesha14** [comment]
We've been facing the same issue as our app is landscape only.

**Comment by nicegraham** [comment]
We've gotten around this limitation for the minute by removing the lock for debug builds so we can view the app in portrait.

**Comment by nicegraham** [comment]
fixed in https://github.com/ios-driver/ios-driver/releases/tag/0.6.2
