### ISSUE TITLE
driver.switchTo().alert().sendKeys("") is not working.

### ISSUE THREAD

**Issue by freynaud** [ios-driver/ios-driver#8]
First of all,

Kudos for making such a great effort to share your tools with fellow Automation Engineers community.

Now to my question:

I have a Native alert which shows up when I click a button on my iOS App. I want to type (sendkeys) in the text box which shows as an alert to the user. I am using : driver.switchTo().alert().sendKeys("Test") but its not working. Is there something I am doing wrong? 

Also if this feature is under development, Is there a work around ?

**Comment by freynaud** [comment]
you're now doing anything wrong, I have implemented that feature only for safari so far.
I'll add that on the todo for 0.6.

**Comment by freynaud** [comment]
@freynaud Thanks!. Waiting for the feature.

**Comment by freynaud** [comment]
There is a workaround while you're waiting for the proper fix.
Alert aren't very special for ios-driver, they're a WebElement like everything else. Alert have the magic id ="3".

If there is an alert displayed on the screen, you can grab it doing :
RemoteWebElement rwe = new RemoteWebElement();
rwe.setParent(driver);
rwe.setId("3");

that give you a handle to the alert. Then you can find whatever you need on the alert. Assuming there is a single button, you can accessing it with the following findElement

WebElement element =rwe.findElement(By.className("UIAButton"));

and discard the alert by clicking that button
element.click();

**Comment by lukeis** [comment]
@freynaud did this get implemented in 0.6?  /cc @mpsingh01

**Comment by freynaud** [comment]
fixed and test added :https://github.com/ios-driver/ios-driver/blob/dev/server/src/test/java/org/uiautomation/ios/e2e/uicatalogapp/AlertTest.java#L240
