### ISSUE TITLE
An apostrophe problem

### ISSUE THREAD

**Issue by xuyuansi** [ios-driver/ios-driver#82]
Hello, 

When I try to find an element by xpath, if the value contains an apostrophe like below, it won't work and it will report "org.openqa.selenium.InvalidSelectorException: wrong xpath //UIAButton[matches(@name,'It's a value with an apostrophe')]".

driver.findElement(By.xpath("//UIAButton[matches(@name, "It's a value with an apostrophe")]"))

By debugging into the server code, an exception throws at the following line in file XPath2Engine.java (at line 137): 
XPathExpression expr = xpath2.compile(xpath); 

I am sure that the apostrophe brings the problem because things work well if I remove it. 

Thanks, 

Xuyuan

**Comment by nicegraham** [comment]
can you try:

driver.findElement(By.xpath("//UIAButton[matches(@namehttps://github.com/name,
concat('It', "'", 's a value with an apostrophe'))]"))

**Comment by xuyuansi** [comment]
It works. Thank you!

But how about using localization string? For example: 

By by = By.xpath("//UIATextField[matches(@value,l10n('a_localization_string_whose_target_contains_an_aphostrophy'))]");

If a_localization_string_whose_content_contains_an_aphostrophy points to a string like   It's-an-apostrophy   , then finding the element by localization string will be converted to finding the element by "It's-an-aphostrophy" which I cannot modify its format. 

Thanks, 

Xuyuan

**Comment by freynaud** [comment]
escape special characters in LanguageDictionary#getRegexPattern

**Comment by freynaud** [comment]
673ec375e5fab24f2dc486f80b4427fe4c177959 should solve it.
