### ISSUE TITLE
JavaScript support?

### ISSUE THREAD

**Issue by AndyKriger** [ios-driver/ios-driver#83]
We have Selenium code that relies heavily on its ability to execute JavaScript. This code runs using iWebDriver, however, while trying to replace that with ios-driver and running tests against Mobile Safari running in a simulator, we are running into this error...

`#<Selenium::WebDriver::Error::UnsupportedOperationError: underlying webdriver instance does not support javascript>`

Can you confirm ios-driver support or lack of support for executing JavaScript via Selenium?

**Comment by AndyKriger** [comment]
[This conversation](https://github.com/SeleniumHQ/irc-logs/blob/master/2013/04/24.txt#L713) appears to address the question. If it is the case, as it appears from that conversation, that execute_script does not work in 0.6.0, when will 0.7.0 be available? The alpha jar referenced in the conversation does appear to fix the problem, but having a properly stable release would be better.

**Comment by nicegraham** [comment]
your'e using Ruby?

the latest code is stable enough to run tests on simulators, real device support is kinda broken right now so it depends on what you're trying to do.

We don't have a date for 0.7.0 - but any help provided would speed it along :)

**Comment by ianrhamilton** [comment]
I am using Ruby with selenium-webdriver and when I try to click on an element in the browser (within simulator) and I get the same error.

"underlying webdriver instance does not support javascript (Selenium::WebDriver::Error::UnsupportedOperationError)"

In that thread unless I misunderstood said it would be fixed in selenium-webdriver 2.33.0?

Is there a workaround for this issue?

**Comment by ianrhamilton** [comment]
updated to the beta jar and its working fine!

**Comment by bobstiles** [comment]
adding the javascript_enabled = true fixes this.

driver = Selenium::WebDriver.for :remote, :url => "http://localhost:4444/wd/hub", :desired_capabilities => :ipad
driver.capabilities.javascript_enabled=true
