### ISSUE TITLE
driver needs to keep track of closing windows and keep the correct window focused.

### ISSUE THREAD

**Issue by rgrzesk** [ios-driver/ios-driver#88]
Exception in thread "DefaultMessageHandler-51" org.openqa.selenium.WebDriverException: 0 new pages.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_45'
Driver info: driver.version: unknown
    at org.uiautomation.ios.wkrdp.WebKitNotificationListener.onMessage(WebKitNotificationListener.java:93)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.process(DefaultMessageHandler.java:76)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.access$000(DefaultMessageHandler.java:31)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler$1.run(DefaultMessageHandler.java:64)

Hi!

I have this exception after every navigation or interrogation on page.

**Comment by freynaud** [comment]
Can you give us the test that you're running when that happens ?

**Comment by rgrzesk** [comment]
@Test
    public void testIOS() throws Exception
    {
    WebDriver edriver = new IPhoneDriver("http://192.168.35.236:4444/wd/hub");

```
    edriver.get("http://www.ebay.co.uk");

    System.err.println(edriver.getTitle());
    edriver.get("http://www.google.pl");
    System.err.println(edriver.getCurrentUrl());

    edriver.get("http://book.theautomatedtester.co.uk/chapter4");
    WebElement element = edriver.findElement(By.id("nextBid"));
    element.sendKeys("100");
    Thread.sleep(5000);
    String title = edriver.getTitle();
    System.err.println(title);
    edriver.navigate().to("http://www.cognifide.com");

    edriver.quit();

}
```

**Comment by freynaud** [comment]
problem with closed window.

**Comment by freynaud** [comment]
13d8f4db88688b0b6d4e6581118e421025c40027 should get rid of that exception.

**Comment by freynaud** [comment]
please try https://s3-eu-west-1.amazonaws.com/ios-driver/ios-server-0.7.13d8f4db88688b0b6d4e6581118e421025c40027.jar and  reopen is that doesn't solve your issue.
