### ISSUE TITLE
Support -browser   parameter while registering ios-driver to Selenium grid

### ISSUE THREAD

**Issue by mdiwakar** [ios-driver/ios-driver#94]
I have configured ios-driver to be one of the nodes on our selenium hub,

java -jar ios-server-0.6.0.jar -host xyz.com -hub http://mymachine.corp.hub.com:4444/grid/register 

we have scenario where we would like to connect to specific ios-driver node to execute test. I was looking at something similar on this line

-browser browserName=iPhone,version=xyz,platform=MAC,simulator=true

java -jar ios-server-0.6.0.jar -host xyz.com -hub http://mymachine.corp.hub.com:4444/grid/register  -browser browserName=iPhone,version=xyz,platform=MAC,simulator=true

so when i pass this parameter values to create DesiredCapabilities, test should be routed to device or ios-simulator on this node

**Comment by nicegraham** [comment]
are you running tests on mobile safari or a native app? 

We currently register the CFBundleVersion so on safari this is pretty static but for your own app it usually has a more frequent version update. 

The only one of those which would differentiate one node from another in the version property. Simulator is already registered true/false in the capabilities so if you want to target sims or real devices that's already possible. 

maybe you can elaborate a bit more on what part of the node you're trying to target.

**Comment by mdiwakar** [comment]
Graham and Roman thanks for quick reply,

Graham,
I am running tests on mobile safari,

Scenario: I register 2 mac node on selenium grid. on first node I start
ios-server with browser version as sim1 and on second node I start
ios-server with browser version as sim2.

I can pass browser version as sim1  or sim2  to route the test to be
executed on ios-server node1 or ios-server node 2

Hi Roman
Could you please point me from where can i download 0.7.0, I am using 0.6.1

Regards,
Milind

**Comment by rdissertori** [comment]
Strange, seems I accidently removed my post. Anyways, I was building 0.7.0 from this dev branch and built it myself (via maven) I don't know if theres any existing 0.7.0 build package on this project.

**Comment by nicegraham** [comment]
hey @mdiwakar 
The latest code as of Friday can be found here: https://github.com/ios-driver/ios-driver/releases/tag/0.6.1

you should use the with dependencies jar. I want to caveat that real device support is broken in this build.

**Comment by mdiwakar** [comment]
Graham, I see #61  and #49  are closed is the real device support only for Apps,  any plan to support mobile safari on real devices in near future?  most of the time the issue reproduced on devices can not be reproduced on simulators. so even though we have great coverage, its not adequate if we running our tests only on simulators.

**Comment by nicegraham** [comment]
currently real device support is only available for apps. We are working on that and should be able to provide at least some support for safari on real apps in the future.

**Comment by nicegraham** [comment]
@mdiwakar I think based on your comments above this issue has been resolved, please reopen if not.

**Comment by mdiwakar** [comment]
graham,
I dont think the issue is resolved, I still dont see a way to configure node on grid based on browser param

"Support -browser parameter while registering ios-driver to Selenium grid" or may be i am missing some thing if this is documented somewhere.

**Comment by nicegraham** [comment]
That sounded like an implementation detail - your requirement was to be able to target specific grid nodes which you said you were able to do via the version field. Why do you still want to edit the browser field?

I'll speak to some of the other guys about this - I'm pretty sure we're standardising what gets sent as platform and browser amongst all the mobile projects so we will need to adhere to that. 

In the meantime you can not set the -hub value and register the node using whatever values you want in an external process like https://github.com/davehunt/flynnid

**Comment by freynaud** [comment]
the registration of a node does NOT have to be part of ios-driver itself. It's a simple http rest request that you send to the hub and that describe your node. You can build whatever makes sense for your architecture reading the result of a /status of the server.
François
